/*
 *  Copyright 2018 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) iar.targets.msp430; 1, 0, 0,0; 7-20-2018 13:58:48; /db/ztree/library/trees/xdctargets/xdctargets-r09/src/ xlibrary

 */

