xwr64xx/mmw/mmw_configPkg_xwr64xx/package/cfg/mmw_per4ft.c File Reference
mmw_per4ft.c File Reference
#include <xdc/std.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/family/arm/IntrinsicsSupport.h>
#include <ti/sysbios/family/arm/TaskSupport.h>
#include <ti/sysbios/family/arm/a15/TimestampProvider.h>
#include <ti/sysbios/family/arm/exc/Exception.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/tms570/Core.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/gates/GateHwi.h>
#include <ti/sysbios/gates/GateMutex.h>
#include <ti/sysbios/hal/Cache.h>
#include <ti/sysbios/hal/CacheNull.h>
#include <ti/sysbios/hal/Core.h>
#include <ti/sysbios/hal/Hwi.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Idle.h>
#include <ti/sysbios/knl/Intrinsics.h>
#include <ti/sysbios/knl/Queue.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/timers/rti/Timer.h>
#include <ti/sysbios/utils/Load.h>
#include <xdc/runtime/Assert.h>
#include <xdc/runtime/Core.h>
#include <xdc/runtime/Defaults.h>
#include <xdc/runtime/Diags.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Gate.h>
#include <xdc/runtime/Log.h>
#include <xdc/runtime/LoggerBuf.h>
#include <xdc/runtime/Main.h>
#include <xdc/runtime/Memory.h>
#include <xdc/runtime/Registry.h>
#include <xdc/runtime/Startup.h>
#include <xdc/runtime/SysStd.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Text.h>
#include <xdc/runtime/Timestamp.h>
#include <xdc/runtime/TimestampNull.h>
#include <limits.h>
#include <xdc/runtime/Types.h>
#include <xdc/runtime/System__internal.h>
#include <_lock.h>
#include <string.h>
Data Structures
struct ti_sysbios_BIOS_RtsGateProxy_Module__
struct ti_sysbios_knl_Queue_Object__
struct ti_sysbios_knl_Queue_Object2__
struct ti_sysbios_knl_Semaphore_Object__
struct ti_sysbios_knl_Semaphore_Object2__
struct ti_sysbios_gates_GateMutex_Object__
struct ti_sysbios_gates_GateMutex_Object2__
struct ti_sysbios_BIOS_RtsGateProxy_Object2__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Object2__
struct ti_sysbios_gates_GateHwi_Module__
struct ti_sysbios_gates_GateHwi_Object__
struct ti_sysbios_gates_GateHwi_Object2__
struct ti_sysbios_gates_GateMutex_Module__
struct ti_sysbios_hal_Hwi_Module__
struct ti_sysbios_hal_Hwi_Object__
struct ti_sysbios_hal_Hwi_Object2__
struct ti_sysbios_hal_Hwi_HwiProxy_Module__
struct ti_sysbios_hal_Hwi_HwiProxy_Object2__
struct ti_sysbios_heaps_HeapBuf_Module__
struct ti_sysbios_heaps_HeapBuf_Object__
struct ti_sysbios_heaps_HeapBuf_Object2__
struct ti_sysbios_heaps_HeapMem_Module__
struct ti_sysbios_heaps_HeapMem_Object__
struct ti_sysbios_heaps_HeapMem_Object2__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Object2__
struct ti_sysbios_knl_Clock_Module__
struct ti_sysbios_knl_Clock_Object__
struct ti_sysbios_knl_Clock_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Module__
struct ti_sysbios_timers_rti_Timer_Object__
struct ti_sysbios_timers_rti_Timer_Object2__
struct ti_sysbios_knl_Clock_TimerProxy_Object2__
struct ti_sysbios_knl_Event_Module__
struct ti_sysbios_knl_Event_Object__
struct ti_sysbios_knl_Event_Object2__
struct ti_sysbios_knl_Queue_Module__
struct ti_sysbios_knl_Semaphore_Module__
struct ti_sysbios_knl_Task_Module__
struct ti_sysbios_knl_Task_Object__
struct ti_sysbios_knl_Task_Object2__
struct ti_sysbios_timers_rti_Timer_Module__
struct xdc_runtime_LoggerBuf_Module__
struct xdc_runtime_LoggerBuf_Object__
struct xdc_runtime_LoggerBuf_Object2__
struct xdc_runtime_LoggerBuf_Module_GateProxy_Module__
struct xdc_runtime_LoggerBuf_Module_GateProxy_Object2__
struct xdc_runtime_Main_Module__
struct xdc_runtime_Main_Module_GateProxy_Module__
struct xdc_runtime_Main_Module_GateProxy_Object2__
struct xdc_runtime_Memory_HeapProxy_Module__
struct xdc_runtime_Memory_HeapProxy_Object2__
struct xdc_runtime_System_Module_GateProxy_Module__
struct xdc_runtime_System_Module_GateProxy_Object2__
struct ti_sysbios_BIOS_Module_State__
struct ti_sysbios_family_arm_a15_TimestampProvider_Module_State__
struct ti_sysbios_family_arm_exc_Exception_Module_State__
struct ti_sysbios_family_arm_v7a_Pmu_Module_State__
struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
struct ti_sysbios_heaps_HeapBuf_Module_State__
struct ti_sysbios_knl_Clock_Module_State__
struct ti_sysbios_knl_Task_Module_State__
struct ti_sysbios_timers_rti_Timer_Module_State__
struct ti_sysbios_utils_Load_Module_State__
struct xdc_runtime_Error_Module_State__
struct xdc_runtime_LoggerBuf_Module_State__
struct xdc_runtime_Memory_Module_State__
struct xdc_runtime_Registry_Module_State__
struct xdc_runtime_Startup_Module_State__
struct xdc_runtime_System_Module_State__
struct xdc_runtime_Text_Module_State__
union Header
struct ti_sysbios_family_arm_v7r_vim_Hwi___S1
struct ti_sysbios_gates_GateHwi___S1
struct ti_sysbios_gates_GateMutex___S1
struct ti_sysbios_hal_Hwi___S1
struct ti_sysbios_heaps_HeapBuf___S1
struct ti_sysbios_heaps_HeapMem___S1
struct ti_sysbios_knl_Clock___S1
struct ti_sysbios_knl_Event___S1
struct ti_sysbios_knl_Queue___S1
struct ti_sysbios_knl_Semaphore___S1
struct ti_sysbios_knl_Task___S1
struct ti_sysbios_timers_rti_Timer___S1
struct xdc_runtime_LoggerBuf___S1
Macros
#define __nested__
#define __config__
#define ATTRIBUTE __attribute__ ((used))
#define IMM_FLAG_REG 0xFFF7AC18
#define IMM_WORD1_REG 0xFFF7AC84
#define IMM_REG_RW32(X) (*(volatile UInt32*)(X))
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapBuf_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapBuf_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapBuf_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapBuf_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapBuf_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapBuf_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapBuf_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapBuf_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapBuf_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapBuf_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Event_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
#define Module__MID ti_sysbios_knl_Task_Module__id__C
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
#define Module__MID xdc_runtime_LoggerBuf_Module__id__C
#define Module__DGSINCL xdc_runtime_LoggerBuf_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_LoggerBuf_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_LoggerBuf_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_LoggerBuf_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_LoggerBuf_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_LoggerBuf_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_LoggerBuf_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_LoggerBuf_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_LoggerBuf_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_LoggerBuf_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_LoggerBuf_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_LoggerBuf_Module__gatePrms__C
#define Module__GP_create xdc_runtime_LoggerBuf_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_LoggerBuf_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_LoggerBuf_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_LoggerBuf_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_LoggerBuf_Module_GateProxy_query
#define Module__MID xdc_runtime_LoggerBuf_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_LoggerBuf_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_LoggerBuf_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Typedefs
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
typedef struct ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__
typedef struct ti_sysbios_heaps_HeapBuf_Object__ ti_sysbios_heaps_HeapBuf_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
typedef struct xdc_runtime_LoggerBuf_Module__ xdc_runtime_LoggerBuf_Module__
typedef struct xdc_runtime_LoggerBuf_Object__ xdc_runtime_LoggerBuf_Object__
typedef struct xdc_runtime_LoggerBuf_Module_GateProxy_Module__ xdc_runtime_LoggerBuf_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_LoggerBuf_Module_GateProxy_Object__
typedef struct xdc_runtime_Main_Module__ xdc_runtime_Main_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_family_arm_a15_TimestampProvider_Module_State__ ti_sysbios_family_arm_a15_TimestampProvider_Module_State__
typedef struct ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module_State__
typedef struct ti_sysbios_family_arm_v7a_Pmu_Module_State__ ti_sysbios_family_arm_v7a_Pmu_Module_State__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
typedef struct ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module_State__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
typedef struct ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_LoggerBuf_Module_State__ xdc_runtime_LoggerBuf_Module_State__
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
typedef union Header Header
Functions
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
xdc_Void MmwDemo_sleep (xdc_Void)
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
xdc_Void ti_sysbios_utils_Load_taskRegHook__E (xdc_Int)
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
xdc_Int xdc_runtime_LoggerBuf_Module_startup__E (xdc_Int)
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_heaps_HeapBuf_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_exc_Exception_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_v7a_Pmu_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
xdc_Int ti_sysbios_family_arm_a15_TimestampProvider_Module_startup__E (xdc_Int)
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char **, xdc_CString *, xdc_VaList *, xdc_runtime_System_ParseData *)
xdc__META (__ASM__,"@(#)__ASM__ = /home/gtbldadm/nightlybuilds/mmwave_sdk/ti/demo/xwr64xx/mmw/mmw_configPkg_xwr64xx/package/cfg/mmw_per4ft")
xdc__META (__ISA__,"@(#)__ISA__ = v7R")
xdc__META (__PLAT__,"@(#)__PLAT__ = ti.platforms.cortexR")
xdc__META (__TARG__,"@(#)__TARG__ = ti.targets.arm.elf.R4Ft")
xdc__META (__TRDR__,"@(#)__TRDR__ = ti.targets.omf.elf.Elf32")
xdc_Bool xdc_runtime_LoggerBuf_Module__startupDone__F (void)
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__F (void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
xdc_Bool ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F (void)
xdc_Void xdc_runtime_Startup_exec__I (void)
xdc_Void xdc_runtime_Startup_reset__I (void)
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
Void ti_sysbios_BIOS_atExitFunc__I (Int)
Void ti_sysbios_BIOS_registerRTSLock ()
Void ti_sysbios_timers_rti_Timer_startup__E ()
Void ti_sysbios_BIOS_startFunc__I ()
Void ti_sysbios_BIOS_rtsLock ()
Void ti_sysbios_BIOS_rtsUnlock ()
Void ti_sysbios_BIOS_nullFunc__I ()
Void ti_sysbios_BIOS_registerRTSLock (Void)
Void ti_sysbios_BIOS_removeRTSLock (Void)
Void ti_sysbios_BIOS_exitFunc (Int stat)
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block *eb)
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Void _c_int00 ()
Void ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I ()
Void ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I ()
Void ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I ()
Void ti_sysbios_utils_Load_update__E ()
static Void * ti_sysbios_rts_MemAlloc_alloc (SizeT size)
Void ATTRIBUTE * malloc (SizeT size)
Void ATTRIBUTE * memalign (SizeT alignment, SizeT size)
Void ATTRIBUTE * calloc (SizeT nmemb, SizeT size)
Void ATTRIBUTE free (Void *ptr)
Void ATTRIBUTE * realloc (Void *ptr, SizeT size)
Void ti_sysbios_family_arm_v7r_tms570_Core_resetC__I ()
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt,...)
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt,...)
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt,...)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle *instp)
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_enable__E (xdc_Bits16 type)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_disable__E (xdc_Bits16 type)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_inv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wb__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbAll__E (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInvAll__E (void)
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wait__E (void)
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_getId__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_interruptCore__E (xdc_UInt coreId)
xdc_IArg ti_sysbios_hal_Core_CoreProxy_lock__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_unlock__E (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiDisable__E (void)
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiEnable__E (void)
xdc_Void ti_sysbios_hal_Core_CoreProxy_hwiRestore__E (xdc_UInt key)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle *instp)
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo *stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
xdc_Char * ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle *instp)
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params *prms, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle *instp)
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz *freq)
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg *arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block *eb)
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr *oldtskContext, xdc_Ptr *newtskContext)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char *stack, xdc_SizeT size)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char *stack, xdc_SizeT size)
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_LoggerBuf_Module_GateProxy_Handle xdc_runtime_LoggerBuf_Module_GateProxy_create (const xdc_runtime_LoggerBuf_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_LoggerBuf_Module_GateProxy_delete (xdc_runtime_LoggerBuf_Module_GateProxy_Handle *instp)
void xdc_runtime_LoggerBuf_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_LoggerBuf_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_LoggerBuf_Module_GateProxy_enter__E (xdc_runtime_LoggerBuf_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_LoggerBuf_Module_GateProxy_leave__E (xdc_runtime_LoggerBuf_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_LoggerBuf_TimestampProxy_Module__startupDone__S (void)
xdc_Bits32 xdc_runtime_LoggerBuf_TimestampProxy_get32__E (void)
xdc_Void xdc_runtime_LoggerBuf_TimestampProxy_get64__E (xdc_runtime_Types_Timestamp64 *result)
xdc_Void xdc_runtime_LoggerBuf_TimestampProxy_getFreq__E (xdc_runtime_Types_FreqHz *freq)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle *instp)
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle *instp)
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block *eb)
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats *stats)
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle *instp)
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_runtime_Types_Label * xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S (void)
xdc_Bits32 xdc_runtime_Timestamp_SupportProxy_get32__E (void)
xdc_Void xdc_runtime_Timestamp_SupportProxy_get64__E (xdc_runtime_Types_Timestamp64 *result)
xdc_Void xdc_runtime_Timestamp_SupportProxy_getFreq__E (xdc_runtime_Types_FreqHz *freq)
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle *instp)
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle *instp)
xdc_runtime_IFilterLogger_Handle xdc_runtime_IFilterLogger_create (xdc_runtime_IFilterLogger_Module mod, const xdc_runtime_IFilterLogger_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_IFilterLogger_delete (xdc_runtime_IFilterLogger_Handle *instp)
xdc_runtime_ILogger_Handle xdc_runtime_ILogger_create (xdc_runtime_ILogger_Module mod, const xdc_runtime_ILogger_Params *prms, xdc_runtime_Error_Block *eb)
void xdc_runtime_ILogger_delete (xdc_runtime_ILogger_Handle *instp)
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_TaskSupport_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S (void)
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_family_arm_v7r_vim_Hwi_Handle ti_sysbios_family_arm_v7r_vim_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_arm_v7r_vim_Hwi_construct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_family_arm_v7r_vim_Hwi_destruct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct *obj)
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_family_arm_v7r_vim_Hwi_delete (ti_sysbios_family_arm_v7r_vim_Hwi_Handle *instp)
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct *__obj, const ti_sysbios_gates_GateHwi_Params *__paramsPtr)
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct *obj)
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle *instp)
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct *__obj, const ti_sysbios_gates_GateMutex_Params *__paramsPtr)
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct *obj)
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle *instp)
xdc_Bool ti_sysbios_hal_Cache_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_CacheNull_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_hal_Core_Module__startupDone__S (void)
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Core_CoreProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct *__obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct *obj)
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle *instp)
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_heaps_HeapBuf_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__first__S (void)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_heaps_HeapBuf_Handle ti_sysbios_heaps_HeapBuf_create (const ti_sysbios_heaps_HeapBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapBuf_construct (ti_sysbios_heaps_HeapBuf_Struct *__obj, const ti_sysbios_heaps_HeapBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapBuf_destruct (ti_sysbios_heaps_HeapBuf_Struct *obj)
xdc_Void ti_sysbios_heaps_HeapBuf_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_heaps_HeapBuf_delete (ti_sysbios_heaps_HeapBuf_Handle *instp)
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct *__obj, const ti_sysbios_heaps_HeapMem_Params *__paramsPtr)
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct *obj)
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle *instp)
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct *__obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params *__paramsPtr)
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct *obj)
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle *instp)
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct *__obj, const ti_sysbios_knl_Event_Params *__paramsPtr)
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct *obj)
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle *instp)
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct *__obj, const ti_sysbios_knl_Queue_Params *__paramsPtr)
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct *obj)
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle *instp)
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct *__obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params *__paramsPtr)
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct *obj)
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct *__obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct *obj)
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle *instp)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
xdc_runtime_Types_Label * ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct *__obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct *obj)
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle *instp)
xdc_Bool ti_sysbios_utils_Load_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
xdc_Bool xdc_runtime_LoggerBuf_Module__startupDone__S (void)
xdc_runtime_Types_Label * xdc_runtime_LoggerBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label *lab)
xdc_Void xdc_runtime_LoggerBuf_Params__init__S (xdc_Ptr prms, const void *src, xdc_SizeT psz, xdc_SizeT isz)
xdc_Ptr xdc_runtime_LoggerBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
xdc_Ptr xdc_runtime_LoggerBuf_Object__first__S (void)
xdc_Ptr xdc_runtime_LoggerBuf_Object__next__S (xdc_Ptr obj)
xdc_Ptr xdc_runtime_LoggerBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar *__paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block *eb)
xdc_runtime_LoggerBuf_Handle xdc_runtime_LoggerBuf_create (const xdc_runtime_LoggerBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void xdc_runtime_LoggerBuf_construct (xdc_runtime_LoggerBuf_Struct *__obj, const xdc_runtime_LoggerBuf_Params *__paramsPtr, xdc_runtime_Error_Block *eb)
void xdc_runtime_LoggerBuf_destruct (xdc_runtime_LoggerBuf_Struct *obj)
xdc_Void xdc_runtime_LoggerBuf_Object__delete__S (xdc_Ptr instp)
void xdc_runtime_LoggerBuf_delete (xdc_runtime_LoggerBuf_Handle *instp)
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_LoggerBuf_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_LoggerBuf_TimestampProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_LoggerBuf_TimestampProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Timestamp_Module__startupDone__S (void)
xdc_Bool xdc_runtime_TimestampNull_Module__startupDone__S (void)
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Proxy__abstract__S (void)
xdc_CPtr xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S (void)
int __xdc__init (void)
Variables
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__root__V
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
xdc_runtime_LoggerBuf_Module__ xdc_runtime_LoggerBuf_Module__root__V
xdc_runtime_LoggerBuf_Module_GateProxy_Module__ xdc_runtime_LoggerBuf_Module_GateProxy_Module__root__V
xdc_runtime_Main_Module__ xdc_runtime_Main_Module__root__V
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base ti_sysbios_interfaces_ICache_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ITimestampProvider_Interface__BASE__C = {&xdc_runtime_ITimestampClient_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IFilterLogger_Interface__BASE__C = {&xdc_runtime_ILogger_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ILogger_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ITimestampClient_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
const ti_sysbios_hal_CacheNull_Fxns__ ti_sysbios_hal_CacheNull_Module__FXNS__C
const ti_sysbios_heaps_HeapBuf_Fxns__ ti_sysbios_heaps_HeapBuf_Module__FXNS__C
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
const xdc_runtime_LoggerBuf_Fxns__ xdc_runtime_LoggerBuf_Module__FXNS__C
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
const xdc_runtime_Timestamp_Fxns__ xdc_runtime_Timestamp_Module__FXNS__C
const xdc_runtime_TimestampNull_Fxns__ xdc_runtime_TimestampNull_Module__FXNS__C
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
ti_sysbios_family_arm_a15_TimestampProvider_Module_State__ ti_sysbios_family_arm_a15_TimestampProvider_Module__state__V
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excActive ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excContext ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStackBuffers ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A [1]
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A [4096]
__T2_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A [1]
ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module__state__V
const __T1_ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__A [1]
ti_sysbios_family_arm_v7a_Pmu_Module_State__ ti_sysbios_family_arm_v7a_Pmu_Module__state__V
ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V [1]
void * __TI_STACK_BASE
void * __TI_STACK_SIZE
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A [2048]
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A [128]
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__state__V
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A [128]
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A [4]
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A [4]
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V [1]
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V [2]
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V [1]
ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module__state__V
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A [65536]
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V [1]
ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__table__V [1]
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A [3]
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A [3]
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A [800]
__T1_ti_sysbios_knl_Task_Instance_State__hookEnv ti_sysbios_knl_Task_Instance_State_0_hookEnv__A [1]
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V [1]
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A [16]
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A [1]
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
const __T1_ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__A [1]
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V [1]
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A [2]
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A [2]
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
__T1_ti_sysbios_utils_Load_Module_State__taskStartTime ti_sysbios_utils_Load_Module_State_0_taskStartTime__A [1]
__T1_ti_sysbios_utils_Load_Module_State__runningTask ti_sysbios_utils_Load_Module_State_0_runningTask__A [1]
__T1_ti_sysbios_utils_Load_Module_State__taskEnv ti_sysbios_utils_Load_Module_State_0_taskEnv__A [1]
ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module__state__V
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
__T1_xdc_runtime_LoggerBuf_Instance_State__entryArr xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A [200]
xdc_runtime_LoggerBuf_Object__ xdc_runtime_LoggerBuf_Object__table__V [1]
xdc_runtime_LoggerBuf_Module_State__ xdc_runtime_LoggerBuf_Module__state__V
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A [2]
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A [12]
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A [12]
__T1_xdc_runtime_System_Module_State__atexitHandlers xdc_runtime_System_Module_State_0_atexitHandlers__A [8]
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A [1]
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A [1]
__FAR__ const xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
__FAR__ const xdc_SizeT ti_sysbios_heaps_HeapBuf_Instance_State_freeList__O = offsetof(ti_sysbios_heaps_HeapBuf_Object__,Object_field_freeList)
__FAR__ const xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
__FAR__ const xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
__FAR__ const xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
__FAR__ const xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
__FAR__ const xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
__FAR__ const xdc_SizeT ti_sysbios_utils_Load_Module_State_taskList__O = offsetof(ti_sysbios_utils_Load_Module_State__,Object_field_taskList)
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
const UInt32 ti_sysbios_family_arm_v7r_vim_Hwi_vectors []
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x1b
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
__FAR__ const CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
__FAR__ const CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
__FAR__ const CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
__FAR__ const CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
__FAR__ const CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
__FAR__ const CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
__FAR__ const CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 0
__FAR__ const CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
__FAR__ const CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
__FAR__ const CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
__FAR__ const CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
__FAR__ const CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
__FAR__ const CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
__FAR__ const CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
__FAR__ const CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
__FAR__ const CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
__FAR__ const CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__id ti_sysbios_family_arm_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x19
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__count ti_sysbios_family_arm_IntrinsicsSupport_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__heap ti_sysbios_family_arm_IntrinsicsSupport_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__table ti_sysbios_family_arm_IntrinsicsSupport_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask ti_sysbios_family_arm_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj ti_sysbios_family_arm_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms ti_sysbios_family_arm_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__id ti_sysbios_family_arm_TaskSupport_Module__id__C = (xdc_Bits16)0x1a
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerDefined ti_sysbios_family_arm_TaskSupport_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj ti_sysbios_family_arm_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__count ti_sysbios_family_arm_TaskSupport_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__heap ti_sysbios_family_arm_TaskSupport_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__sizeof ti_sysbios_family_arm_TaskSupport_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__table ti_sysbios_family_arm_TaskSupport_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_defaultStackSize ti_sysbios_family_arm_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_stackAlignment ti_sysbios_family_arm_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsEnabled ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsIncluded ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__id ti_sysbios_family_arm_a15_TimestampProvider_Module__id__C = (xdc_Bits16)0x39
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerDefined ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__count ti_sysbios_family_arm_a15_TimestampProvider_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__heap ti_sysbios_family_arm_a15_TimestampProvider_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__sizeof ti_sysbios_family_arm_a15_TimestampProvider_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__table ti_sysbios_family_arm_a15_TimestampProvider_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask ti_sysbios_family_arm_exc_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj ti_sysbios_family_arm_exc_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms ti_sysbios_family_arm_exc_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__id ti_sysbios_family_arm_exc_Exception_Module__id__C = (xdc_Bits16)0x2b
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerDefined ti_sysbios_family_arm_exc_Exception_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj ti_sysbios_family_arm_exc_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__count ti_sysbios_family_arm_exc_Exception_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__heap ti_sysbios_family_arm_exc_Exception_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__sizeof ti_sysbios_family_arm_exc_Exception_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__table ti_sysbios_family_arm_exc_Exception_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_swi ti_sysbios_family_arm_exc_Exception_E_swi__C = (((xdc_runtime_Error_Id)24) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_prefetchAbort ti_sysbios_family_arm_exc_Exception_E_prefetchAbort__C = (((xdc_runtime_Error_Id)25) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_dataAbort ti_sysbios_family_arm_exc_Exception_E_dataAbort__C = (((xdc_runtime_Error_Id)26) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction__C = (((xdc_runtime_Error_Id)27) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_enableDecode ti_sysbios_family_arm_exc_Exception_enableDecode__C = 1
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_excHookFunc ti_sysbios_family_arm_exc_Exception_excHookFunc__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFunc)0)
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs)ti_sysbios_family_arm_exc_Exception_excHookFuncs__A)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__gateObj ti_sysbios_family_arm_v7a_Pmu_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__id ti_sysbios_family_arm_v7a_Pmu_Module__id__C = (xdc_Bits16)0x33
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__count ti_sysbios_family_arm_v7a_Pmu_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__heap ti_sysbios_family_arm_v7a_Pmu_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__sizeof ti_sysbios_family_arm_v7a_Pmu_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__table ti_sysbios_family_arm_v7a_Pmu_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_intNum ti_sysbios_family_arm_v7a_Pmu_intNum__C = (xdc_UInt)(-0x0 - 1)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_A_badIntNum ti_sysbios_family_arm_v7a_Pmu_A_badIntNum__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_A_invalidCounterId ti_sysbios_family_arm_v7a_Pmu_A_invalidCounterId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__id ti_sysbios_family_arm_v7r_tms570_Core_Module__id__C = (xdc_Bits16)0x37
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__count ti_sysbios_family_arm_v7r_tms570_Core_Object__count__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__heap ti_sysbios_family_arm_v7r_tms570_Core_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__table ti_sysbios_family_arm_v7r_tms570_Core_Object__table__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_numCores ti_sysbios_family_arm_v7r_tms570_Core_numCores__C = (xdc_UInt)0x1
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds__C = (((xdc_runtime_Error_Id)33) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_id ti_sysbios_family_arm_v7r_tms570_Core_id__C = (xdc_UInt)0x0
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C
__FAR__ const ti_sysbios_family_arm_v7r_vim_Hwi_Params ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__id ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C = (xdc_Bits16)0x2a
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__count ti_sysbios_family_arm_v7r_vim_Hwi_Object__count__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object__)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__table ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C = ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport__C = 0
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS__C = (xdc_UInt)0x80
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress)(0x0))
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress)(0x0))
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc)((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_phantomIntHandler__I))
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM__C = 1
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)19) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum__C = (((xdc_runtime_Error_Id)20) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined__C = (((xdc_runtime_Error_Id)21) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption__C = (((xdc_runtime_Error_Id)22) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt__C = (((xdc_runtime_Error_Id)23) << 16 | 0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)29) << 16 | 768)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_LD_end ti_sysbios_family_arm_v7r_vim_Hwi_LD_end__C = (((xdc_runtime_Log_Event)30) << 16 | 512)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap)ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi)0)
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_hooks ti_sysbios_family_arm_v7r_vim_Hwi_hooks__C = {0, 0}
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
__FAR__ const ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x35
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
__FAR__ const ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x36
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
__FAR__ const CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsEnabled ti_sysbios_hal_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsIncluded ti_sysbios_hal_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsMask ti_sysbios_hal_Cache_Module__diagsMask__C = ((CT__ti_sysbios_hal_Cache_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__gateObj ti_sysbios_hal_Cache_Module__gateObj__C = ((CT__ti_sysbios_hal_Cache_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__gatePrms ti_sysbios_hal_Cache_Module__gatePrms__C = ((CT__ti_sysbios_hal_Cache_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__id ti_sysbios_hal_Cache_Module__id__C = (xdc_Bits16)0x2c
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerDefined ti_sysbios_hal_Cache_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerObj ti_sysbios_hal_Cache_Module__loggerObj__C = ((CT__ti_sysbios_hal_Cache_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn0 ti_sysbios_hal_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn1 ti_sysbios_hal_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn2 ti_sysbios_hal_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn4 ti_sysbios_hal_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn8 ti_sysbios_hal_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_hal_Cache_Object__count ti_sysbios_hal_Cache_Object__count__C = 0
__FAR__ const CT__ti_sysbios_hal_Cache_Object__heap ti_sysbios_hal_Cache_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_hal_Cache_Object__sizeof ti_sysbios_hal_Cache_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_hal_Cache_Object__table ti_sysbios_hal_Cache_Object__table__C = 0
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsEnabled ti_sysbios_hal_CacheNull_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsIncluded ti_sysbios_hal_CacheNull_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsMask ti_sysbios_hal_CacheNull_Module__diagsMask__C = ((CT__ti_sysbios_hal_CacheNull_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__gateObj ti_sysbios_hal_CacheNull_Module__gateObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__gatePrms ti_sysbios_hal_CacheNull_Module__gatePrms__C = ((CT__ti_sysbios_hal_CacheNull_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__id ti_sysbios_hal_CacheNull_Module__id__C = (xdc_Bits16)0x2d
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerDefined ti_sysbios_hal_CacheNull_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerObj ti_sysbios_hal_CacheNull_Module__loggerObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0 ti_sysbios_hal_CacheNull_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1 ti_sysbios_hal_CacheNull_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2 ti_sysbios_hal_CacheNull_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4 ti_sysbios_hal_CacheNull_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8 ti_sysbios_hal_CacheNull_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__count ti_sysbios_hal_CacheNull_Object__count__C = 0
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__heap ti_sysbios_hal_CacheNull_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__sizeof ti_sysbios_hal_CacheNull_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__table ti_sysbios_hal_CacheNull_Object__table__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsEnabled ti_sysbios_hal_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsIncluded ti_sysbios_hal_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsMask ti_sysbios_hal_Core_Module__diagsMask__C = ((CT__ti_sysbios_hal_Core_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__gateObj ti_sysbios_hal_Core_Module__gateObj__C = ((CT__ti_sysbios_hal_Core_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__gatePrms ti_sysbios_hal_Core_Module__gatePrms__C = ((CT__ti_sysbios_hal_Core_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__id ti_sysbios_hal_Core_Module__id__C = (xdc_Bits16)0x2e
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerDefined ti_sysbios_hal_Core_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerObj ti_sysbios_hal_Core_Module__loggerObj__C = ((CT__ti_sysbios_hal_Core_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn0 ti_sysbios_hal_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn1 ti_sysbios_hal_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn2 ti_sysbios_hal_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn4 ti_sysbios_hal_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn8 ti_sysbios_hal_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_hal_Core_Object__count ti_sysbios_hal_Core_Object__count__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_Object__heap ti_sysbios_hal_Core_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_Object__sizeof ti_sysbios_hal_Core_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_Object__table ti_sysbios_hal_Core_Object__table__C = 0
__FAR__ const CT__ti_sysbios_hal_Core_numCores ti_sysbios_hal_Core_numCores__C = (xdc_UInt)0x1
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
__FAR__ const ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x2f
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 0
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
__FAR__ const CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)28) << 16 | 0)
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapBuf_Object__DESC__C
__FAR__ const ti_sysbios_heaps_HeapBuf_Params ti_sysbios_heaps_HeapBuf_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsEnabled ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsIncluded ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask ti_sysbios_heaps_HeapBuf_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__gateObj ti_sysbios_heaps_HeapBuf_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms ti_sysbios_heaps_HeapBuf_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__id ti_sysbios_heaps_HeapBuf_Module__id__C = (xdc_Bits16)0x27
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerDefined ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj ti_sysbios_heaps_HeapBuf_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__count ti_sysbios_heaps_HeapBuf_Object__count__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__heap ti_sysbios_heaps_HeapBuf_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__sizeof ti_sysbios_heaps_HeapBuf_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapBuf_Object__)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__table ti_sysbios_heaps_HeapBuf_Object__table__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_nullBuf ti_sysbios_heaps_HeapBuf_A_nullBuf__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_bufAlign ti_sysbios_heaps_HeapBuf_A_bufAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidAlign ti_sysbios_heaps_HeapBuf_A_invalidAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidBlockSize ti_sysbios_heaps_HeapBuf_A_invalidBlockSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_zeroBlocks ti_sysbios_heaps_HeapBuf_A_zeroBlocks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_zeroBufSize ti_sysbios_heaps_HeapBuf_A_zeroBufSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidBufSize ti_sysbios_heaps_HeapBuf_A_invalidBufSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_noBlocksToFree ti_sysbios_heaps_HeapBuf_A_noBlocksToFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidFree ti_sysbios_heaps_HeapBuf_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_E_size ti_sysbios_heaps_HeapBuf_E_size__C = (((xdc_runtime_Error_Id)16) << 16 | 0)
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_trackMaxAllocs ti_sysbios_heaps_HeapBuf_trackMaxAllocs__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_numConstructedHeaps ti_sysbios_heaps_HeapBuf_numConstructedHeaps__C = (xdc_UInt)0x0
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
__FAR__ const ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x28
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)17) << 16 | 0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
__FAR__ const CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
__FAR__ const ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x1d
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 1
__FAR__ const CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
__FAR__ const CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = ti_sysbios_knl_Clock_Object__table__V
__FAR__ const CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)12) << 16 | 1024)
__FAR__ const CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)13) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)14) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
__FAR__ const CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
__FAR__ const CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
__FAR__ const CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
__FAR__ const CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
__FAR__ const CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
__FAR__ const CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
__FAR__ const ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x20
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
__FAR__ const CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
__FAR__ const CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
__FAR__ const CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)15) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)16) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x1e
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
__FAR__ const CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
__FAR__ const CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {3, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
__FAR__ const CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {3, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x1f
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
__FAR__ const ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x21
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
__FAR__ const CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
__FAR__ const CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
__FAR__ const ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x22
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
__FAR__ const CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)17) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)18) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)9) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
__FAR__ const CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
__FAR__ const CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
__FAR__ const CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
__FAR__ const ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x190
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)((void*)&ti_sysbios_knl_Task_Module__root__V.mask))
__FAR__ const CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x23
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
__FAR__ const CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
__FAR__ const CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
__FAR__ const CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)19) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)20) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)21) << 16 | 512)
__FAR__ const CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)22) << 16 | 512)
__FAR__ const CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)23) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)24) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)25) << 16 | 512)
__FAR__ const CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)26) << 16 | 768)
__FAR__ const CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)27) << 16 | 1024)
__FAR__ const CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)28) << 16 | 1024)
__FAR__ const CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)10) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)11) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)12) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)13) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)14) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)15) << 16 | 0)
__FAR__ const CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
__FAR__ const CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x800
__FAR__ const CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
__FAR__ const CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
__FAR__ const CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
__FAR__ const CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {1, ((__T1_ti_sysbios_knl_Task_hooks *)ti_sysbios_knl_Task_hooks__A)}
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
__FAR__ const CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
__FAR__ const CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
__FAR__ const ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x38
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
__FAR__ const CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)34) << 16 | 0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)35) << 16 | 0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)36) << 16 | 0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)37) << 16 | 0)
__FAR__ const CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
__FAR__ const CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
__FAR__ const CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
__FAR__ const CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsEnabled ti_sysbios_utils_Load_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsIncluded ti_sysbios_utils_Load_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsMask ti_sysbios_utils_Load_Module__diagsMask__C = ((CT__ti_sysbios_utils_Load_Module__diagsMask)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__gateObj ti_sysbios_utils_Load_Module__gateObj__C = ((CT__ti_sysbios_utils_Load_Module__gateObj)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__gatePrms ti_sysbios_utils_Load_Module__gatePrms__C = ((CT__ti_sysbios_utils_Load_Module__gatePrms)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__id ti_sysbios_utils_Load_Module__id__C = (xdc_Bits16)0x34
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerDefined ti_sysbios_utils_Load_Module__loggerDefined__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerObj ti_sysbios_utils_Load_Module__loggerObj__C = ((CT__ti_sysbios_utils_Load_Module__loggerObj)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn0 ti_sysbios_utils_Load_Module__loggerFxn0__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn0)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn1 ti_sysbios_utils_Load_Module__loggerFxn1__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn1)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn2 ti_sysbios_utils_Load_Module__loggerFxn2__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn2)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn4 ti_sysbios_utils_Load_Module__loggerFxn4__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn4)0)
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn8 ti_sysbios_utils_Load_Module__loggerFxn8__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn8)0)
__FAR__ const CT__ti_sysbios_utils_Load_Object__count ti_sysbios_utils_Load_Object__count__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_Object__heap ti_sysbios_utils_Load_Object__heap__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_Object__sizeof ti_sysbios_utils_Load_Object__sizeof__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_Object__table ti_sysbios_utils_Load_Object__table__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_LS_cpuLoad ti_sysbios_utils_Load_LS_cpuLoad__C = (((xdc_runtime_Log_Event)31) << 16 | 2048)
__FAR__ const CT__ti_sysbios_utils_Load_LS_hwiLoad ti_sysbios_utils_Load_LS_hwiLoad__C = (((xdc_runtime_Log_Event)32) << 16 | 2048)
__FAR__ const CT__ti_sysbios_utils_Load_LS_swiLoad ti_sysbios_utils_Load_LS_swiLoad__C = (((xdc_runtime_Log_Event)33) << 16 | 2048)
__FAR__ const CT__ti_sysbios_utils_Load_LS_taskLoad ti_sysbios_utils_Load_LS_taskLoad__C = (((xdc_runtime_Log_Event)34) << 16 | 2048)
__FAR__ const CT__ti_sysbios_utils_Load_postUpdate ti_sysbios_utils_Load_postUpdate__C = ((CT__ti_sysbios_utils_Load_postUpdate)0)
__FAR__ const CT__ti_sysbios_utils_Load_updateInIdle ti_sysbios_utils_Load_updateInIdle__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_windowInMs ti_sysbios_utils_Load_windowInMs__C = (xdc_UInt)0x1f4
__FAR__ const CT__ti_sysbios_utils_Load_hwiEnabled ti_sysbios_utils_Load_hwiEnabled__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_swiEnabled ti_sysbios_utils_Load_swiEnabled__C = 0
__FAR__ const CT__ti_sysbios_utils_Load_taskEnabled ti_sysbios_utils_Load_taskEnabled__C = 1
__FAR__ const CT__ti_sysbios_utils_Load_autoAddTasks ti_sysbios_utils_Load_autoAddTasks__C = 1
__FAR__ const CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x1
__FAR__ const CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)1) << 16 | 0)
__FAR__ const CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x2
__FAR__ const CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x3
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x4
__FAR__ const CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
__FAR__ const CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
__FAR__ const CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x5
__FAR__ const CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
__FAR__ const CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)2) << 16 | 0)
__FAR__ const CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3) << 16 | 0)
__FAR__ const CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)4) << 16 | 0)
__FAR__ const CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
__FAR__ const CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
__FAR__ const CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
__FAR__ const CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x6
__FAR__ const CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x7
__FAR__ const CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)1) << 16 | 4)
__FAR__ const CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)2) << 16 | 4)
__FAR__ const CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)3) << 16 | 4)
__FAR__ const CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)4) << 16 | 4)
__FAR__ const CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5) << 16 | 192)
__FAR__ const CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)6) << 16 | 224)
__FAR__ const CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)7) << 16 | 16384)
__FAR__ const CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)8) << 16 | 32768)
__FAR__ const CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)9) << 16 | 32768)
__FAR__ const CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)10) << 16 | 32768)
__FAR__ const CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)11) << 16 | 32768)
__FAR__ const xdc_runtime_Core_ObjDesc xdc_runtime_LoggerBuf_Object__DESC__C
__FAR__ const xdc_runtime_LoggerBuf_Params xdc_runtime_LoggerBuf_Object__PARAMS__C
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsEnabled xdc_runtime_LoggerBuf_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsIncluded xdc_runtime_LoggerBuf_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsMask xdc_runtime_LoggerBuf_Module__diagsMask__C = ((CT__xdc_runtime_LoggerBuf_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__gateObj xdc_runtime_LoggerBuf_Module__gateObj__C = ((CT__xdc_runtime_LoggerBuf_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__gatePrms xdc_runtime_LoggerBuf_Module__gatePrms__C = ((CT__xdc_runtime_LoggerBuf_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__id xdc_runtime_LoggerBuf_Module__id__C = (xdc_Bits16)0x8
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerDefined xdc_runtime_LoggerBuf_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerObj xdc_runtime_LoggerBuf_Module__loggerObj__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn0 xdc_runtime_LoggerBuf_Module__loggerFxn0__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn1 xdc_runtime_LoggerBuf_Module__loggerFxn1__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn2 xdc_runtime_LoggerBuf_Module__loggerFxn2__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn4 xdc_runtime_LoggerBuf_Module__loggerFxn4__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn8 xdc_runtime_LoggerBuf_Module__loggerFxn8__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__count xdc_runtime_LoggerBuf_Object__count__C = 1
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__heap xdc_runtime_LoggerBuf_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__sizeof xdc_runtime_LoggerBuf_Object__sizeof__C = sizeof(xdc_runtime_LoggerBuf_Object__)
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__table xdc_runtime_LoggerBuf_Object__table__C = xdc_runtime_LoggerBuf_Object__table__V
__FAR__ const CT__xdc_runtime_LoggerBuf_filterByLevel xdc_runtime_LoggerBuf_filterByLevel__C = 0
__FAR__ const CT__xdc_runtime_LoggerBuf_E_badLevel xdc_runtime_LoggerBuf_E_badLevel__C = (((xdc_runtime_Error_Id)5) << 16 | 0)
__FAR__ const CT__xdc_runtime_LoggerBuf_enableFlush xdc_runtime_LoggerBuf_enableFlush__C = 0
__FAR__ const CT__xdc_runtime_LoggerBuf_statusLogger xdc_runtime_LoggerBuf_statusLogger__C = 0
__FAR__ const CT__xdc_runtime_LoggerBuf_level1Mask xdc_runtime_LoggerBuf_level1Mask__C = (xdc_Bits16)0x0
__FAR__ const CT__xdc_runtime_LoggerBuf_level2Mask xdc_runtime_LoggerBuf_level2Mask__C = (xdc_Bits16)0x0
__FAR__ const CT__xdc_runtime_LoggerBuf_level3Mask xdc_runtime_LoggerBuf_level3Mask__C = (xdc_Bits16)0x0
__FAR__ const CT__xdc_runtime_LoggerBuf_level4Mask xdc_runtime_LoggerBuf_level4Mask__C = (xdc_Bits16)0xff87
__FAR__ const CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x190
__FAR__ const CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)((void*)&xdc_runtime_Main_Module__root__V.mask))
__FAR__ const CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
__FAR__ const CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x9
__FAR__ const CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 1
__FAR__ const CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)((const void*)(xdc_runtime_ILogger_Handle)&xdc_runtime_LoggerBuf_Object__table__V[0]))
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)((xdc_Fxn)xdc_runtime_LoggerBuf_write0))
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)((xdc_Fxn)xdc_runtime_LoggerBuf_write1))
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)((xdc_Fxn)xdc_runtime_LoggerBuf_write2))
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)((xdc_Fxn)xdc_runtime_LoggerBuf_write4))
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)((xdc_Fxn)xdc_runtime_LoggerBuf_write8))
__FAR__ const CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0xa
__FAR__ const CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
__FAR__ const CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
__FAR__ const CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0xb
__FAR__ const CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0xc
__FAR__ const CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
__FAR__ const CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
__FAR__ const CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
__FAR__ const CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
__FAR__ const CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
__FAR__ const CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
__FAR__ const CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0xe
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
__FAR__ const CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
__FAR__ const CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
__FAR__ const CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0xd
__FAR__ const CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
__FAR__ const CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
__FAR__ const CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
__FAR__ const CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x8
__FAR__ const CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
__FAR__ const CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
__FAR__ const CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
__FAR__ const CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0xf
__FAR__ const CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
__FAR__ const CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
__FAR__ const CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
__FAR__ const CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
__FAR__ const CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 0
__FAR__ const CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
__FAR__ const CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
__FAR__ const CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1
__FAR__ const CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x1
__FAR__ const CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
__FAR__ const CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
__FAR__ const CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
__FAR__ const CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsEnabled xdc_runtime_Timestamp_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsIncluded xdc_runtime_Timestamp_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsMask xdc_runtime_Timestamp_Module__diagsMask__C = ((CT__xdc_runtime_Timestamp_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__gateObj xdc_runtime_Timestamp_Module__gateObj__C = ((CT__xdc_runtime_Timestamp_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__gatePrms xdc_runtime_Timestamp_Module__gatePrms__C = ((CT__xdc_runtime_Timestamp_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__id xdc_runtime_Timestamp_Module__id__C = (xdc_Bits16)0x10
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerDefined xdc_runtime_Timestamp_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerObj xdc_runtime_Timestamp_Module__loggerObj__C = ((CT__xdc_runtime_Timestamp_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn0 xdc_runtime_Timestamp_Module__loggerFxn0__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn1 xdc_runtime_Timestamp_Module__loggerFxn1__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn2 xdc_runtime_Timestamp_Module__loggerFxn2__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn4 xdc_runtime_Timestamp_Module__loggerFxn4__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn8 xdc_runtime_Timestamp_Module__loggerFxn8__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_Timestamp_Object__count xdc_runtime_Timestamp_Object__count__C = 0
__FAR__ const CT__xdc_runtime_Timestamp_Object__heap xdc_runtime_Timestamp_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_Timestamp_Object__sizeof xdc_runtime_Timestamp_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_Timestamp_Object__table xdc_runtime_Timestamp_Object__table__C = 0
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsEnabled xdc_runtime_TimestampNull_Module__diagsEnabled__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsIncluded xdc_runtime_TimestampNull_Module__diagsIncluded__C = (xdc_Bits32)0x10
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsMask xdc_runtime_TimestampNull_Module__diagsMask__C = ((CT__xdc_runtime_TimestampNull_Module__diagsMask)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__gateObj xdc_runtime_TimestampNull_Module__gateObj__C = ((CT__xdc_runtime_TimestampNull_Module__gateObj)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__gatePrms xdc_runtime_TimestampNull_Module__gatePrms__C = ((CT__xdc_runtime_TimestampNull_Module__gatePrms)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__id xdc_runtime_TimestampNull_Module__id__C = (xdc_Bits16)0x11
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerDefined xdc_runtime_TimestampNull_Module__loggerDefined__C = 0
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerObj xdc_runtime_TimestampNull_Module__loggerObj__C = ((CT__xdc_runtime_TimestampNull_Module__loggerObj)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn0 xdc_runtime_TimestampNull_Module__loggerFxn0__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn0)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn1 xdc_runtime_TimestampNull_Module__loggerFxn1__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn1)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn2 xdc_runtime_TimestampNull_Module__loggerFxn2__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn2)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn4 xdc_runtime_TimestampNull_Module__loggerFxn4__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn4)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn8 xdc_runtime_TimestampNull_Module__loggerFxn8__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn8)0)
__FAR__ const CT__xdc_runtime_TimestampNull_Object__count xdc_runtime_TimestampNull_Object__count__C = 0
__FAR__ const CT__xdc_runtime_TimestampNull_Object__heap xdc_runtime_TimestampNull_Object__heap__C = 0
__FAR__ const CT__xdc_runtime_TimestampNull_Object__sizeof xdc_runtime_TimestampNull_Object__sizeof__C = 0
__FAR__ const CT__xdc_runtime_TimestampNull_Object__table xdc_runtime_TimestampNull_Object__table__C = 0
__FAR__ int(*volatile __xdc__init__addr)(void) = &__xdc__init
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Macro Definition Documentation
#define __config__
Definition at line 9 of file mmw_per4ft.c.
#define __nested__
Definition at line 8 of file mmw_per4ft.c.
#define ATTRIBUTE __attribute__ ((used))
Definition at line 2560 of file mmw_per4ft.c.
Referenced by realloc().
#define IMM_FLAG_REG 0xFFF7AC18
Definition at line 2781 of file mmw_per4ft.c.
#define IMM_REG_RW32 (X) (*(volatile UInt32*)(X))
Definition at line 2783 of file mmw_per4ft.c.
#define IMM_WORD1_REG 0xFFF7AC84
Definition at line 2782 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_BIOS_RtsGateProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_gates_GateHwi_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_gates_GateMutex_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_hal_Hwi_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_hal_Hwi_HwiProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Clock_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Clock_TimerProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Event_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Queue_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Semaphore_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_knl_Task_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB xdc_runtime_LoggerBuf_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB xdc_runtime_Main_Module_GateProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB xdc_runtime_Memory_HeapProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSENAB xdc_runtime_System_Module_GateProxy_Module__diagsEnabled__C
Definition at line 14144 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_BIOS_RtsGateProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_gates_GateHwi_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_gates_GateMutex_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_hal_Hwi_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_hal_Hwi_HwiProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Clock_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Clock_TimerProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Event_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Queue_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Semaphore_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_knl_Task_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL xdc_runtime_LoggerBuf_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL xdc_runtime_Main_Module_GateProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL xdc_runtime_Memory_HeapProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSINCL xdc_runtime_System_Module_GateProxy_Module__diagsIncluded__C
Definition at line 14137 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_BIOS_RtsGateProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_gates_GateHwi_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_gates_GateMutex_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_hal_Hwi_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_hal_Hwi_HwiProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_heaps_HeapBuf_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Clock_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Clock_TimerProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Event_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Queue_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Semaphore_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_knl_Task_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK ti_sysbios_timers_rti_Timer_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK xdc_runtime_LoggerBuf_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK xdc_runtime_LoggerBuf_Module_GateProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK xdc_runtime_Main_Module_GateProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK xdc_runtime_Memory_HeapProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__DGSMASK xdc_runtime_System_Module_GateProxy_Module__diagsMask__C
Definition at line 14151 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_BIOS_RtsGateProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_gates_GateHwi_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_gates_GateMutex_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_hal_Hwi_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_hal_Hwi_HwiProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_heaps_HeapBuf_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Clock_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Clock_TimerProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Event_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Queue_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Semaphore_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_knl_Task_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ ti_sysbios_timers_rti_Timer_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ xdc_runtime_LoggerBuf_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ xdc_runtime_LoggerBuf_Module_GateProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ xdc_runtime_Main_Module_GateProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ xdc_runtime_Memory_HeapProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_OBJ xdc_runtime_System_Module_GateProxy_Module__gateObj__C
Definition at line 14208 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_BIOS_RtsGateProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_gates_GateHwi_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_gates_GateMutex_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_hal_Hwi_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_hal_Hwi_HwiProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_heaps_HeapBuf_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Clock_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Clock_TimerProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Event_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Queue_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Semaphore_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_knl_Task_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS ti_sysbios_timers_rti_Timer_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS xdc_runtime_LoggerBuf_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS xdc_runtime_LoggerBuf_Module_GateProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS xdc_runtime_Main_Module_GateProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS xdc_runtime_Memory_HeapProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__G_PRMS xdc_runtime_System_Module_GateProxy_Module__gatePrms__C
Definition at line 14215 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_gates_GateHwi_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_gates_GateMutex_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_hal_Hwi_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_heaps_HeapBuf_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Clock_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Event_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Queue_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Semaphore_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_knl_Task_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create ti_sysbios_timers_rti_Timer_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create xdc_runtime_LoggerBuf_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create xdc_runtime_Main_Module_GateProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create xdc_runtime_Memory_HeapProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_create xdc_runtime_System_Module_GateProxy_Module_GateProxy_create
Definition at line 14219 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_gates_GateHwi_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_gates_GateMutex_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_hal_Hwi_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_heaps_HeapBuf_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Clock_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Event_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Queue_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Semaphore_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_knl_Task_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete ti_sysbios_timers_rti_Timer_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete xdc_runtime_LoggerBuf_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete xdc_runtime_Main_Module_GateProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete xdc_runtime_Memory_HeapProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_delete xdc_runtime_System_Module_GateProxy_Module_GateProxy_delete
Definition at line 14221 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_gates_GateHwi_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_gates_GateMutex_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_hal_Hwi_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_heaps_HeapBuf_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Clock_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Event_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Queue_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Semaphore_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_knl_Task_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter ti_sysbios_timers_rti_Timer_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter xdc_runtime_LoggerBuf_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter xdc_runtime_Main_Module_GateProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter xdc_runtime_Memory_HeapProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_enter xdc_runtime_System_Module_GateProxy_Module_GateProxy_enter
Definition at line 14223 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_gates_GateHwi_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_gates_GateMutex_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_hal_Hwi_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_heaps_HeapBuf_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Clock_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Event_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Queue_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Semaphore_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_knl_Task_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave ti_sysbios_timers_rti_Timer_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave xdc_runtime_LoggerBuf_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave xdc_runtime_Main_Module_GateProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave xdc_runtime_Memory_HeapProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_leave xdc_runtime_System_Module_GateProxy_Module_GateProxy_leave
Definition at line 14225 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_BIOS_RtsGateProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_family_arm_v7r_vim_Hwi_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_gates_GateHwi_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_gates_GateMutex_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_hal_Hwi_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_hal_Hwi_HwiProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_heaps_HeapBuf_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_heaps_HeapMem_Module_GateProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Clock_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Clock_TimerProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Event_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Queue_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Semaphore_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_knl_Task_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query ti_sysbios_timers_rti_Timer_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query xdc_runtime_LoggerBuf_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query xdc_runtime_LoggerBuf_Module_GateProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query xdc_runtime_Main_Module_GateProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query xdc_runtime_Memory_HeapProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__GP_query xdc_runtime_System_Module_GateProxy_Module_GateProxy_query
Definition at line 14227 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_BIOS_RtsGateProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_gates_GateHwi_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_gates_GateMutex_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_hal_Hwi_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_hal_Hwi_HwiProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Clock_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Clock_TimerProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Event_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Queue_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Semaphore_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_knl_Task_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF ti_sysbios_timers_rti_Timer_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF xdc_runtime_LoggerBuf_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF xdc_runtime_Main_Module_GateProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF xdc_runtime_Memory_HeapProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGDEF xdc_runtime_System_Module_GateProxy_Module__loggerDefined__C
Definition at line 14158 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Clock_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Event_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Queue_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_knl_Task_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 xdc_runtime_LoggerBuf_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 xdc_runtime_Memory_HeapProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN0 xdc_runtime_System_Module_GateProxy_Module__loggerFxn0__C
Definition at line 14173 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Clock_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Event_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Queue_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_knl_Task_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 xdc_runtime_LoggerBuf_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 xdc_runtime_Memory_HeapProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN1 xdc_runtime_System_Module_GateProxy_Module__loggerFxn1__C
Definition at line 14180 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Clock_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Event_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Queue_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_knl_Task_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 xdc_runtime_LoggerBuf_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 xdc_runtime_Memory_HeapProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN2 xdc_runtime_System_Module_GateProxy_Module__loggerFxn2__C
Definition at line 14187 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Clock_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Event_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Queue_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_knl_Task_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 xdc_runtime_LoggerBuf_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 xdc_runtime_Memory_HeapProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN4 xdc_runtime_System_Module_GateProxy_Module__loggerFxn4__C
Definition at line 14194 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_BIOS_RtsGateProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_hal_Hwi_HwiProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Clock_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Clock_TimerProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Event_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Queue_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_knl_Task_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 xdc_runtime_LoggerBuf_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 xdc_runtime_Main_Module_GateProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 xdc_runtime_Memory_HeapProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGFXN8 xdc_runtime_System_Module_GateProxy_Module__loggerFxn8__C
Definition at line 14201 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_BIOS_RtsGateProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_gates_GateHwi_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_gates_GateMutex_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_hal_Hwi_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_hal_Hwi_HwiProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_heaps_HeapBuf_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Clock_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Clock_TimerProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Event_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Queue_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Semaphore_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_knl_Task_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ ti_sysbios_timers_rti_Timer_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ xdc_runtime_LoggerBuf_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ xdc_runtime_LoggerBuf_Module_GateProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ xdc_runtime_Main_Module_GateProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ xdc_runtime_Memory_HeapProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__LOGOBJ xdc_runtime_System_Module_GateProxy_Module__loggerObj__C
Definition at line 14166 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_BIOS_RtsGateProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_gates_GateHwi_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_gates_GateMutex_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_hal_Hwi_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_hal_Hwi_HwiProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_heaps_HeapBuf_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_heaps_HeapMem_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Clock_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Clock_TimerProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Event_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Queue_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Semaphore_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_knl_Task_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID ti_sysbios_timers_rti_Timer_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID xdc_runtime_LoggerBuf_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID xdc_runtime_LoggerBuf_Module_GateProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID xdc_runtime_Main_Module_GateProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID xdc_runtime_Memory_HeapProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
#define Module__MID xdc_runtime_System_Module_GateProxy_Module__id__C
Definition at line 14130 of file mmw_per4ft.c.
Typedef Documentation
typedef union Header Header
typedef struct ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module_State__
typedef struct ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_BIOS_RtsGateProxy_Object__
Definition at line 151 of file mmw_per4ft.c.
typedef struct ti_sysbios_family_arm_a15_TimestampProvider_Module_State__ ti_sysbios_family_arm_a15_TimestampProvider_Module_State__
typedef struct ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module_State__
typedef struct ti_sysbios_family_arm_v7a_Pmu_Module_State__ ti_sysbios_family_arm_v7a_Pmu_Module_State__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__
typedef struct ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__
typedef struct ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__
typedef struct ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__
typedef struct ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__
typedef struct ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__
typedef struct ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__
typedef ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_hal_Hwi_HwiProxy_Object__
Definition at line 325 of file mmw_per4ft.c.
typedef struct ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__
typedef struct ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__
typedef struct ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__
typedef struct ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module_State__
typedef struct ti_sysbios_heaps_HeapBuf_Object__ ti_sysbios_heaps_HeapBuf_Object__
typedef struct ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__
typedef struct ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateMutex_Object__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Object__
Definition at line 411 of file mmw_per4ft.c.
typedef struct ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__
typedef struct ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__
typedef struct ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module_State__
typedef struct ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__
typedef struct ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__
typedef ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_knl_Clock_TimerProxy_Object__
Definition at line 489 of file mmw_per4ft.c.
typedef struct ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__
typedef struct ti_sysbios_knl_Event_Object__ ti_sysbios_knl_Event_Object__
typedef struct ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__
typedef struct ti_sysbios_knl_Queue_Object__ ti_sysbios_knl_Queue_Object__
typedef struct ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__
typedef struct ti_sysbios_knl_Semaphore_Object__ ti_sysbios_knl_Semaphore_Object__
typedef struct ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__
typedef struct ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module_State__
typedef struct ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__
typedef struct ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__
typedef struct ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module_State__
typedef struct ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__
typedef struct ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module_State__
typedef struct xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module_State__
typedef struct xdc_runtime_LoggerBuf_Module__ xdc_runtime_LoggerBuf_Module__
typedef struct xdc_runtime_LoggerBuf_Module_GateProxy_Module__ xdc_runtime_LoggerBuf_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_LoggerBuf_Module_GateProxy_Object__
Definition at line 727 of file mmw_per4ft.c.
typedef struct xdc_runtime_LoggerBuf_Module_State__ xdc_runtime_LoggerBuf_Module_State__
typedef struct xdc_runtime_LoggerBuf_Object__ xdc_runtime_LoggerBuf_Object__
typedef struct xdc_runtime_Main_Module__ xdc_runtime_Main_Module__
typedef struct xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_Main_Module_GateProxy_Object__
Definition at line 769 of file mmw_per4ft.c.
typedef struct xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__
typedef ti_sysbios_heaps_HeapMem_Object__ xdc_runtime_Memory_HeapProxy_Object__
Definition at line 798 of file mmw_per4ft.c.
typedef struct xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module_State__
typedef struct xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module_State__
typedef struct xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module_State__
typedef struct xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__
typedef ti_sysbios_gates_GateHwi_Object__ xdc_runtime_System_Module_GateProxy_Object__
Definition at line 842 of file mmw_per4ft.c.
typedef struct xdc_runtime_System_Module_State__ xdc_runtime_System_Module_State__
typedef struct xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module_State__
Function Documentation
int __xdc__init (void)
Referenced by xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S().
Void _c_int00 ()
Referenced by ti_sysbios_knl_Clock_doTick__I().
Void ATTRIBUTE* calloc (SizeT nmemb, SizeT size)
Definition at line 2674 of file mmw_per4ft.c.
References ti_sysbios_rts_MemAlloc_alloc().
Referenced by realloc().
Void ATTRIBUTE free (Void * ptr)
Definition at line 2697 of file mmw_per4ft.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by realloc().
Void ATTRIBUTE* malloc (SizeT size)
Definition at line 2625 of file mmw_per4ft.c.
References ti_sysbios_rts_MemAlloc_alloc().
Referenced by realloc().
Void ATTRIBUTE* memalign (SizeT alignment, SizeT size)
Definition at line 2634 of file mmw_per4ft.c.
References Header::actualBuf, Header::header, and Header::size.
xdc_Void MmwDemo_sleep (xdc_Void)
Void ATTRIBUTE* realloc (Void * ptr, SizeT size)
Definition at line 2713 of file mmw_per4ft.c.
References ATTRIBUTE, calloc(), free(), Header::header, malloc(), and Header::size.
Referenced by realloc().
Void ti_sysbios_BIOS_atExitFunc__I (Int notused)
Definition at line 2349 of file mmw_per4ft.c.
Referenced by xdc_runtime_Text_visitRope__I().
Void ti_sysbios_BIOS_errorRaiseHook (xdc_runtime_Error_Block * eb)
Definition at line 2438 of file mmw_per4ft.c.
References ti_sysbios_BIOS_removeRTSLock().
xdc_Void ti_sysbios_BIOS_exitFunc (xdc_Int)
Referenced by ti_sysbios_family_arm_v7r_tms570_Core_resetC__I().
Void ti_sysbios_BIOS_exitFunc (Int stat)
Definition at line 2424 of file mmw_per4ft.c.
References ti_sysbios_BIOS_removeRTSLock().
xdc_Bool ti_sysbios_BIOS_Module__startupDone__S (void)
Definition at line 9691 of file mmw_per4ft.c.
Void ti_sysbios_BIOS_nullFunc__I ()
Definition at line 2395 of file mmw_per4ft.c.
Void ti_sysbios_BIOS_registerRTSLock ()
Referenced by ti_sysbios_BIOS_startFunc__I(), and xdc_runtime_Text_visitRope__I().
Void ti_sysbios_BIOS_registerRTSLock (Void)
Definition at line 2402 of file mmw_per4ft.c.
References ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
Void ti_sysbios_BIOS_removeRTSLock (Void)
Definition at line 2413 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_errorRaiseHook(), and ti_sysbios_BIOS_exitFunc().
ti_sysbios_BIOS_RtsGateProxy_Handle ti_sysbios_BIOS_RtsGateProxy_create (const ti_sysbios_BIOS_RtsGateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8469 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_create().
void ti_sysbios_BIOS_RtsGateProxy_delete (ti_sysbios_BIOS_RtsGateProxy_Handle * instp)
Definition at line 8475 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
xdc_IArg ti_sysbios_BIOS_RtsGateProxy_enter__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst)
Definition at line 8499 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_BIOS_RtsGateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8487 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
xdc_Void ti_sysbios_BIOS_RtsGateProxy_leave__E (ti_sysbios_BIOS_RtsGateProxy_Handle __inst, xdc_IArg key)
Definition at line 8505 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S (void)
Definition at line 8463 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
void ti_sysbios_BIOS_RtsGateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8481 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_Proxy__abstract__S (void)
Definition at line 9806 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S (void)
Definition at line 9810 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
xdc_Bool ti_sysbios_BIOS_RtsGateProxy_query__E (xdc_Int qual)
Definition at line 8493 of file mmw_per4ft.c.
Void ti_sysbios_BIOS_rtsLock ()
Definition at line 2365 of file mmw_per4ft.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
Void ti_sysbios_BIOS_rtsUnlock ()
Definition at line 2381 of file mmw_per4ft.c.
References ti_sysbios_BIOS_Module__state__V.
Referenced by ti_sysbios_BIOS_registerRTSLock().
xdc_Void ti_sysbios_BIOS_startFunc (xdc_Void)
Referenced by ti_sysbios_family_arm_v7r_tms570_Core_resetC__I().
Void ti_sysbios_BIOS_startFunc__I ()
Definition at line 2327 of file mmw_per4ft.c.
References ti_sysbios_BIOS_registerRTSLock(), and ti_sysbios_timers_rti_Timer_startup__E().
xdc_Bool ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F (void)
Definition at line 2055 of file mmw_per4ft.c.
References xdc_runtime_Startup_exec__I(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__S(), and ti_sysbios_timers_rti_Timer_Module__startupDone__F().
xdc_Bool ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__S (void)
Definition at line 9846 of file mmw_per4ft.c.
References ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F().
Referenced by xdc_runtime_LoggerBuf_TimestampProxy_Module__startupDone__S(), and xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S().
xdc_Int ti_sysbios_family_arm_a15_TimestampProvider_Module_startup__E (xdc_Int)
Void ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I ()
Referenced by ti_sysbios_knl_Clock_doTick__I().
Void ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I ()
Referenced by ti_sysbios_knl_Clock_doTick__I().
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__F (void)
Definition at line 2035 of file mmw_per4ft.c.
References ti_sysbios_hal_Hwi_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_exc_Exception_Module__startupDone__S(), and ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F().
xdc_Bool ti_sysbios_family_arm_exc_Exception_Module__startupDone__S (void)
Definition at line 9858 of file mmw_per4ft.c.
References ti_sysbios_family_arm_exc_Exception_Module__startupDone__F().
xdc_Int ti_sysbios_family_arm_exc_Exception_Module_startup__E (xdc_Int)
xdc_Bool ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S (void)
Definition at line 9822 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S().
xdc_Bool ti_sysbios_family_arm_TaskSupport_Module__startupDone__S (void)
Definition at line 9834 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S().
xdc_Bool ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F (void)
Definition at line 2043 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__S(), and ti_sysbios_hal_Hwi_Module__startupDone__F().
xdc_Bool ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__S (void)
Definition at line 9870 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F().
xdc_Int ti_sysbios_family_arm_v7a_Pmu_Module_startup__E (xdc_Int)
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F (void)
Definition at line 2047 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F(), and ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S().
xdc_Bool ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S (void)
Definition at line 9882 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F().
Referenced by ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S().
xdc_Int ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E (xdc_Int)
Void ti_sysbios_family_arm_v7r_tms570_Core_resetC__I ()
Definition at line 2788 of file mmw_per4ft.c.
References ti_sysbios_BIOS_exitFunc(), and ti_sysbios_BIOS_startFunc().
void ti_sysbios_family_arm_v7r_vim_Hwi_construct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10110 of file mmw_per4ft.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Handle ti_sysbios_family_arm_v7r_vim_Hwi_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_family_arm_v7r_vim_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10086 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_create().
void ti_sysbios_family_arm_v7r_vim_Hwi_delete (ti_sysbios_family_arm_v7r_vim_Hwi_Handle * instp)
Definition at line 10140 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S().
void ti_sysbios_family_arm_v7r_vim_Hwi_destruct (ti_sysbios_family_arm_v7r_vim_Hwi_Struct * obj)
Definition at line 10127 of file mmw_per4ft.c.
Void ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I ()
Referenced by ti_sysbios_knl_Clock_doTick__I().
xdc_runtime_Types_Label* ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10004 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S().
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F (void)
Definition at line 2031 of file mmw_per4ft.c.
References ti_sysbios_family_arm_exc_Exception_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S(), and ti_sysbios_heaps_HeapBuf_Module__startupDone__F().
xdc_Bool ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S (void)
Definition at line 9998 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F().
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S().
xdc_Int ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10057 of file mmw_per4ft.c.
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 10133 of file mmw_per4ft.c.
Referenced by ti_sysbios_family_arm_v7r_vim_Hwi_delete(), and ti_sysbios_hal_Hwi_HwiProxy_delete().
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__first__S (void)
Definition at line 10031 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__::link.
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10020 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_family_arm_v7r_vim_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 10044 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__::link.
xdc_Void ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10014 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Hwi_HwiProxy_Params__init__S().
void ti_sysbios_gates_GateHwi_construct (ti_sysbios_gates_GateHwi_Struct * __obj, const ti_sysbios_gates_GateHwi_Params * __paramsPtr)
Definition at line 10354 of file mmw_per4ft.c.
ti_sysbios_gates_GateHwi_Handle ti_sysbios_gates_GateHwi_create (const ti_sysbios_gates_GateHwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10336 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_Module_GateProxy_create(), xdc_runtime_Main_Module_GateProxy_create(), and xdc_runtime_System_Module_GateProxy_create().
void ti_sysbios_gates_GateHwi_delete (ti_sysbios_gates_GateHwi_Handle * instp)
Definition at line 10379 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
void ti_sysbios_gates_GateHwi_destruct (ti_sysbios_gates_GateHwi_Struct * obj)
Definition at line 10366 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_gates_GateHwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10261 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_Module_GateProxy_Handle__label__S(), xdc_runtime_Main_Module_GateProxy_Handle__label__S(), and xdc_runtime_System_Module_GateProxy_Handle__label__S().
xdc_Bool ti_sysbios_gates_GateHwi_Module__startupDone__S (void)
Definition at line 10255 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_Module_GateProxy_Module__startupDone__S(), xdc_runtime_Main_Module_GateProxy_Module__startupDone__S(), and xdc_runtime_System_Module_GateProxy_Module__startupDone__S().
xdc_Ptr ti_sysbios_gates_GateHwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10314 of file mmw_per4ft.c.
xdc_Void ti_sysbios_gates_GateHwi_Object__delete__S (xdc_Ptr instp)
Definition at line 10372 of file mmw_per4ft.c.
Referenced by ti_sysbios_gates_GateHwi_delete(), xdc_runtime_LoggerBuf_Module_GateProxy_delete(), xdc_runtime_Main_Module_GateProxy_delete(), and xdc_runtime_System_Module_GateProxy_delete().
xdc_Ptr ti_sysbios_gates_GateHwi_Object__first__S (void)
Definition at line 10288 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__::link.
xdc_Ptr ti_sysbios_gates_GateHwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10277 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_gates_GateHwi_Object__next__S (xdc_Ptr obj)
Definition at line 10301 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__::link.
xdc_Void ti_sysbios_gates_GateHwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10271 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_Module_GateProxy_Params__init__S(), xdc_runtime_Main_Module_GateProxy_Params__init__S(), and xdc_runtime_System_Module_GateProxy_Params__init__S().
void ti_sysbios_gates_GateMutex_construct (ti_sysbios_gates_GateMutex_Struct * __obj, const ti_sysbios_gates_GateMutex_Params * __paramsPtr)
Definition at line 10593 of file mmw_per4ft.c.
ti_sysbios_gates_GateMutex_Handle ti_sysbios_gates_GateMutex_create (const ti_sysbios_gates_GateMutex_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10575 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_create(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_create().
void ti_sysbios_gates_GateMutex_delete (ti_sysbios_gates_GateMutex_Handle * instp)
Definition at line 10618 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
void ti_sysbios_gates_GateMutex_destruct (ti_sysbios_gates_GateMutex_Struct * obj)
Definition at line 10605 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_gates_GateMutex_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10500 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Handle__label__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S().
xdc_Bool ti_sysbios_gates_GateMutex_Module__startupDone__S (void)
Definition at line 10494 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Module__startupDone__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S().
xdc_Ptr ti_sysbios_gates_GateMutex_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10553 of file mmw_per4ft.c.
xdc_Void ti_sysbios_gates_GateMutex_Object__delete__S (xdc_Ptr instp)
Definition at line 10611 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_delete(), ti_sysbios_gates_GateMutex_delete(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_delete().
xdc_Ptr ti_sysbios_gates_GateMutex_Object__first__S (void)
Definition at line 10527 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__::link.
xdc_Ptr ti_sysbios_gates_GateMutex_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10516 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_gates_GateMutex_Object__next__S (xdc_Ptr obj)
Definition at line 10540 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__::link.
xdc_Void ti_sysbios_gates_GateMutex_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10510 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Params__init__S(), and ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S().
xdc_Void ti_sysbios_hal_Cache_CacheProxy_disable__E (xdc_Bits16 type)
Definition at line 8530 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_enable__E (xdc_Bits16 type)
Definition at line 8524 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_inv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 8536 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S (void)
Definition at line 8518 of file mmw_per4ft.c.
References ti_sysbios_hal_CacheNull_Module__startupDone__S().
xdc_Bool ti_sysbios_hal_Cache_CacheProxy_Proxy__abstract__S (void)
Definition at line 10653 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S (void)
Definition at line 10657 of file mmw_per4ft.c.
References ti_sysbios_hal_CacheNull_Module__FXNS__C.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wait__E (void)
Definition at line 8566 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wb__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 8542 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbAll__E (void)
Definition at line 8554 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInv__E (xdc_Ptr blockPtr, xdc_SizeT byteCnt, xdc_Bits16 type, xdc_Bool wait)
Definition at line 8548 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Cache_CacheProxy_wbInvAll__E (void)
Definition at line 8560 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Cache_Module__startupDone__S (void)
Definition at line 10629 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_CacheNull_Module__startupDone__S (void)
Definition at line 10641 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Cache_CacheProxy_Module__startupDone__S().
xdc_UInt ti_sysbios_hal_Core_CoreProxy_getId__E (void)
Definition at line 8585 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiDisable__E (void)
Definition at line 8609 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_hal_Core_CoreProxy_hwiEnable__E (void)
Definition at line 8615 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Core_CoreProxy_hwiRestore__E (xdc_UInt key)
Definition at line 8621 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Core_CoreProxy_interruptCore__E (xdc_UInt coreId)
Definition at line 8591 of file mmw_per4ft.c.
xdc_IArg ti_sysbios_hal_Core_CoreProxy_lock__E (void)
Definition at line 8597 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Module__startupDone__S (void)
Definition at line 8579 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__S().
xdc_Bool ti_sysbios_hal_Core_CoreProxy_Proxy__abstract__S (void)
Definition at line 10680 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_hal_Core_CoreProxy_Proxy__delegate__S (void)
Definition at line 10684 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Core_CoreProxy_unlock__E (void)
Definition at line 8603 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Core_Module__startupDone__S (void)
Definition at line 10668 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_checkStack (xdc_Void)
void ti_sysbios_hal_Hwi_construct (ti_sysbios_hal_Hwi_Struct * __obj, xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10911 of file mmw_per4ft.c.
ti_sysbios_hal_Hwi_Handle ti_sysbios_hal_Hwi_create (xdc_Int intNum, ti_sysbios_hal_Hwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 10887 of file mmw_per4ft.c.
void ti_sysbios_hal_Hwi_delete (ti_sysbios_hal_Hwi_Handle * instp)
Definition at line 10941 of file mmw_per4ft.c.
References ti_sysbios_hal_Hwi_Object__delete__S().
void ti_sysbios_hal_Hwi_destruct (ti_sysbios_hal_Hwi_Struct * obj)
Definition at line 10928 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 10805 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_clearInterrupt__E (xdc_UInt intNum)
Definition at line 8736 of file mmw_per4ft.c.
ti_sysbios_hal_Hwi_HwiProxy_Handle ti_sysbios_hal_Hwi_HwiProxy_create (xdc_Int intNum, ti_sysbios_interfaces_IHwi_FuncPtr hwiFxn, const ti_sysbios_hal_Hwi_HwiProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8640 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_create().
void ti_sysbios_hal_Hwi_HwiProxy_delete (ti_sysbios_hal_Hwi_HwiProxy_Handle * instp)
Definition at line 8646 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Object__delete__S().
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disable__E (void)
Definition at line 8682 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_disableInterrupt__E (xdc_UInt intNum)
Definition at line 8718 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enable__E (void)
Definition at line 8688 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_hal_Hwi_HwiProxy_enableInterrupt__E (xdc_UInt intNum)
Definition at line 8724 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getCoreStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth, xdc_UInt coreId)
Definition at line 8670 of file mmw_per4ft.c.
ti_sysbios_interfaces_IHwi_FuncPtr ti_sysbios_hal_Hwi_HwiProxy_getFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_UArg * arg)
Definition at line 8742 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_hal_Hwi_HwiProxy_getHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id)
Definition at line 8754 of file mmw_per4ft.c.
ti_sysbios_interfaces_IHwi_Irp ti_sysbios_hal_Hwi_HwiProxy_getIrp__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst)
Definition at line 8766 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_getStackInfo__E (ti_sysbios_interfaces_IHwi_StackInfo * stkInfo, xdc_Bool computeStackDepth)
Definition at line 8664 of file mmw_per4ft.c.
xdc_Char* ti_sysbios_hal_Hwi_HwiProxy_getTaskSP__E (void)
Definition at line 8712 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_hal_Hwi_HwiProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8658 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Handle__label__S().
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Module__startupDone__S (void)
Definition at line 8634 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__S().
void ti_sysbios_hal_Hwi_HwiProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8652 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Params__init__S().
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_post__E (xdc_UInt intNum)
Definition at line 8706 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_hal_Hwi_HwiProxy_Proxy__abstract__S (void)
Definition at line 11055 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_hal_Hwi_HwiProxy_Proxy__delegate__S (void)
Definition at line 11059 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restore__E (xdc_UInt key)
Definition at line 8694 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_restoreInterrupt__E (xdc_UInt intNum, xdc_UInt key)
Definition at line 8730 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setFunc__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, ti_sysbios_interfaces_IHwi_FuncPtr fxn, xdc_UArg arg)
Definition at line 8748 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_setHookContext__E (ti_sysbios_hal_Hwi_HwiProxy_Handle __inst, xdc_Int id, xdc_Ptr hookContext)
Definition at line 8760 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_startup__E (void)
Definition at line 8676 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_HwiProxy_switchFromBootStack__E (void)
Definition at line 8700 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_initStack (xdc_Void)
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__F (void)
Definition at line 2039 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_exc_Exception_Module__startupDone__F(), and ti_sysbios_hal_Hwi_Module__startupDone__S().
xdc_Bool ti_sysbios_hal_Hwi_Module__startupDone__S (void)
Definition at line 10799 of file mmw_per4ft.c.
References ti_sysbios_hal_Hwi_Module__startupDone__F().
xdc_Int ti_sysbios_hal_Hwi_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_hal_Hwi_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 10858 of file mmw_per4ft.c.
xdc_Void ti_sysbios_hal_Hwi_Object__delete__S (xdc_Ptr instp)
Definition at line 10934 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Hwi_delete().
xdc_Ptr ti_sysbios_hal_Hwi_Object__first__S (void)
Definition at line 10832 of file mmw_per4ft.c.
References ti_sysbios_hal_Hwi_Module__::link.
xdc_Ptr ti_sysbios_hal_Hwi_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 10821 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_hal_Hwi_Object__next__S (xdc_Ptr obj)
Definition at line 10845 of file mmw_per4ft.c.
References ti_sysbios_hal_Hwi_Module__::link.
xdc_Void ti_sysbios_hal_Hwi_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 10815 of file mmw_per4ft.c.
void ti_sysbios_heaps_HeapBuf_construct (ti_sysbios_heaps_HeapBuf_Struct * __obj, const ti_sysbios_heaps_HeapBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11286 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapBuf_Handle ti_sysbios_heaps_HeapBuf_create (const ti_sysbios_heaps_HeapBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11262 of file mmw_per4ft.c.
void ti_sysbios_heaps_HeapBuf_delete (ti_sysbios_heaps_HeapBuf_Handle * instp)
Definition at line 11316 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapBuf_Object__delete__S().
void ti_sysbios_heaps_HeapBuf_destruct (ti_sysbios_heaps_HeapBuf_Struct * obj)
Definition at line 11303 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11181 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__F (void)
Definition at line 2027 of file mmw_per4ft.c.
References ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_heaps_HeapBuf_Module__startupDone__S(), and ti_sysbios_knl_Task_Module__startupDone__F().
xdc_Bool ti_sysbios_heaps_HeapBuf_Module__startupDone__S (void)
Definition at line 11175 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapBuf_Module__startupDone__F().
xdc_Int ti_sysbios_heaps_HeapBuf_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11234 of file mmw_per4ft.c.
xdc_Void ti_sysbios_heaps_HeapBuf_Object__delete__S (xdc_Ptr instp)
Definition at line 11309 of file mmw_per4ft.c.
Referenced by ti_sysbios_heaps_HeapBuf_delete().
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__first__S (void)
Definition at line 11208 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapBuf_Module__::link.
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11197 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_heaps_HeapBuf_Object__next__S (xdc_Ptr obj)
Definition at line 11221 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapBuf_Module__::link.
xdc_Void ti_sysbios_heaps_HeapBuf_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11191 of file mmw_per4ft.c.
void ti_sysbios_heaps_HeapMem_construct (ti_sysbios_heaps_HeapMem_Struct * __obj, const ti_sysbios_heaps_HeapMem_Params * __paramsPtr)
Definition at line 11530 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapMem_Handle ti_sysbios_heaps_HeapMem_create (const ti_sysbios_heaps_HeapMem_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11512 of file mmw_per4ft.c.
Referenced by xdc_runtime_Memory_HeapProxy_create().
void ti_sysbios_heaps_HeapMem_delete (ti_sysbios_heaps_HeapMem_Handle * instp)
Definition at line 11555 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
void ti_sysbios_heaps_HeapMem_destruct (ti_sysbios_heaps_HeapMem_Struct * obj)
Definition at line 11542 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11437 of file mmw_per4ft.c.
Referenced by xdc_runtime_Memory_HeapProxy_Handle__label__S().
xdc_Bool ti_sysbios_heaps_HeapMem_Module__startupDone__S (void)
Definition at line 11431 of file mmw_per4ft.c.
Referenced by xdc_runtime_Memory_HeapProxy_Module__startupDone__S().
ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle ti_sysbios_heaps_HeapMem_Module_GateProxy_create (const ti_sysbios_heaps_HeapMem_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8785 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_create().
void ti_sysbios_heaps_HeapMem_Module_GateProxy_delete (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle * instp)
Definition at line 8791 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Object__delete__S().
xdc_IArg ti_sysbios_heaps_HeapMem_Module_GateProxy_enter__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst)
Definition at line 8815 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8803 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Handle__label__S().
xdc_Void ti_sysbios_heaps_HeapMem_Module_GateProxy_leave__E (ti_sysbios_heaps_HeapMem_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 8821 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__startupDone__S (void)
Definition at line 8779 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__startupDone__S().
void ti_sysbios_heaps_HeapMem_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8797 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Params__init__S().
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 11669 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 11673 of file mmw_per4ft.c.
References ti_sysbios_gates_GateMutex_Module__FXNS__C.
xdc_Bool ti_sysbios_heaps_HeapMem_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 8809 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11490 of file mmw_per4ft.c.
xdc_Void ti_sysbios_heaps_HeapMem_Object__delete__S (xdc_Ptr instp)
Definition at line 11548 of file mmw_per4ft.c.
Referenced by ti_sysbios_heaps_HeapMem_delete(), and xdc_runtime_Memory_HeapProxy_delete().
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__first__S (void)
Definition at line 11464 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Module__::link.
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11453 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_heaps_HeapMem_Object__next__S (xdc_Ptr obj)
Definition at line 11477 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Module__::link.
xdc_Void ti_sysbios_heaps_HeapMem_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11447 of file mmw_per4ft.c.
Referenced by xdc_runtime_Memory_HeapProxy_Params__init__S().
void ti_sysbios_knl_Clock_construct (ti_sysbios_knl_Clock_Struct * __obj, ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr)
Definition at line 11889 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_Handle ti_sysbios_knl_Clock_create (ti_sysbios_knl_Clock_FuncPtr clockFxn, xdc_UInt timeout, const ti_sysbios_knl_Clock_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 11871 of file mmw_per4ft.c.
void ti_sysbios_knl_Clock_delete (ti_sysbios_knl_Clock_Handle * instp)
Definition at line 11914 of file mmw_per4ft.c.
References ti_sysbios_knl_Clock_Object__delete__S().
void ti_sysbios_knl_Clock_destruct (ti_sysbios_knl_Clock_Struct * obj)
Definition at line 11901 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_doTick__I (xdc_UArg)
Void ti_sysbios_knl_Clock_doTick__I (UArg arg)
Definition at line 2463 of file mmw_per4ft.c.
References _c_int00(), ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I(), ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I(), ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I(), and ti_sysbios_knl_Clock_Module__state__V.
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 11795 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__F (void)
Definition at line 2019 of file mmw_per4ft.c.
References ti_sysbios_knl_Task_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Clock_Module__startupDone__S(), and xdc_runtime_System_Module__startupDone__F().
xdc_Bool ti_sysbios_knl_Clock_Module__startupDone__S (void)
Definition at line 11789 of file mmw_per4ft.c.
References ti_sysbios_knl_Clock_Module__startupDone__F().
xdc_Int ti_sysbios_knl_Clock_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_knl_Clock_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 11848 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_Object__delete__S (xdc_Ptr instp)
Definition at line 11907 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_delete().
xdc_Ptr ti_sysbios_knl_Clock_Object__first__S (void)
Definition at line 11822 of file mmw_per4ft.c.
References ti_sysbios_knl_Clock_Module__::link.
xdc_Ptr ti_sysbios_knl_Clock_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 11811 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Clock_Object__next__S (xdc_Ptr obj)
Definition at line 11835 of file mmw_per4ft.c.
References ti_sysbios_knl_Clock_Module__::link.
xdc_Void ti_sysbios_knl_Clock_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 11805 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_TimerProxy_Handle ti_sysbios_knl_Clock_TimerProxy_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_knl_Clock_TimerProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 8840 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_create().
void ti_sysbios_knl_Clock_TimerProxy_delete (ti_sysbios_knl_Clock_TimerProxy_Handle * instp)
Definition at line 8846 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCount__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8924 of file mmw_per4ft.c.
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getCurrentTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_Bool save)
Definition at line 8966 of file mmw_per4ft.c.
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredCounts__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8954 of file mmw_per4ft.c.
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getExpiredTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 tickPeriod)
Definition at line 8960 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_getFreq__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_runtime_Types_FreqHz * freq)
Definition at line 8930 of file mmw_per4ft.c.
ti_sysbios_interfaces_ITimer_FuncPtr ti_sysbios_knl_Clock_TimerProxy_getFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UArg * arg)
Definition at line 8936 of file mmw_per4ft.c.
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getMaxTicks__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8882 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_knl_Clock_TimerProxy_getNumTimers__E (void)
Definition at line 8864 of file mmw_per4ft.c.
xdc_UInt32 ti_sysbios_knl_Clock_TimerProxy_getPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8918 of file mmw_per4ft.c.
ti_sysbios_interfaces_ITimer_Status ti_sysbios_knl_Clock_TimerProxy_getStatus__E (xdc_UInt id)
Definition at line 8870 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_knl_Clock_TimerProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 8858 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Handle__label__S().
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S (void)
Definition at line 8834 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__S().
void ti_sysbios_knl_Clock_TimerProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 8852 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Params__init__S().
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_Proxy__abstract__S (void)
Definition at line 12028 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_knl_Clock_TimerProxy_Proxy__delegate__S (void)
Definition at line 12032 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setFunc__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, ti_sysbios_interfaces_ITimer_FuncPtr fxn, xdc_UArg arg)
Definition at line 8942 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setNextTick__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 ticks)
Definition at line 8888 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_setPeriod__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 period)
Definition at line 8906 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Clock_TimerProxy_setPeriodMicroSecs__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 microsecs)
Definition at line 8912 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_start__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8894 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_startup__E (void)
Definition at line 8876 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_stop__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst)
Definition at line 8900 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Clock_TimerProxy_trigger__E (ti_sysbios_knl_Clock_TimerProxy_Handle __inst, xdc_UInt32 cycles)
Definition at line 8948 of file mmw_per4ft.c.
void ti_sysbios_knl_Event_construct (ti_sysbios_knl_Event_Struct * __obj, const ti_sysbios_knl_Event_Params * __paramsPtr)
Definition at line 12247 of file mmw_per4ft.c.
ti_sysbios_knl_Event_Handle ti_sysbios_knl_Event_create (const ti_sysbios_knl_Event_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12229 of file mmw_per4ft.c.
void ti_sysbios_knl_Event_delete (ti_sysbios_knl_Event_Handle * instp)
Definition at line 12272 of file mmw_per4ft.c.
References ti_sysbios_knl_Event_Object__delete__S().
void ti_sysbios_knl_Event_destruct (ti_sysbios_knl_Event_Struct * obj)
Definition at line 12259 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_knl_Event_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12154 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Event_Module__startupDone__S (void)
Definition at line 12148 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Event_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12207 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Event_Object__delete__S (xdc_Ptr instp)
Definition at line 12265 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Event_delete().
xdc_Ptr ti_sysbios_knl_Event_Object__first__S (void)
Definition at line 12181 of file mmw_per4ft.c.
References ti_sysbios_knl_Event_Module__::link.
xdc_Ptr ti_sysbios_knl_Event_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12170 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Event_Object__next__S (xdc_Ptr obj)
Definition at line 12194 of file mmw_per4ft.c.
References ti_sysbios_knl_Event_Module__::link.
xdc_Void ti_sysbios_knl_Event_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12164 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Idle_Module__startupDone__S (void)
Definition at line 12283 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Intrinsics_Module__startupDone__S (void)
Definition at line 12295 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_knl_Intrinsics_SupportProxy_maxbit__E (xdc_UInt bits)
Definition at line 8985 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Module__startupDone__S (void)
Definition at line 8979 of file mmw_per4ft.c.
References ti_sysbios_family_arm_IntrinsicsSupport_Module__startupDone__S().
xdc_Bool ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__abstract__S (void)
Definition at line 12307 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_knl_Intrinsics_SupportProxy_Proxy__delegate__S (void)
Definition at line 12311 of file mmw_per4ft.c.
void ti_sysbios_knl_Queue_construct (ti_sysbios_knl_Queue_Struct * __obj, const ti_sysbios_knl_Queue_Params * __paramsPtr)
Definition at line 12525 of file mmw_per4ft.c.
ti_sysbios_knl_Queue_Handle ti_sysbios_knl_Queue_create (const ti_sysbios_knl_Queue_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12507 of file mmw_per4ft.c.
void ti_sysbios_knl_Queue_delete (ti_sysbios_knl_Queue_Handle * instp)
Definition at line 12550 of file mmw_per4ft.c.
References ti_sysbios_knl_Queue_Object__delete__S().
void ti_sysbios_knl_Queue_destruct (ti_sysbios_knl_Queue_Struct * obj)
Definition at line 12537 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_knl_Queue_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12432 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Queue_Module__startupDone__S (void)
Definition at line 12426 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Queue_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12485 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Queue_Object__delete__S (xdc_Ptr instp)
Definition at line 12543 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Queue_delete().
xdc_Ptr ti_sysbios_knl_Queue_Object__first__S (void)
Definition at line 12459 of file mmw_per4ft.c.
References ti_sysbios_knl_Queue_Module__::link.
xdc_Ptr ti_sysbios_knl_Queue_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12448 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Queue_Object__next__S (xdc_Ptr obj)
Definition at line 12472 of file mmw_per4ft.c.
References ti_sysbios_knl_Queue_Module__::link.
xdc_Void ti_sysbios_knl_Queue_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12442 of file mmw_per4ft.c.
void ti_sysbios_knl_Semaphore_construct (ti_sysbios_knl_Semaphore_Struct * __obj, xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr)
Definition at line 12765 of file mmw_per4ft.c.
ti_sysbios_knl_Semaphore_Handle ti_sysbios_knl_Semaphore_create (xdc_Int count, const ti_sysbios_knl_Semaphore_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12747 of file mmw_per4ft.c.
void ti_sysbios_knl_Semaphore_delete (ti_sysbios_knl_Semaphore_Handle * instp)
Definition at line 12790 of file mmw_per4ft.c.
References ti_sysbios_knl_Semaphore_Object__delete__S().
void ti_sysbios_knl_Semaphore_destruct (ti_sysbios_knl_Semaphore_Struct * obj)
Definition at line 12777 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_knl_Semaphore_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12671 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Semaphore_Module__startupDone__S (void)
Definition at line 12665 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Semaphore_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12724 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Semaphore_Object__delete__S (xdc_Ptr instp)
Definition at line 12783 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Semaphore_delete().
xdc_Ptr ti_sysbios_knl_Semaphore_Object__first__S (void)
Definition at line 12698 of file mmw_per4ft.c.
References ti_sysbios_knl_Semaphore_Module__::link.
xdc_Ptr ti_sysbios_knl_Semaphore_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12687 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Semaphore_Object__next__S (xdc_Ptr obj)
Definition at line 12711 of file mmw_per4ft.c.
References ti_sysbios_knl_Semaphore_Module__::link.
xdc_Void ti_sysbios_knl_Semaphore_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12681 of file mmw_per4ft.c.
void ti_sysbios_knl_Task_construct (ti_sysbios_knl_Task_Struct * __obj, ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 13017 of file mmw_per4ft.c.
ti_sysbios_knl_Task_Handle ti_sysbios_knl_Task_create (ti_sysbios_knl_Task_FuncPtr fxn, const ti_sysbios_knl_Task_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 12993 of file mmw_per4ft.c.
void ti_sysbios_knl_Task_delete (ti_sysbios_knl_Task_Handle * instp)
Definition at line 13047 of file mmw_per4ft.c.
References ti_sysbios_knl_Task_Object__delete__S().
void ti_sysbios_knl_Task_destruct (ti_sysbios_knl_Task_Struct * obj)
Definition at line 13034 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_knl_Task_disable__E (xdc_Void)
xdc_runtime_Types_Label* ti_sysbios_knl_Task_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 12911 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__F (void)
Definition at line 2023 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapBuf_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_knl_Clock_Module__startupDone__F(), and ti_sysbios_knl_Task_Module__startupDone__S().
xdc_Bool ti_sysbios_knl_Task_Module__startupDone__S (void)
Definition at line 12905 of file mmw_per4ft.c.
References ti_sysbios_knl_Task_Module__startupDone__F().
xdc_Int ti_sysbios_knl_Task_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_knl_Task_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 12964 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Task_Object__delete__S (xdc_Ptr instp)
Definition at line 13040 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Task_delete().
xdc_Ptr ti_sysbios_knl_Task_Object__first__S (void)
Definition at line 12938 of file mmw_per4ft.c.
References ti_sysbios_knl_Task_Module__::link.
xdc_Ptr ti_sysbios_knl_Task_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 12927 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Task_Object__next__S (xdc_Ptr obj)
Definition at line 12951 of file mmw_per4ft.c.
References ti_sysbios_knl_Task_Module__::link.
xdc_Void ti_sysbios_knl_Task_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 12921 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Task_restoreHwi__E (xdc_UInt)
xdc_Bool ti_sysbios_knl_Task_SupportProxy_checkStack__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 9016 of file mmw_per4ft.c.
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_getDefaultStackSize__E (void)
Definition at line 9034 of file mmw_per4ft.c.
xdc_UInt ti_sysbios_knl_Task_SupportProxy_getStackAlignment__E (void)
Definition at line 9028 of file mmw_per4ft.c.
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Module__startupDone__S (void)
Definition at line 8998 of file mmw_per4ft.c.
References ti_sysbios_family_arm_TaskSupport_Module__startupDone__S().
xdc_Bool ti_sysbios_knl_Task_SupportProxy_Proxy__abstract__S (void)
Definition at line 13058 of file mmw_per4ft.c.
xdc_CPtr ti_sysbios_knl_Task_SupportProxy_Proxy__delegate__S (void)
Definition at line 13062 of file mmw_per4ft.c.
xdc_SizeT ti_sysbios_knl_Task_SupportProxy_stackUsed__E (xdc_Char * stack, xdc_SizeT size)
Definition at line 9022 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_knl_Task_SupportProxy_start__E (xdc_Ptr curTask, ti_sysbios_interfaces_ITaskSupport_FuncPtr enterFxn, ti_sysbios_interfaces_ITaskSupport_FuncPtr exitFxn, xdc_runtime_Error_Block * eb)
Definition at line 9004 of file mmw_per4ft.c.
xdc_Void ti_sysbios_knl_Task_SupportProxy_swap__E (xdc_Ptr * oldtskContext, xdc_Ptr * newtskContext)
Definition at line 9010 of file mmw_per4ft.c.
static Void* ti_sysbios_rts_MemAlloc_alloc (SizeT size) static
Definition at line 2598 of file mmw_per4ft.c.
References Header::actualBuf, Header::header, and Header::size.
Referenced by calloc(), and malloc().
void ti_sysbios_timers_rti_Timer_construct (ti_sysbios_timers_rti_Timer_Struct * __obj, xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 13289 of file mmw_per4ft.c.
ti_sysbios_timers_rti_Timer_Handle ti_sysbios_timers_rti_Timer_create (xdc_Int id, ti_sysbios_interfaces_ITimer_FuncPtr tickFxn, const ti_sysbios_timers_rti_Timer_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 13265 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_create().
void ti_sysbios_timers_rti_Timer_delete (ti_sysbios_timers_rti_Timer_Handle * instp)
Definition at line 13319 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Object__delete__S().
void ti_sysbios_timers_rti_Timer_destruct (ti_sysbios_timers_rti_Timer_Struct * obj)
Definition at line 13306 of file mmw_per4ft.c.
xdc_runtime_Types_Label* ti_sysbios_timers_rti_Timer_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 13183 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Handle__label__S().
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__F (void)
Definition at line 2051 of file mmw_per4ft.c.
References ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F(), and ti_sysbios_timers_rti_Timer_Module__startupDone__S().
xdc_Bool ti_sysbios_timers_rti_Timer_Module__startupDone__S (void)
Definition at line 13177 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Module__startupDone__F().
Referenced by ti_sysbios_knl_Clock_TimerProxy_Module__startupDone__S().
xdc_Int ti_sysbios_timers_rti_Timer_Module_startup__E (xdc_Int)
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 13236 of file mmw_per4ft.c.
xdc_Void ti_sysbios_timers_rti_Timer_Object__delete__S (xdc_Ptr instp)
Definition at line 13312 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_delete(), and ti_sysbios_timers_rti_Timer_delete().
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__first__S (void)
Definition at line 13210 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Module__::link.
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 13199 of file mmw_per4ft.c.
xdc_Ptr ti_sysbios_timers_rti_Timer_Object__next__S (xdc_Ptr obj)
Definition at line 13223 of file mmw_per4ft.c.
References ti_sysbios_timers_rti_Timer_Module__::link.
xdc_Void ti_sysbios_timers_rti_Timer_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 13193 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_TimerProxy_Params__init__S().
Void ti_sysbios_timers_rti_Timer_startup__E ()
Referenced by ti_sysbios_BIOS_startFunc__I(), and xdc_runtime_Text_visitRope__I().
xdc_Bool ti_sysbios_utils_Load_Module__startupDone__S (void)
Definition at line 13330 of file mmw_per4ft.c.
xdc_Void ti_sysbios_utils_Load_taskRegHook__E (xdc_Int)
Void ti_sysbios_utils_Load_update__E ()
Definition at line 2531 of file mmw_per4ft.c.
xdc__META (__ASM__)
xdc__META (__ISA__)
xdc__META (__PLAT__)
xdc__META (__TARG__)
xdc__META (__TRDR__)
xdc_Bool xdc_runtime_Assert_Module__startupDone__S (void)
Definition at line 13342 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Core_Module__startupDone__S (void)
Definition at line 13354 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Defaults_Module__startupDone__S (void)
Definition at line 13366 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Diags_Module__startupDone__S (void)
Definition at line 13378 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Error_Module__startupDone__S (void)
Definition at line 13390 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Gate_Module__startupDone__S (void)
Definition at line 13402 of file mmw_per4ft.c.
xdc_runtime_IFilterLogger_Handle xdc_runtime_IFilterLogger_create (xdc_runtime_IFilterLogger_Module mod, const xdc_runtime_IFilterLogger_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9657 of file mmw_per4ft.c.
void xdc_runtime_IFilterLogger_delete (xdc_runtime_IFilterLogger_Handle * instp)
Definition at line 9663 of file mmw_per4ft.c.
xdc_runtime_IGateProvider_Handle xdc_runtime_IGateProvider_create (xdc_runtime_IGateProvider_Module mod, const xdc_runtime_IGateProvider_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9640 of file mmw_per4ft.c.
void xdc_runtime_IGateProvider_delete (xdc_runtime_IGateProvider_Handle * instp)
Definition at line 9646 of file mmw_per4ft.c.
xdc_runtime_IHeap_Handle xdc_runtime_IHeap_create (xdc_runtime_IHeap_Module mod, const xdc_runtime_IHeap_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9623 of file mmw_per4ft.c.
void xdc_runtime_IHeap_delete (xdc_runtime_IHeap_Handle * instp)
Definition at line 9629 of file mmw_per4ft.c.
xdc_runtime_ILogger_Handle xdc_runtime_ILogger_create (xdc_runtime_ILogger_Module mod, const xdc_runtime_ILogger_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9674 of file mmw_per4ft.c.
void xdc_runtime_ILogger_delete (xdc_runtime_ILogger_Handle * instp)
Definition at line 9680 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Log_Module__startupDone__S (void)
Definition at line 13414 of file mmw_per4ft.c.
void xdc_runtime_LoggerBuf_construct (xdc_runtime_LoggerBuf_Struct * __obj, const xdc_runtime_LoggerBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 13641 of file mmw_per4ft.c.
xdc_runtime_LoggerBuf_Handle xdc_runtime_LoggerBuf_create (const xdc_runtime_LoggerBuf_Params * __paramsPtr, xdc_runtime_Error_Block * eb)
Definition at line 13617 of file mmw_per4ft.c.
void xdc_runtime_LoggerBuf_delete (xdc_runtime_LoggerBuf_Handle * instp)
Definition at line 13671 of file mmw_per4ft.c.
References xdc_runtime_LoggerBuf_Object__delete__S().
void xdc_runtime_LoggerBuf_destruct (xdc_runtime_LoggerBuf_Struct * obj)
Definition at line 13658 of file mmw_per4ft.c.
xdc_runtime_Types_Label* xdc_runtime_LoggerBuf_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 13536 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_LoggerBuf_Module__startupDone__F (void)
Definition at line 2011 of file mmw_per4ft.c.
References xdc_runtime_Startup_Module__state__V, and xdc_runtime_System_Module__startupDone__F().
Referenced by xdc_runtime_LoggerBuf_Module__startupDone__S().
xdc_Bool xdc_runtime_LoggerBuf_Module__startupDone__S (void)
Definition at line 13530 of file mmw_per4ft.c.
References xdc_runtime_LoggerBuf_Module__startupDone__F().
xdc_runtime_LoggerBuf_Module_GateProxy_Handle xdc_runtime_LoggerBuf_Module_GateProxy_create (const xdc_runtime_LoggerBuf_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9053 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_create().
void xdc_runtime_LoggerBuf_Module_GateProxy_delete (xdc_runtime_LoggerBuf_Module_GateProxy_Handle * instp)
Definition at line 9059 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_IArg xdc_runtime_LoggerBuf_Module_GateProxy_enter__E (xdc_runtime_LoggerBuf_Module_GateProxy_Handle __inst)
Definition at line 9083 of file mmw_per4ft.c.
xdc_runtime_Types_Label* xdc_runtime_LoggerBuf_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9071 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_Void xdc_runtime_LoggerBuf_Module_GateProxy_leave__E (xdc_runtime_LoggerBuf_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 9089 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_Module__startupDone__S (void)
Definition at line 9047 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
void xdc_runtime_LoggerBuf_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9065 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 13785 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_LoggerBuf_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 13789 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_Bool xdc_runtime_LoggerBuf_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 9077 of file mmw_per4ft.c.
xdc_Int xdc_runtime_LoggerBuf_Module_startup__E (xdc_Int)
xdc_Ptr xdc_runtime_LoggerBuf_Object__create__S (xdc_CPtr __aa, const xdc_UChar * __paramsPtr, xdc_SizeT __psz, xdc_runtime_Error_Block * eb)
Definition at line 13589 of file mmw_per4ft.c.
xdc_Void xdc_runtime_LoggerBuf_Object__delete__S (xdc_Ptr instp)
Definition at line 13664 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_delete().
xdc_Ptr xdc_runtime_LoggerBuf_Object__first__S (void)
Definition at line 13563 of file mmw_per4ft.c.
References xdc_runtime_LoggerBuf_Module__::link.
xdc_Ptr xdc_runtime_LoggerBuf_Object__get__S (xdc_Ptr oa, xdc_Int i)
Definition at line 13552 of file mmw_per4ft.c.
xdc_Ptr xdc_runtime_LoggerBuf_Object__next__S (xdc_Ptr obj)
Definition at line 13576 of file mmw_per4ft.c.
References xdc_runtime_LoggerBuf_Module__::link.
xdc_Void xdc_runtime_LoggerBuf_Params__init__S (xdc_Ptr prms, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 13546 of file mmw_per4ft.c.
xdc_Bits32 xdc_runtime_LoggerBuf_TimestampProxy_get32__E (void)
Definition at line 9108 of file mmw_per4ft.c.
xdc_Void xdc_runtime_LoggerBuf_TimestampProxy_get64__E (xdc_runtime_Types_Timestamp64 * result)
Definition at line 9114 of file mmw_per4ft.c.
xdc_Void xdc_runtime_LoggerBuf_TimestampProxy_getFreq__E (xdc_runtime_Types_FreqHz * freq)
Definition at line 9120 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_LoggerBuf_TimestampProxy_Module__startupDone__S (void)
Definition at line 9102 of file mmw_per4ft.c.
References ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__S().
xdc_Bool xdc_runtime_LoggerBuf_TimestampProxy_Proxy__abstract__S (void)
Definition at line 13801 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_LoggerBuf_TimestampProxy_Proxy__delegate__S (void)
Definition at line 13805 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Main_Module__startupDone__S (void)
Definition at line 13816 of file mmw_per4ft.c.
xdc_runtime_Main_Module_GateProxy_Handle xdc_runtime_Main_Module_GateProxy_create (const xdc_runtime_Main_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9139 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_create().
void xdc_runtime_Main_Module_GateProxy_delete (xdc_runtime_Main_Module_GateProxy_Handle * instp)
Definition at line 9145 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_IArg xdc_runtime_Main_Module_GateProxy_enter__E (xdc_runtime_Main_Module_GateProxy_Handle __inst)
Definition at line 9169 of file mmw_per4ft.c.
xdc_runtime_Types_Label* xdc_runtime_Main_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9157 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_Void xdc_runtime_Main_Module_GateProxy_leave__E (xdc_runtime_Main_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 9175 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Main_Module_GateProxy_Module__startupDone__S (void)
Definition at line 9133 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
void xdc_runtime_Main_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9151 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_Bool xdc_runtime_Main_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 13931 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 13935 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_Bool xdc_runtime_Main_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 9163 of file mmw_per4ft.c.
xdc_Ptr xdc_runtime_Memory_HeapProxy_alloc__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_SizeT size, xdc_SizeT align, xdc_runtime_Error_Block * eb)
Definition at line 9218 of file mmw_per4ft.c.
xdc_runtime_Memory_HeapProxy_Handle xdc_runtime_Memory_HeapProxy_create (const xdc_runtime_Memory_HeapProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9194 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_create().
void xdc_runtime_Memory_HeapProxy_delete (xdc_runtime_Memory_HeapProxy_Handle * instp)
Definition at line 9200 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Object__delete__S().
xdc_Void xdc_runtime_Memory_HeapProxy_free__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_Ptr block, xdc_SizeT size)
Definition at line 9224 of file mmw_per4ft.c.
xdc_Void xdc_runtime_Memory_HeapProxy_getStats__E (xdc_runtime_Memory_HeapProxy_Handle __inst, xdc_runtime_Memory_Stats * stats)
Definition at line 9236 of file mmw_per4ft.c.
xdc_runtime_Types_Label* xdc_runtime_Memory_HeapProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9212 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Handle__label__S().
xdc_Bool xdc_runtime_Memory_HeapProxy_isBlocking__E (xdc_runtime_Memory_HeapProxy_Handle __inst)
Definition at line 9230 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Memory_HeapProxy_Module__startupDone__S (void)
Definition at line 9188 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Module__startupDone__S().
void xdc_runtime_Memory_HeapProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9206 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Params__init__S().
xdc_Bool xdc_runtime_Memory_HeapProxy_Proxy__abstract__S (void)
Definition at line 14062 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_Memory_HeapProxy_Proxy__delegate__S (void)
Definition at line 14066 of file mmw_per4ft.c.
References ti_sysbios_heaps_HeapMem_Module__FXNS__C.
xdc_Bool xdc_runtime_Memory_Module__startupDone__S (void)
Definition at line 13947 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Registry_Module__startupDone__S (void)
Definition at line 14078 of file mmw_per4ft.c.
xdc_Void xdc_runtime_Startup_exec__I (void)
Definition at line 2084 of file mmw_per4ft.c.
References xdc_runtime_Startup_reset__I(), and xdc_runtime_Startup_startModsFxn__C.
Referenced by ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F().
xdc_Bool xdc_runtime_Startup_Module__startupDone__S (void)
Definition at line 14090 of file mmw_per4ft.c.
xdc_Void xdc_runtime_Startup_reset__I (void)
Definition at line 2121 of file mmw_per4ft.c.
Referenced by xdc_runtime_Startup_exec__I().
xdc_Bool xdc_runtime_SysStd_Module__startupDone__S (void)
Definition at line 14102 of file mmw_per4ft.c.
Referenced by xdc_runtime_System_SupportProxy_Module__startupDone__S().
xdc_Int xdc_runtime_System_aprintf__E (xdc_CString fmt, ...)
Definition at line 8390 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_aprintf_va__E (xdc_CString fmt, va_list __va)
Definition at line 8384 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_asprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 8426 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_asprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 8420 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_System_Module__startupDone__F (void)
Definition at line 2015 of file mmw_per4ft.c.
References ti_sysbios_knl_Clock_Module__startupDone__F(), and xdc_runtime_Startup_Module__state__V.
Referenced by xdc_runtime_LoggerBuf_Module__startupDone__F(), and xdc_runtime_System_Module__startupDone__S().
xdc_Bool xdc_runtime_System_Module__startupDone__S (void)
Definition at line 14114 of file mmw_per4ft.c.
References xdc_runtime_System_Module__startupDone__F().
xdc_runtime_System_Module_GateProxy_Handle xdc_runtime_System_Module_GateProxy_create (const xdc_runtime_System_Module_GateProxy_Params * prms, xdc_runtime_Error_Block * eb)
Definition at line 9255 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_create().
void xdc_runtime_System_Module_GateProxy_delete (xdc_runtime_System_Module_GateProxy_Handle * instp)
Definition at line 9261 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Object__delete__S().
xdc_IArg xdc_runtime_System_Module_GateProxy_enter__E (xdc_runtime_System_Module_GateProxy_Handle __inst)
Definition at line 9285 of file mmw_per4ft.c.
xdc_runtime_Types_Label* xdc_runtime_System_Module_GateProxy_Handle__label__S (xdc_Ptr obj, xdc_runtime_Types_Label * lab)
Definition at line 9273 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Handle__label__S().
xdc_Void xdc_runtime_System_Module_GateProxy_leave__E (xdc_runtime_System_Module_GateProxy_Handle __inst, xdc_IArg key)
Definition at line 9291 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_System_Module_GateProxy_Module__startupDone__S (void)
Definition at line 9249 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__startupDone__S().
void xdc_runtime_System_Module_GateProxy_Params__init__S (xdc_Ptr dst, const void * src, xdc_SizeT psz, xdc_SizeT isz)
Definition at line 9267 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Params__init__S().
xdc_Bool xdc_runtime_System_Module_GateProxy_Proxy__abstract__S (void)
Definition at line 14229 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_System_Module_GateProxy_Proxy__delegate__S (void)
Definition at line 14233 of file mmw_per4ft.c.
References ti_sysbios_gates_GateHwi_Module__FXNS__C.
xdc_Bool xdc_runtime_System_Module_GateProxy_query__E (xdc_Int qual)
Definition at line 9279 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_Module_startup__E (xdc_Int)
xdc_Int xdc_runtime_System_printf__E (xdc_CString fmt, ...)
Definition at line 8372 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_printf_va__E (xdc_CString fmt, va_list __va)
Definition at line 8366 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_printfExtend__I (xdc_Char ** pbuf, xdc_CString * pfmt, xdc_VaList * pva, xdc_runtime_System_ParseData * parse)
Definition at line 2150 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_snprintf__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, ...)
Definition at line 8444 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_snprintf_va__E (xdc_Char buf[], xdc_SizeT n, xdc_CString fmt, va_list __va)
Definition at line 8438 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_sprintf__E (xdc_Char buf[], xdc_CString fmt, ...)
Definition at line 8408 of file mmw_per4ft.c.
xdc_Int xdc_runtime_System_sprintf_va__E (xdc_Char buf[], xdc_CString fmt, va_list __va)
Definition at line 8402 of file mmw_per4ft.c.
xdc_Void xdc_runtime_System_SupportProxy_abort__E (xdc_CString str)
Definition at line 9310 of file mmw_per4ft.c.
xdc_Void xdc_runtime_System_SupportProxy_exit__E (xdc_Int stat)
Definition at line 9316 of file mmw_per4ft.c.
xdc_Void xdc_runtime_System_SupportProxy_flush__E (void)
Definition at line 9322 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_System_SupportProxy_Module__startupDone__S (void)
Definition at line 9304 of file mmw_per4ft.c.
References xdc_runtime_SysStd_Module__startupDone__S().
xdc_Bool xdc_runtime_System_SupportProxy_Proxy__abstract__S (void)
Definition at line 14245 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_System_SupportProxy_Proxy__delegate__S (void)
Definition at line 14249 of file mmw_per4ft.c.
References xdc_runtime_SysStd_Module__FXNS__C.
xdc_Void xdc_runtime_System_SupportProxy_putch__E (xdc_Char ch)
Definition at line 9328 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_System_SupportProxy_ready__E (void)
Definition at line 9334 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Text_Module__startupDone__S (void)
Definition at line 14260 of file mmw_per4ft.c.
void xdc_runtime_Text_visitRope__I (xdc_runtime_Text_RopeId rope, xdc_Fxn visFxn, xdc_Ptr visState)
Definition at line 2310 of file mmw_per4ft.c.
References ti_sysbios_BIOS_atExitFunc__I(), ti_sysbios_BIOS_registerRTSLock(), and ti_sysbios_timers_rti_Timer_startup__E().
xdc_Bool xdc_runtime_Timestamp_Module__startupDone__S (void)
Definition at line 14272 of file mmw_per4ft.c.
xdc_Bits32 xdc_runtime_Timestamp_SupportProxy_get32__E (void)
Definition at line 9353 of file mmw_per4ft.c.
xdc_Void xdc_runtime_Timestamp_SupportProxy_get64__E (xdc_runtime_Types_Timestamp64 * result)
Definition at line 9359 of file mmw_per4ft.c.
xdc_Void xdc_runtime_Timestamp_SupportProxy_getFreq__E (xdc_runtime_Types_FreqHz * freq)
Definition at line 9365 of file mmw_per4ft.c.
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Module__startupDone__S (void)
Definition at line 9347 of file mmw_per4ft.c.
References ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__S().
xdc_Bool xdc_runtime_Timestamp_SupportProxy_Proxy__abstract__S (void)
Definition at line 14296 of file mmw_per4ft.c.
xdc_CPtr xdc_runtime_Timestamp_SupportProxy_Proxy__delegate__S (void)
Definition at line 14300 of file mmw_per4ft.c.
References __xdc__init().
xdc_Bool xdc_runtime_TimestampNull_Module__startupDone__S (void)
Definition at line 14284 of file mmw_per4ft.c.
Variable Documentation
void* __TI_STACK_BASE
void* __TI_STACK_SIZE
__FAR__ int(* volatile __xdc__init__addr) (void) = &__xdc__init
Definition at line 14320 of file mmw_per4ft.c.
const ti_sysbios_heaps_HeapMem_Handle heap0 = (ti_sysbios_heaps_HeapMem_Handle)((ti_sysbios_heaps_HeapMem_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0])
Definition at line 14336 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_clockEnabled ti_sysbios_BIOS_clockEnabled__C = 1
Definition at line 2918 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_cpuFreq ti_sysbios_BIOS_cpuFreq__C
Initial value:
= {
    (xdc_Bits32)0x0,
    (xdc_Bits32)0xbebc200,
}
Definition at line 2899 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_defaultKernelHeapInstance ti_sysbios_BIOS_defaultKernelHeapInstance__C = 0
Definition at line 2922 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_heapSection ti_sysbios_BIOS_heapSection__C = 0
Definition at line 2938 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_heapSize ti_sysbios_BIOS_heapSize__C = (xdc_SizeT)0x1000
Definition at line 2934 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_heapTrackEnabled ti_sysbios_BIOS_heapTrackEnabled__C = 0
Definition at line 2942 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_installedErrorHook ti_sysbios_BIOS_installedErrorHook__C = ((CT__ti_sysbios_BIOS_installedErrorHook)((xdc_Fxn)xdc_runtime_Error_print__E))
Definition at line 2954 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_kernelHeapSection ti_sysbios_BIOS_kernelHeapSection__C = ".kernel_heap"
Definition at line 2930 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_kernelHeapSize ti_sysbios_BIOS_kernelHeapSize__C = (xdc_SizeT)0x1000
Definition at line 2926 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsEnabled ti_sysbios_BIOS_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2823 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsIncluded ti_sysbios_BIOS_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2827 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__diagsMask ti_sysbios_BIOS_Module__diagsMask__C = ((CT__ti_sysbios_BIOS_Module__diagsMask)0)
Definition at line 2831 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__gateObj ti_sysbios_BIOS_Module__gateObj__C = ((CT__ti_sysbios_BIOS_Module__gateObj)0)
Definition at line 2835 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__gatePrms ti_sysbios_BIOS_Module__gatePrms__C = ((CT__ti_sysbios_BIOS_Module__gatePrms)0)
Definition at line 2839 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__id ti_sysbios_BIOS_Module__id__C = (xdc_Bits16)0x1b
Definition at line 2843 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerDefined ti_sysbios_BIOS_Module__loggerDefined__C = 0
Definition at line 2847 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn0 ti_sysbios_BIOS_Module__loggerFxn0__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn0)0)
Definition at line 2855 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn1 ti_sysbios_BIOS_Module__loggerFxn1__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn1)0)
Definition at line 2859 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn2 ti_sysbios_BIOS_Module__loggerFxn2__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn2)0)
Definition at line 2863 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn4 ti_sysbios_BIOS_Module__loggerFxn4__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn4)0)
Definition at line 2867 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerFxn8 ti_sysbios_BIOS_Module__loggerFxn8__C = ((CT__ti_sysbios_BIOS_Module__loggerFxn8)0)
Definition at line 2871 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Module__loggerObj ti_sysbios_BIOS_Module__loggerObj__C = ((CT__ti_sysbios_BIOS_Module__loggerObj)0)
Definition at line 2851 of file mmw_per4ft.c.
ti_sysbios_BIOS_Module_State__ ti_sysbios_BIOS_Module__state__V
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
    (xdc_UInt)0x0,
    ((xdc_IArg)(0x0)),
    (ti_sysbios_BIOS_RtsGateProxy_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[1],
    ti_sysbios_BIOS_ThreadType_Main,
    ((void*)0),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_BIOS_startFunc)),
    ((xdc_Void(*)(xdc_Int))((xdc_Fxn)ti_sysbios_BIOS_exitFunc)),
}
Definition at line 1135 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_rtsLock(), and ti_sysbios_BIOS_rtsUnlock().
__FAR__ const CT__ti_sysbios_BIOS_mpeEnabled ti_sysbios_BIOS_mpeEnabled__C = 0
Definition at line 2895 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Object__count ti_sysbios_BIOS_Object__count__C = 0
Definition at line 2875 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Object__heap ti_sysbios_BIOS_Object__heap__C = 0
Definition at line 2879 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Object__sizeof ti_sysbios_BIOS_Object__sizeof__C = 0
Definition at line 2883 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_Object__table ti_sysbios_BIOS_Object__table__C = 0
Definition at line 2887 of file mmw_per4ft.c.
ti_sysbios_BIOS_RtsGateProxy_Module__ ti_sysbios_BIOS_RtsGateProxy_Module__root__V
__FAR__ const CT__ti_sysbios_BIOS_runtimeCreatesEnabled ti_sysbios_BIOS_runtimeCreatesEnabled__C = 1
Definition at line 2906 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_setupSecureContext ti_sysbios_BIOS_setupSecureContext__C = 0
Definition at line 2946 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_smpEnabled ti_sysbios_BIOS_smpEnabled__C = 0
Definition at line 2891 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_swiEnabled ti_sysbios_BIOS_swiEnabled__C = 0
Definition at line 2914 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_taskEnabled ti_sysbios_BIOS_taskEnabled__C = 1
Definition at line 2910 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_BIOS_useSK ti_sysbios_BIOS_useSK__C = 0
Definition at line 2950 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsEnabled ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 3137 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsIncluded ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 3141 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__diagsMask)0)
Definition at line 3145 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gateObj)0)
Definition at line 3149 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__gatePrms)0)
Definition at line 3153 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__id ti_sysbios_family_arm_a15_TimestampProvider_Module__id__C = (xdc_Bits16)0x39
Definition at line 3157 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerDefined ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerDefined__C = 0
Definition at line 3161 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn0)0)
Definition at line 3169 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn1)0)
Definition at line 3173 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn2)0)
Definition at line 3177 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn4)0)
Definition at line 3181 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8 ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerFxn8)0)
Definition at line 3185 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_a15_TimestampProvider_Module__loggerObj)0)
Definition at line 3165 of file mmw_per4ft.c.
ti_sysbios_family_arm_a15_TimestampProvider_Module_State__ ti_sysbios_family_arm_a15_TimestampProvider_Module__state__V
Initial value:
= {
    (xdc_UInt32)0x0,
}
Definition at line 1163 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__count ti_sysbios_family_arm_a15_TimestampProvider_Object__count__C = 0
Definition at line 3189 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__heap ti_sysbios_family_arm_a15_TimestampProvider_Object__heap__C = 0
Definition at line 3193 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__sizeof ti_sysbios_family_arm_a15_TimestampProvider_Object__sizeof__C = 0
Definition at line 3197 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_a15_TimestampProvider_Object__table ti_sysbios_family_arm_a15_TimestampProvider_Object__table__C = 0
Definition at line 3201 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_dataAbort ti_sysbios_family_arm_exc_Exception_E_dataAbort__C = (((xdc_runtime_Error_Id)26) << 16 | 0)
Definition at line 3334 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_prefetchAbort ti_sysbios_family_arm_exc_Exception_E_prefetchAbort__C = (((xdc_runtime_Error_Id)25) << 16 | 0)
Definition at line 3330 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_swi ti_sysbios_family_arm_exc_Exception_E_swi__C = (((xdc_runtime_Error_Id)24) << 16 | 0)
Definition at line 3326 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction ti_sysbios_family_arm_exc_Exception_E_undefinedInstruction__C = (((xdc_runtime_Error_Id)27) << 16 | 0)
Definition at line 3338 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_enableDecode ti_sysbios_family_arm_exc_Exception_enableDecode__C = 1
Definition at line 3342 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_excHookFunc ti_sysbios_family_arm_exc_Exception_excHookFunc__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFunc)0)
Definition at line 3346 of file mmw_per4ft.c.
const __T1_ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__A
Initial value:
= {
    ((xdc_Void(*)(ti_sysbios_family_arm_exc_Exception_ExcContext*))0),
}
Definition at line 1209 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs ti_sysbios_family_arm_exc_Exception_excHookFuncs__C = ((CT__ti_sysbios_family_arm_exc_Exception_excHookFuncs)ti_sysbios_family_arm_exc_Exception_excHookFuncs__A)
Definition at line 3350 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled ti_sysbios_family_arm_exc_Exception_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3258 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded ti_sysbios_family_arm_exc_Exception_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3262 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask ti_sysbios_family_arm_exc_Exception_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__diagsMask)0)
Definition at line 3266 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj ti_sysbios_family_arm_exc_Exception_Module__gateObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gateObj)0)
Definition at line 3270 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms ti_sysbios_family_arm_exc_Exception_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__gatePrms)0)
Definition at line 3274 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__id ti_sysbios_family_arm_exc_Exception_Module__id__C = (xdc_Bits16)0x2b
Definition at line 3278 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerDefined ti_sysbios_family_arm_exc_Exception_Module__loggerDefined__C = 0
Definition at line 3282 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn0)0)
Definition at line 3290 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn1)0)
Definition at line 3294 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn2)0)
Definition at line 3298 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn4)0)
Definition at line 3302 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8 ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerFxn8)0)
Definition at line 3306 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj ti_sysbios_family_arm_exc_Exception_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_exc_Exception_Module__loggerObj)0)
Definition at line 3286 of file mmw_per4ft.c.
ti_sysbios_family_arm_exc_Exception_Module_State__ ti_sysbios_family_arm_exc_Exception_Module__state__V
Initial value:
= {
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A),
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A),
    (xdc_SizeT)0x1000,
}
Definition at line 1206 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excActive ti_sysbios_family_arm_exc_Exception_Module_State_0_excActive__A
Initial value:
= {
    0,
}
Definition at line 1180 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excContext ti_sysbios_family_arm_exc_Exception_Module_State_0_excContext__A
Initial value:
= {
    ((ti_sysbios_family_arm_exc_Exception_ExcContext*)0),
}
Definition at line 1183 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A
Definition at line 1192 of file mmw_per4ft.c.
__T2_ti_sysbios_family_arm_exc_Exception_Module_State__excStack ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack__A
Initial value:
= {
    ((void*)ti_sysbios_family_arm_exc_Exception_Module_State_0_excStack_0__A),
}
Definition at line 1203 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_exc_Exception_Module_State__excStackBuffers ti_sysbios_family_arm_exc_Exception_Module_State_0_excStackBuffers__A
Initial value:
= {
    ((xdc_Ptr)0),
}
Definition at line 1186 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__count ti_sysbios_family_arm_exc_Exception_Object__count__C = 0
Definition at line 3310 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__heap ti_sysbios_family_arm_exc_Exception_Object__heap__C = 0
Definition at line 3314 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__sizeof ti_sysbios_family_arm_exc_Exception_Object__sizeof__C = 0
Definition at line 3318 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_exc_Exception_Object__table ti_sysbios_family_arm_exc_Exception_Object__table__C = 0
Definition at line 3322 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 2968 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 2972 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__diagsMask)0)
Definition at line 2976 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gateObj)0)
Definition at line 2980 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__gatePrms)0)
Definition at line 2984 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__id ti_sysbios_family_arm_IntrinsicsSupport_Module__id__C = (xdc_Bits16)0x19
Definition at line 2988 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerDefined__C = 0
Definition at line 2992 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn0)0)
Definition at line 3000 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn1)0)
Definition at line 3004 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn2)0)
Definition at line 3008 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn4)0)
Definition at line 3012 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8 ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerFxn8)0)
Definition at line 3016 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_IntrinsicsSupport_Module__loggerObj)0)
Definition at line 2996 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__count ti_sysbios_family_arm_IntrinsicsSupport_Object__count__C = 0
Definition at line 3020 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__heap ti_sysbios_family_arm_IntrinsicsSupport_Object__heap__C = 0
Definition at line 3024 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof ti_sysbios_family_arm_IntrinsicsSupport_Object__sizeof__C = 0
Definition at line 3028 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_IntrinsicsSupport_Object__table ti_sysbios_family_arm_IntrinsicsSupport_Object__table__C = 0
Definition at line 3032 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_defaultStackSize ti_sysbios_family_arm_TaskSupport_defaultStackSize__C = (xdc_SizeT)0x800
Definition at line 3109 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled ti_sysbios_family_arm_TaskSupport_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3041 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded ti_sysbios_family_arm_TaskSupport_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3045 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask ti_sysbios_family_arm_TaskSupport_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__diagsMask)0)
Definition at line 3049 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj ti_sysbios_family_arm_TaskSupport_Module__gateObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gateObj)0)
Definition at line 3053 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms ti_sysbios_family_arm_TaskSupport_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__gatePrms)0)
Definition at line 3057 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__id ti_sysbios_family_arm_TaskSupport_Module__id__C = (xdc_Bits16)0x1a
Definition at line 3061 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerDefined ti_sysbios_family_arm_TaskSupport_Module__loggerDefined__C = 0
Definition at line 3065 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn0)0)
Definition at line 3073 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn1)0)
Definition at line 3077 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn2)0)
Definition at line 3081 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn4)0)
Definition at line 3085 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8 ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerFxn8)0)
Definition at line 3089 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj ti_sysbios_family_arm_TaskSupport_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_TaskSupport_Module__loggerObj)0)
Definition at line 3069 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__count ti_sysbios_family_arm_TaskSupport_Object__count__C = 0
Definition at line 3093 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__heap ti_sysbios_family_arm_TaskSupport_Object__heap__C = 0
Definition at line 3097 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__sizeof ti_sysbios_family_arm_TaskSupport_Object__sizeof__C = 0
Definition at line 3101 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_Object__table ti_sysbios_family_arm_TaskSupport_Object__table__C = 0
Definition at line 3105 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_TaskSupport_stackAlignment ti_sysbios_family_arm_TaskSupport_stackAlignment__C = (xdc_UInt)0x8
Definition at line 3113 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_A_badIntNum ti_sysbios_family_arm_v7a_Pmu_A_badIntNum__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 3448 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_A_invalidCounterId ti_sysbios_family_arm_v7a_Pmu_A_invalidCounterId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 3452 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_intNum ti_sysbios_family_arm_v7a_Pmu_intNum__C = (xdc_UInt)(-0x0 - 1)
Definition at line 3444 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3376 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3380 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask)0)
Definition at line 3384 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__gateObj ti_sysbios_family_arm_v7a_Pmu_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gateObj)0)
Definition at line 3388 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms)0)
Definition at line 3392 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__id ti_sysbios_family_arm_v7a_Pmu_Module__id__C = (xdc_Bits16)0x33
Definition at line 3396 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined__C = 0
Definition at line 3400 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0)0)
Definition at line 3408 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1)0)
Definition at line 3412 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2)0)
Definition at line 3416 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4)0)
Definition at line 3420 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8)0)
Definition at line 3424 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj)0)
Definition at line 3404 of file mmw_per4ft.c.
ti_sysbios_family_arm_v7a_Pmu_Module_State__ ti_sysbios_family_arm_v7a_Pmu_Module__state__V
Initial value:
= {
    (xdc_UInt)0x0,
    0,
    ((xdc_Void(*)(xdc_UArg))0),
}
Definition at line 1224 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__count ti_sysbios_family_arm_v7a_Pmu_Object__count__C = 0
Definition at line 3428 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__heap ti_sysbios_family_arm_v7a_Pmu_Object__heap__C = 0
Definition at line 3432 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__sizeof ti_sysbios_family_arm_v7a_Pmu_Object__sizeof__C = 0
Definition at line 3436 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7a_Pmu_Object__table ti_sysbios_family_arm_v7a_Pmu_Object__table__C = 0
Definition at line 3440 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds ti_sysbios_family_arm_v7r_tms570_Core_E_mismatchedIds__C = (((xdc_runtime_Error_Id)33) << 16 | 0)
Definition at line 3533 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_id ti_sysbios_family_arm_v7r_tms570_Core_id__C = (xdc_UInt)0x0
Definition at line 3537 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3461 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3465 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__diagsMask)0)
Definition at line 3469 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gateObj)0)
Definition at line 3473 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__gatePrms)0)
Definition at line 3477 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__id ti_sysbios_family_arm_v7r_tms570_Core_Module__id__C = (xdc_Bits16)0x37
Definition at line 3481 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerDefined__C = 0
Definition at line 3485 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn0)0)
Definition at line 3493 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn1)0)
Definition at line 3497 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn2)0)
Definition at line 3501 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn4)0)
Definition at line 3505 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8 ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerFxn8)0)
Definition at line 3509 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_tms570_Core_Module__loggerObj)0)
Definition at line 3489 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_numCores ti_sysbios_family_arm_v7r_tms570_Core_numCores__C = (xdc_UInt)0x1
Definition at line 3529 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__count ti_sysbios_family_arm_v7r_tms570_Core_Object__count__C = 0
Definition at line 3513 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__heap ti_sysbios_family_arm_v7r_tms570_Core_Object__heap__C = 0
Definition at line 3517 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof ti_sysbios_family_arm_v7r_tms570_Core_Object__sizeof__C = 0
Definition at line 3521 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_tms570_Core_Object__table ti_sysbios_family_arm_v7r_tms570_Core_Object__table__C = 0
Definition at line 3525 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId ti_sysbios_family_arm_v7r_vim_Hwi_A_badChannelId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4020 of file mmw_per4ft.c.
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A
Definition at line 1288 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_channelMap)ti_sysbios_family_arm_v7r_vim_Hwi_channelMap__A)
Definition at line 4052 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core0VectorTableAddress)(0x0))
Definition at line 3996 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_core1VectorTableAddress)(0x0))
Definition at line 4000 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 3976 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 3988 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherSwiSupport__C = 0
Definition at line 3980 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport ti_sysbios_family_arm_v7r_vim_Hwi_dispatcherTaskSupport__C = 1
Definition at line 3984 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined ti_sysbios_family_arm_v7r_vim_Hwi_E_alreadyDefined__C = (((xdc_runtime_Error_Id)19) << 16 | 0)
Definition at line 4024 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum ti_sysbios_family_arm_v7r_vim_Hwi_E_badIntNum__C = (((xdc_runtime_Error_Id)20) << 16 | 0)
Definition at line 4028 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt ti_sysbios_family_arm_v7r_vim_Hwi_E_phantomInterrupt__C = (((xdc_runtime_Error_Id)23) << 16 | 0)
Definition at line 4040 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined ti_sysbios_family_arm_v7r_vim_Hwi_E_undefined__C = (((xdc_runtime_Error_Id)21) << 16 | 0)
Definition at line 4032 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption ti_sysbios_family_arm_v7r_vim_Hwi_E_unsupportedMaskingOption__C = (((xdc_runtime_Error_Id)22) << 16 | 0)
Definition at line 4036 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm ti_sysbios_family_arm_v7r_vim_Hwi_errataInitEsm__C = 1
Definition at line 4012 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_fiqStack)0)
Definition at line 4008 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_hooks ti_sysbios_family_arm_v7r_vim_Hwi_hooks__C = {0, 0}
Definition at line 4080 of file mmw_per4ft.c.
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A
Initial value:
= {
    (xdc_UInt32)0x4,
    (xdc_UInt32)0x0,
    (xdc_UInt32)0x0,
    (xdc_UInt32)0x0,
}
Definition at line 1291 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_intReqEnaSet__A)
Definition at line 4056 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_LD_end ti_sysbios_family_arm_v7r_vim_Hwi_LD_end__C = (((xdc_runtime_Log_Event)30) << 16 | 512)
Definition at line 4048 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin ti_sysbios_family_arm_v7r_vim_Hwi_LM_begin__C = (((xdc_runtime_Log_Event)29) << 16 | 768)
Definition at line 4044 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 3908 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 3912 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__diagsMask)0)
Definition at line 3916 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gateObj)0)
Definition at line 3920 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__gatePrms)0)
Definition at line 3924 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__id ti_sysbios_family_arm_v7r_vim_Hwi_Module__id__C = (xdc_Bits16)0x2a
Definition at line 3928 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerDefined__C = 0
Definition at line 3932 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn0)0)
Definition at line 3940 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn1)0)
Definition at line 3944 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn2)0)
Definition at line 3948 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn4)0)
Definition at line 3952 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8 ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerFxn8)0)
Definition at line 3956 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_Module__loggerObj)0)
Definition at line 3936 of file mmw_per4ft.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link,
    &ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link},
}
Definition at line 3567 of file mmw_per4ft.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__ ti_sysbios_family_arm_v7r_vim_Hwi_Module__state__V
Initial value:
= {
    ((xdc_Char*)0),
    ((xdc_Char*)0),
    ((xdc_Ptr)((void*)&__TI_STACK_BASE)),
    ((xdc_Ptr)((void*)&__TI_STACK_SIZE)),
    ((void*)ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A),
    (xdc_SizeT)0x800,
    ((xdc_UInt*)(0xfff82000)),
    ((void*)ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A),
    {
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
        (xdc_UInt)0xffffffff,
    },
    (xdc_UInt)0x0,
}
Definition at line 1285 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__dispatchTable ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_dispatchTable__A
Definition at line 1282 of file mmw_per4ft.c.
__T1_ti_sysbios_family_arm_v7r_vim_Hwi_Module_State__fiqStack ti_sysbios_family_arm_v7r_vim_Hwi_Module_State_0_fiqStack__A
Definition at line 1263 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS ti_sysbios_family_arm_v7r_vim_Hwi_NUM_INTERRUPTS__C = (xdc_UInt)0x80
Definition at line 3992 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__count ti_sysbios_family_arm_v7r_vim_Hwi_Object__count__C = 1
Definition at line 3960 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_family_arm_v7r_vim_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_family_arm_v7r_vim_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi___S1) - sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Params),
}
Definition at line 3545 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap ti_sysbios_family_arm_v7r_vim_Hwi_Object__heap__C = 0
Definition at line 3964 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_family_arm_v7r_vim_Hwi_Params ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_family_arm_v7r_vim_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_LOWER,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)(-0x0 - 1),
    ti_sysbios_family_arm_v7r_vim_Hwi_Type_IRQ,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 3549 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof ti_sysbios_family_arm_v7r_vim_Hwi_Object__sizeof__C = sizeof(ti_sysbios_family_arm_v7r_vim_Hwi_Object__)
Definition at line 3968 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_Object__table ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__C = ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
Definition at line 3972 of file mmw_per4ft.c.
ti_sysbios_family_arm_v7r_vim_Hwi_Object__ ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V
Initial value:
= {
    {
        0,
        ti_sysbios_family_arm_v7r_vim_Hwi_Type_IRQ,
        ((xdc_UArg)((void*)(ti_sysbios_timers_rti_Timer_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0])),
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_timers_rti_Timer_periodicStub__E)),
        (xdc_Int)0x2,
        ((xdc_UArg)0),
        ((void*)0),
        {
            (xdc_UInt)0x4,
            (xdc_UInt)0x0,
            (xdc_UInt)0x0,
            (xdc_UInt)0x0,
        },
    },
}
Definition at line 1237 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_phantomFunc)((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_phantomIntHandler__I))
Definition at line 4004 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM ti_sysbios_family_arm_v7r_vim_Hwi_resetVIM__C = 1
Definition at line 4016 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiDisable)0)
Definition at line 4064 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_swiRestoreHwi)0)
Definition at line 4068 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskDisable)((xdc_Fxn)ti_sysbios_knl_Task_disable__E))
Definition at line 4072 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_taskRestoreHwi)((xdc_Fxn)ti_sysbios_knl_Task_restoreHwi__E))
Definition at line 4076 of file mmw_per4ft.c.
const UInt32 ti_sysbios_family_arm_v7r_vim_Hwi_vectors[]
Initial value:
= {
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE59FF018),
    (UInt32)(0xE51FF1B0),
    (UInt32)(&_c_int00),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerDataAsm__I),
    (UInt32)(&ti_sysbios_family_arm_exc_Exception_excHandlerAsm__I),
    (UInt32)(&ti_sysbios_family_arm_v7r_vim_Hwi_dispatchIRQ__I)
}
Definition at line 2503 of file mmw_per4ft.c.
const __T1_ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A
Initial value:
= {
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
    (xdc_UInt32)0xffffffff,
}
Definition at line 1294 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__C = ((CT__ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet)ti_sysbios_family_arm_v7r_vim_Hwi_wakeEnaSet__A)
Definition at line 4060 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsEnabled ti_sysbios_gates_GateHwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4118 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsIncluded ti_sysbios_gates_GateHwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4122 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__diagsMask ti_sysbios_gates_GateHwi_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateHwi_Module__diagsMask)0)
Definition at line 4126 of file mmw_per4ft.c.
const ti_sysbios_gates_GateHwi_Fxns__ ti_sysbios_gates_GateHwi_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateHwi_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateHwi_query__E,
    ti_sysbios_gates_GateHwi_enter__E,
    ti_sysbios_gates_GateHwi_leave__E,
    {
        ti_sysbios_gates_GateHwi_Object__create__S,
        ti_sysbios_gates_GateHwi_Object__delete__S,
        ti_sysbios_gates_GateHwi_Handle__label__S,
        0x35,
    }
}
Definition at line 914 of file mmw_per4ft.c.
Referenced by xdc_runtime_LoggerBuf_Module_GateProxy_Proxy__delegate__S(), xdc_runtime_Main_Module_GateProxy_Proxy__delegate__S(), xdc_runtime_System_Module_GateProxy_Proxy__delegate__S(), and xdc_runtime_Timestamp_SupportProxy_getFreq__E().
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__gateObj ti_sysbios_gates_GateHwi_Module__gateObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__gateObj)0)
Definition at line 4130 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__gatePrms ti_sysbios_gates_GateHwi_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateHwi_Module__gatePrms)0)
Definition at line 4134 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__id ti_sysbios_gates_GateHwi_Module__id__C = (xdc_Bits16)0x35
Definition at line 4138 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerDefined ti_sysbios_gates_GateHwi_Module__loggerDefined__C = 0
Definition at line 4142 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0 ti_sysbios_gates_GateHwi_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn0)0)
Definition at line 4150 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1 ti_sysbios_gates_GateHwi_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn1)0)
Definition at line 4154 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2 ti_sysbios_gates_GateHwi_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn2)0)
Definition at line 4158 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4 ti_sysbios_gates_GateHwi_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn4)0)
Definition at line 4162 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8 ti_sysbios_gates_GateHwi_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerFxn8)0)
Definition at line 4166 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Module__loggerObj ti_sysbios_gates_GateHwi_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateHwi_Module__loggerObj)0)
Definition at line 4146 of file mmw_per4ft.c.
ti_sysbios_gates_GateHwi_Module__ ti_sysbios_gates_GateHwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateHwi_Module__root__V.link,
    &ti_sysbios_gates_GateHwi_Module__root__V.link},
}
Definition at line 4104 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__count ti_sysbios_gates_GateHwi_Object__count__C = 1
Definition at line 4170 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateHwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Module__FXNS__C,
    &ti_sysbios_gates_GateHwi_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateHwi___S1) - sizeof(ti_sysbios_gates_GateHwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateHwi_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateHwi_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateHwi_Params),
}
Definition at line 4088 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__heap ti_sysbios_gates_GateHwi_Object__heap__C = 0
Definition at line 4174 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_gates_GateHwi_Params ti_sysbios_gates_GateHwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateHwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateHwi_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4092 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__sizeof ti_sysbios_gates_GateHwi_Object__sizeof__C = sizeof(ti_sysbios_gates_GateHwi_Object__)
Definition at line 4178 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateHwi_Object__table ti_sysbios_gates_GateHwi_Object__table__C = ti_sysbios_gates_GateHwi_Object__table__V
Definition at line 4182 of file mmw_per4ft.c.
ti_sysbios_gates_GateHwi_Object__ ti_sysbios_gates_GateHwi_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_gates_GateHwi_Module__FXNS__C,
    },
}
Definition at line 1308 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_A_badContext ti_sysbios_gates_GateMutex_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4317 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_gates_GateMutex_Instance_State_sem__O = offsetof(ti_sysbios_gates_GateMutex_Object__,Object_field_sem)
Definition at line 1882 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsEnabled ti_sysbios_gates_GateMutex_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4249 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsIncluded ti_sysbios_gates_GateMutex_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4253 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__diagsMask ti_sysbios_gates_GateMutex_Module__diagsMask__C = ((CT__ti_sysbios_gates_GateMutex_Module__diagsMask)0)
Definition at line 4257 of file mmw_per4ft.c.
const ti_sysbios_gates_GateMutex_Fxns__ ti_sysbios_gates_GateMutex_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IGateProvider_Interface__BASE__C,
    &ti_sysbios_gates_GateMutex_Module__FXNS__C.__sfxns,
    ti_sysbios_gates_GateMutex_query__E,
    ti_sysbios_gates_GateMutex_enter__E,
    ti_sysbios_gates_GateMutex_leave__E,
    {
        ti_sysbios_gates_GateMutex_Object__create__S,
        ti_sysbios_gates_GateMutex_Object__delete__S,
        ti_sysbios_gates_GateMutex_Handle__label__S,
        0x36,
    }
}
Definition at line 935 of file mmw_per4ft.c.
Referenced by ti_sysbios_BIOS_RtsGateProxy_Proxy__delegate__S(), ti_sysbios_heaps_HeapMem_Module_GateProxy_Proxy__delegate__S(), and xdc_runtime_Timestamp_SupportProxy_getFreq__E().
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__gateObj ti_sysbios_gates_GateMutex_Module__gateObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__gateObj)0)
Definition at line 4261 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__gatePrms ti_sysbios_gates_GateMutex_Module__gatePrms__C = ((CT__ti_sysbios_gates_GateMutex_Module__gatePrms)0)
Definition at line 4265 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__id ti_sysbios_gates_GateMutex_Module__id__C = (xdc_Bits16)0x36
Definition at line 4269 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerDefined ti_sysbios_gates_GateMutex_Module__loggerDefined__C = 0
Definition at line 4273 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0 ti_sysbios_gates_GateMutex_Module__loggerFxn0__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn0)0)
Definition at line 4281 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1 ti_sysbios_gates_GateMutex_Module__loggerFxn1__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn1)0)
Definition at line 4285 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2 ti_sysbios_gates_GateMutex_Module__loggerFxn2__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn2)0)
Definition at line 4289 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4 ti_sysbios_gates_GateMutex_Module__loggerFxn4__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn4)0)
Definition at line 4293 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8 ti_sysbios_gates_GateMutex_Module__loggerFxn8__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerFxn8)0)
Definition at line 4297 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Module__loggerObj ti_sysbios_gates_GateMutex_Module__loggerObj__C = ((CT__ti_sysbios_gates_GateMutex_Module__loggerObj)0)
Definition at line 4277 of file mmw_per4ft.c.
ti_sysbios_gates_GateMutex_Module__ ti_sysbios_gates_GateMutex_Module__root__V
Initial value:
= {
    {&ti_sysbios_gates_GateMutex_Module__root__V.link,
    &ti_sysbios_gates_GateMutex_Module__root__V.link},
}
Definition at line 4206 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__count ti_sysbios_gates_GateMutex_Object__count__C = 2
Definition at line 4301 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_gates_GateMutex_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Module__FXNS__C,
    &ti_sysbios_gates_GateMutex_Module__root__V.link,
    sizeof(ti_sysbios_gates_GateMutex___S1) - sizeof(ti_sysbios_gates_GateMutex_Object2__),
    0,
    0,
    sizeof(ti_sysbios_gates_GateMutex_Object2__),
    (xdc_CPtr)&ti_sysbios_gates_GateMutex_Object__PARAMS__C,
    sizeof(ti_sysbios_gates_GateMutex_Params),
}
Definition at line 4190 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__heap ti_sysbios_gates_GateMutex_Object__heap__C = 0
Definition at line 4305 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_gates_GateMutex_Params ti_sysbios_gates_GateMutex_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_gates_GateMutex_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_gates_GateMutex_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4194 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__sizeof ti_sysbios_gates_GateMutex_Object__sizeof__C = sizeof(ti_sysbios_gates_GateMutex_Object__)
Definition at line 4309 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_gates_GateMutex_Object__table ti_sysbios_gates_GateMutex_Object__table__C = ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 4313 of file mmw_per4ft.c.
ti_sysbios_gates_GateMutex_Object__ ti_sysbios_gates_GateMutex_Object__table__V
Definition at line 1316 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsEnabled ti_sysbios_hal_Cache_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4326 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsIncluded ti_sysbios_hal_Cache_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4330 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__diagsMask ti_sysbios_hal_Cache_Module__diagsMask__C = ((CT__ti_sysbios_hal_Cache_Module__diagsMask)0)
Definition at line 4334 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__gateObj ti_sysbios_hal_Cache_Module__gateObj__C = ((CT__ti_sysbios_hal_Cache_Module__gateObj)0)
Definition at line 4338 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__gatePrms ti_sysbios_hal_Cache_Module__gatePrms__C = ((CT__ti_sysbios_hal_Cache_Module__gatePrms)0)
Definition at line 4342 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__id ti_sysbios_hal_Cache_Module__id__C = (xdc_Bits16)0x2c
Definition at line 4346 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerDefined ti_sysbios_hal_Cache_Module__loggerDefined__C = 0
Definition at line 4350 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn0 ti_sysbios_hal_Cache_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn0)0)
Definition at line 4358 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn1 ti_sysbios_hal_Cache_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn1)0)
Definition at line 4362 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn2 ti_sysbios_hal_Cache_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn2)0)
Definition at line 4366 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn4 ti_sysbios_hal_Cache_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn4)0)
Definition at line 4370 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerFxn8 ti_sysbios_hal_Cache_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Cache_Module__loggerFxn8)0)
Definition at line 4374 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Module__loggerObj ti_sysbios_hal_Cache_Module__loggerObj__C = ((CT__ti_sysbios_hal_Cache_Module__loggerObj)0)
Definition at line 4354 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Object__count ti_sysbios_hal_Cache_Object__count__C = 0
Definition at line 4378 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Object__heap ti_sysbios_hal_Cache_Object__heap__C = 0
Definition at line 4382 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Object__sizeof ti_sysbios_hal_Cache_Object__sizeof__C = 0
Definition at line 4386 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Cache_Object__table ti_sysbios_hal_Cache_Object__table__C = 0
Definition at line 4390 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsEnabled ti_sysbios_hal_CacheNull_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4399 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsIncluded ti_sysbios_hal_CacheNull_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4403 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__diagsMask ti_sysbios_hal_CacheNull_Module__diagsMask__C = ((CT__ti_sysbios_hal_CacheNull_Module__diagsMask)0)
Definition at line 4407 of file mmw_per4ft.c.
const ti_sysbios_hal_CacheNull_Fxns__ ti_sysbios_hal_CacheNull_Module__FXNS__C
Initial value:
= {
    &ti_sysbios_interfaces_ICache_Interface__BASE__C,
    &ti_sysbios_hal_CacheNull_Module__FXNS__C.__sfxns,
    ti_sysbios_hal_CacheNull_enable__E,
    ti_sysbios_hal_CacheNull_disable__E,
    ti_sysbios_hal_CacheNull_inv__E,
    ti_sysbios_hal_CacheNull_wb__E,
    ti_sysbios_hal_CacheNull_wbInv__E,
    ti_sysbios_hal_CacheNull_wbAll__E,
    ti_sysbios_hal_CacheNull_wbInvAll__E,
    ti_sysbios_hal_CacheNull_wait__E,
    {
        NULL,
        NULL,
        NULL,
        0x2d,
    }
}
Definition at line 956 of file mmw_per4ft.c.
Referenced by ti_sysbios_hal_Cache_CacheProxy_Proxy__delegate__S().
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__gateObj ti_sysbios_hal_CacheNull_Module__gateObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__gateObj)0)
Definition at line 4411 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__gatePrms ti_sysbios_hal_CacheNull_Module__gatePrms__C = ((CT__ti_sysbios_hal_CacheNull_Module__gatePrms)0)
Definition at line 4415 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__id ti_sysbios_hal_CacheNull_Module__id__C = (xdc_Bits16)0x2d
Definition at line 4419 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerDefined ti_sysbios_hal_CacheNull_Module__loggerDefined__C = 0
Definition at line 4423 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0 ti_sysbios_hal_CacheNull_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn0)0)
Definition at line 4431 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1 ti_sysbios_hal_CacheNull_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn1)0)
Definition at line 4435 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2 ti_sysbios_hal_CacheNull_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn2)0)
Definition at line 4439 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4 ti_sysbios_hal_CacheNull_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn4)0)
Definition at line 4443 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8 ti_sysbios_hal_CacheNull_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerFxn8)0)
Definition at line 4447 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Module__loggerObj ti_sysbios_hal_CacheNull_Module__loggerObj__C = ((CT__ti_sysbios_hal_CacheNull_Module__loggerObj)0)
Definition at line 4427 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__count ti_sysbios_hal_CacheNull_Object__count__C = 0
Definition at line 4451 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__heap ti_sysbios_hal_CacheNull_Object__heap__C = 0
Definition at line 4455 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__sizeof ti_sysbios_hal_CacheNull_Object__sizeof__C = 0
Definition at line 4459 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_CacheNull_Object__table ti_sysbios_hal_CacheNull_Object__table__C = 0
Definition at line 4463 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsEnabled ti_sysbios_hal_Core_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4477 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsIncluded ti_sysbios_hal_Core_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4481 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__diagsMask ti_sysbios_hal_Core_Module__diagsMask__C = ((CT__ti_sysbios_hal_Core_Module__diagsMask)0)
Definition at line 4485 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__gateObj ti_sysbios_hal_Core_Module__gateObj__C = ((CT__ti_sysbios_hal_Core_Module__gateObj)0)
Definition at line 4489 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__gatePrms ti_sysbios_hal_Core_Module__gatePrms__C = ((CT__ti_sysbios_hal_Core_Module__gatePrms)0)
Definition at line 4493 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__id ti_sysbios_hal_Core_Module__id__C = (xdc_Bits16)0x2e
Definition at line 4497 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerDefined ti_sysbios_hal_Core_Module__loggerDefined__C = 0
Definition at line 4501 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn0 ti_sysbios_hal_Core_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn0)0)
Definition at line 4509 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn1 ti_sysbios_hal_Core_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn1)0)
Definition at line 4513 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn2 ti_sysbios_hal_Core_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn2)0)
Definition at line 4517 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn4 ti_sysbios_hal_Core_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn4)0)
Definition at line 4521 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerFxn8 ti_sysbios_hal_Core_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Core_Module__loggerFxn8)0)
Definition at line 4525 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Module__loggerObj ti_sysbios_hal_Core_Module__loggerObj__C = ((CT__ti_sysbios_hal_Core_Module__loggerObj)0)
Definition at line 4505 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_numCores ti_sysbios_hal_Core_numCores__C = (xdc_UInt)0x1
Definition at line 4545 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Object__count ti_sysbios_hal_Core_Object__count__C = 0
Definition at line 4529 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Object__heap ti_sysbios_hal_Core_Object__heap__C = 0
Definition at line 4533 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Object__sizeof ti_sysbios_hal_Core_Object__sizeof__C = 0
Definition at line 4537 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Core_Object__table ti_sysbios_hal_Core_Object__table__C = 0
Definition at line 4541 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport ti_sysbios_hal_Hwi_dispatcherAutoNestingSupport__C = 1
Definition at line 4662 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport ti_sysbios_hal_Hwi_dispatcherIrpTrackingSupport__C = 1
Definition at line 4674 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherSwiSupport ti_sysbios_hal_Hwi_dispatcherSwiSupport__C = 0
Definition at line 4666 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_dispatcherTaskSupport ti_sysbios_hal_Hwi_dispatcherTaskSupport__C = 1
Definition at line 4670 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_E_stackOverflow ti_sysbios_hal_Hwi_E_stackOverflow__C = (((xdc_runtime_Error_Id)28) << 16 | 0)
Definition at line 4678 of file mmw_per4ft.c.
ti_sysbios_hal_Hwi_HwiProxy_Module__ ti_sysbios_hal_Hwi_HwiProxy_Module__root__V
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsEnabled ti_sysbios_hal_Hwi_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4594 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsIncluded ti_sysbios_hal_Hwi_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4598 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__diagsMask ti_sysbios_hal_Hwi_Module__diagsMask__C = ((CT__ti_sysbios_hal_Hwi_Module__diagsMask)0)
Definition at line 4602 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__gateObj ti_sysbios_hal_Hwi_Module__gateObj__C = ((CT__ti_sysbios_hal_Hwi_Module__gateObj)0)
Definition at line 4606 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__gatePrms ti_sysbios_hal_Hwi_Module__gatePrms__C = ((CT__ti_sysbios_hal_Hwi_Module__gatePrms)0)
Definition at line 4610 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__id ti_sysbios_hal_Hwi_Module__id__C = (xdc_Bits16)0x2f
Definition at line 4614 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerDefined ti_sysbios_hal_Hwi_Module__loggerDefined__C = 0
Definition at line 4618 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn0 ti_sysbios_hal_Hwi_Module__loggerFxn0__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn0)0)
Definition at line 4626 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn1 ti_sysbios_hal_Hwi_Module__loggerFxn1__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn1)0)
Definition at line 4630 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn2 ti_sysbios_hal_Hwi_Module__loggerFxn2__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn2)0)
Definition at line 4634 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn4 ti_sysbios_hal_Hwi_Module__loggerFxn4__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn4)0)
Definition at line 4638 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerFxn8 ti_sysbios_hal_Hwi_Module__loggerFxn8__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerFxn8)0)
Definition at line 4642 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Module__loggerObj ti_sysbios_hal_Hwi_Module__loggerObj__C = ((CT__ti_sysbios_hal_Hwi_Module__loggerObj)0)
Definition at line 4622 of file mmw_per4ft.c.
ti_sysbios_hal_Hwi_Module__ ti_sysbios_hal_Hwi_Module__root__V
Initial value:
= {
    {&ti_sysbios_hal_Hwi_Module__root__V.link,
    &ti_sysbios_hal_Hwi_Module__root__V.link},
}
Definition at line 4579 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__count ti_sysbios_hal_Hwi_Object__count__C = 1
Definition at line 4646 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_hal_Hwi_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_hal_Hwi_Module__root__V.link,
    sizeof(ti_sysbios_hal_Hwi___S1) - sizeof(ti_sysbios_hal_Hwi_Object2__),
    0,
    0,
    sizeof(ti_sysbios_hal_Hwi_Object2__),
    (xdc_CPtr)&ti_sysbios_hal_Hwi_Object__PARAMS__C,
    sizeof(ti_sysbios_hal_Hwi_Params),
}
Definition at line 4558 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__heap ti_sysbios_hal_Hwi_Object__heap__C = 0
Definition at line 4650 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_hal_Hwi_Params ti_sysbios_hal_Hwi_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_hal_Hwi_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_hal_Hwi_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_IHwi_MaskingOption_LOWER,
    ((xdc_UArg)(0x0)),
    1,
    (xdc_Int)(-0x0 - 1),
    (xdc_Int)(-0x0 - 1),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4562 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__sizeof ti_sysbios_hal_Hwi_Object__sizeof__C = sizeof(ti_sysbios_hal_Hwi_Object__)
Definition at line 4654 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_hal_Hwi_Object__table ti_sysbios_hal_Hwi_Object__table__C = ti_sysbios_hal_Hwi_Object__table__V
Definition at line 4658 of file mmw_per4ft.c.
ti_sysbios_hal_Hwi_Object__ ti_sysbios_hal_Hwi_Object__table__V
Initial value:
= {
    {
        0,
        (ti_sysbios_hal_Hwi_HwiProxy_Handle)&ti_sysbios_family_arm_v7r_vim_Hwi_Object__table__V[0],
    },
}
Definition at line 1349 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_bufAlign ti_sysbios_heaps_HeapBuf_A_bufAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4806 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidAlign ti_sysbios_heaps_HeapBuf_A_invalidAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4810 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidBlockSize ti_sysbios_heaps_HeapBuf_A_invalidBlockSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4818 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidBufSize ti_sysbios_heaps_HeapBuf_A_invalidBufSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4830 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidFree ti_sysbios_heaps_HeapBuf_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4838 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign ti_sysbios_heaps_HeapBuf_A_invalidRequestedAlign__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4814 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_noBlocksToFree ti_sysbios_heaps_HeapBuf_A_noBlocksToFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4834 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_nullBuf ti_sysbios_heaps_HeapBuf_A_nullBuf__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4802 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_zeroBlocks ti_sysbios_heaps_HeapBuf_A_zeroBlocks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4822 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_A_zeroBufSize ti_sysbios_heaps_HeapBuf_A_zeroBufSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4826 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_E_size ti_sysbios_heaps_HeapBuf_E_size__C = (((xdc_runtime_Error_Id)16) << 16 | 0)
Definition at line 4842 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_heaps_HeapBuf_Instance_State_freeList__O = offsetof(ti_sysbios_heaps_HeapBuf_Object__,Object_field_freeList)
Definition at line 1890 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsEnabled ti_sysbios_heaps_HeapBuf_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4734 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsIncluded ti_sysbios_heaps_HeapBuf_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4738 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask ti_sysbios_heaps_HeapBuf_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__diagsMask)0)
Definition at line 4742 of file mmw_per4ft.c.
const ti_sysbios_heaps_HeapBuf_Fxns__ ti_sysbios_heaps_HeapBuf_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IHeap_Interface__BASE__C,
    &ti_sysbios_heaps_HeapBuf_Module__FXNS__C.__sfxns,
    ti_sysbios_heaps_HeapBuf_alloc__E,
    ti_sysbios_heaps_HeapBuf_free__E,
    ti_sysbios_heaps_HeapBuf_isBlocking__E,
    ti_sysbios_heaps_HeapBuf_getStats__E,
    {
        ti_sysbios_heaps_HeapBuf_Object__create__S,
        ti_sysbios_heaps_HeapBuf_Object__delete__S,
        ti_sysbios_heaps_HeapBuf_Handle__label__S,
        0x27,
    }
}
Definition at line 982 of file mmw_per4ft.c.
Referenced by xdc_runtime_Timestamp_SupportProxy_getFreq__E().
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__gateObj ti_sysbios_heaps_HeapBuf_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gateObj)0)
Definition at line 4746 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms ti_sysbios_heaps_HeapBuf_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__gatePrms)0)
Definition at line 4750 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__id ti_sysbios_heaps_HeapBuf_Module__id__C = (xdc_Bits16)0x27
Definition at line 4754 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerDefined ti_sysbios_heaps_HeapBuf_Module__loggerDefined__C = 0
Definition at line 4758 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0 ti_sysbios_heaps_HeapBuf_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn0)0)
Definition at line 4766 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1 ti_sysbios_heaps_HeapBuf_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn1)0)
Definition at line 4770 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2 ti_sysbios_heaps_HeapBuf_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn2)0)
Definition at line 4774 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4 ti_sysbios_heaps_HeapBuf_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn4)0)
Definition at line 4778 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8 ti_sysbios_heaps_HeapBuf_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerFxn8)0)
Definition at line 4782 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj ti_sysbios_heaps_HeapBuf_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapBuf_Module__loggerObj)0)
Definition at line 4762 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapBuf_Module__ ti_sysbios_heaps_HeapBuf_Module__root__V
Initial value:
= {
    {&ti_sysbios_heaps_HeapBuf_Module__root__V.link,
    &ti_sysbios_heaps_HeapBuf_Module__root__V.link},
}
Definition at line 4712 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapBuf_Module_State__ ti_sysbios_heaps_HeapBuf_Module__state__V
Initial value:
= {
    ((void*)0),
}
Definition at line 1367 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_numConstructedHeaps ti_sysbios_heaps_HeapBuf_numConstructedHeaps__C = (xdc_UInt)0x0
Definition at line 4850 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__count ti_sysbios_heaps_HeapBuf_Object__count__C = 0
Definition at line 4786 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapBuf_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_heaps_HeapBuf_Module__FXNS__C,
    &ti_sysbios_heaps_HeapBuf_Module__root__V.link,
    sizeof(ti_sysbios_heaps_HeapBuf___S1) - sizeof(ti_sysbios_heaps_HeapBuf_Object2__),
    0,
    0,
    sizeof(ti_sysbios_heaps_HeapBuf_Object2__),
    (xdc_CPtr)&ti_sysbios_heaps_HeapBuf_Object__PARAMS__C,
    sizeof(ti_sysbios_heaps_HeapBuf_Params),
}
Definition at line 4691 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__heap ti_sysbios_heaps_HeapBuf_Object__heap__C = 0
Definition at line 4790 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_heaps_HeapBuf_Params ti_sysbios_heaps_HeapBuf_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_heaps_HeapBuf_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_heaps_HeapBuf_Object__PARAMS__C.__iprms,
    (xdc_SizeT)0x0,
    (xdc_UInt)0x0,
    (xdc_SizeT)0x0,
    ((xdc_UArg)(0x0)),
    ((xdc_Ptr)(0x0)),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4695 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__sizeof ti_sysbios_heaps_HeapBuf_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapBuf_Object__)
Definition at line 4794 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_Object__table ti_sysbios_heaps_HeapBuf_Object__table__C = 0
Definition at line 4798 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapBuf_trackMaxAllocs ti_sysbios_heaps_HeapBuf_trackMaxAllocs__C = 0
Definition at line 4846 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_align ti_sysbios_heaps_HeapMem_A_align__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4977 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_heapSize ti_sysbios_heaps_HeapMem_A_heapSize__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4973 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_invalidFree ti_sysbios_heaps_HeapMem_A_invalidFree__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4985 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_A_zeroBlock ti_sysbios_heaps_HeapMem_A_zeroBlock__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 4969 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_E_memory ti_sysbios_heaps_HeapMem_E_memory__C = (((xdc_runtime_Error_Id)17) << 16 | 0)
Definition at line 4981 of file mmw_per4ft.c.
__T1_ti_sysbios_heaps_HeapMem_Instance_State__buf ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A
Definition at line 1378 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsEnabled ti_sysbios_heaps_HeapMem_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 4901 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsIncluded ti_sysbios_heaps_HeapMem_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 4905 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__diagsMask ti_sysbios_heaps_HeapMem_Module__diagsMask__C = ((CT__ti_sysbios_heaps_HeapMem_Module__diagsMask)0)
Definition at line 4909 of file mmw_per4ft.c.
const ti_sysbios_heaps_HeapMem_Fxns__ ti_sysbios_heaps_HeapMem_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IHeap_Interface__BASE__C,
    &ti_sysbios_heaps_HeapMem_Module__FXNS__C.__sfxns,
    ti_sysbios_heaps_HeapMem_alloc__E,
    ti_sysbios_heaps_HeapMem_free__E,
    ti_sysbios_heaps_HeapMem_isBlocking__E,
    ti_sysbios_heaps_HeapMem_getStats__E,
    {
        ti_sysbios_heaps_HeapMem_Object__create__S,
        ti_sysbios_heaps_HeapMem_Object__delete__S,
        ti_sysbios_heaps_HeapMem_Handle__label__S,
        0x28,
    }
}
Definition at line 1004 of file mmw_per4ft.c.
Referenced by xdc_runtime_Memory_HeapProxy_Proxy__delegate__S(), and xdc_runtime_Timestamp_SupportProxy_getFreq__E().
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__gateObj ti_sysbios_heaps_HeapMem_Module__gateObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateMutex_Object__table__V[0]))
Definition at line 4913 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__gatePrms ti_sysbios_heaps_HeapMem_Module__gatePrms__C = ((CT__ti_sysbios_heaps_HeapMem_Module__gatePrms)0)
Definition at line 4917 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__id ti_sysbios_heaps_HeapMem_Module__id__C = (xdc_Bits16)0x28
Definition at line 4921 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerDefined ti_sysbios_heaps_HeapMem_Module__loggerDefined__C = 0
Definition at line 4925 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0 ti_sysbios_heaps_HeapMem_Module__loggerFxn0__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn0)0)
Definition at line 4933 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1 ti_sysbios_heaps_HeapMem_Module__loggerFxn1__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn1)0)
Definition at line 4937 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2 ti_sysbios_heaps_HeapMem_Module__loggerFxn2__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn2)0)
Definition at line 4941 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4 ti_sysbios_heaps_HeapMem_Module__loggerFxn4__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn4)0)
Definition at line 4945 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8 ti_sysbios_heaps_HeapMem_Module__loggerFxn8__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerFxn8)0)
Definition at line 4949 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Module__loggerObj ti_sysbios_heaps_HeapMem_Module__loggerObj__C = ((CT__ti_sysbios_heaps_HeapMem_Module__loggerObj)0)
Definition at line 4929 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapMem_Module__ ti_sysbios_heaps_HeapMem_Module__root__V
Initial value:
= {
    {&ti_sysbios_heaps_HeapMem_Module__root__V.link,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link},
}
Definition at line 4880 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__ ti_sysbios_heaps_HeapMem_Module_GateProxy_Module__root__V
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__count ti_sysbios_heaps_HeapMem_Object__count__C = 1
Definition at line 4953 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_heaps_HeapMem_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Module__FXNS__C,
    &ti_sysbios_heaps_HeapMem_Module__root__V.link,
    sizeof(ti_sysbios_heaps_HeapMem___S1) - sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    0,
    0,
    sizeof(ti_sysbios_heaps_HeapMem_Object2__),
    (xdc_CPtr)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C,
    sizeof(ti_sysbios_heaps_HeapMem_Params),
}
Definition at line 4858 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__heap ti_sysbios_heaps_HeapMem_Object__heap__C = 0
Definition at line 4957 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_heaps_HeapMem_Params ti_sysbios_heaps_HeapMem_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_heaps_HeapMem_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_heaps_HeapMem_Object__PARAMS__C.__iprms,
    (xdc_SizeT)0x0,
    ((xdc_Ptr)(0x0)),
    ((xdc_UArg)(0x0)),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 4862 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__sizeof ti_sysbios_heaps_HeapMem_Object__sizeof__C = sizeof(ti_sysbios_heaps_HeapMem_Object__)
Definition at line 4961 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_Object__table ti_sysbios_heaps_HeapMem_Object__table__C = ti_sysbios_heaps_HeapMem_Object__table__V
Definition at line 4965 of file mmw_per4ft.c.
ti_sysbios_heaps_HeapMem_Object__ ti_sysbios_heaps_HeapMem_Object__table__V
Initial value:
= {
    {
        &ti_sysbios_heaps_HeapMem_Module__FXNS__C,
        ((xdc_UArg)(0x8)),
        ((void*)ti_sysbios_heaps_HeapMem_Instance_State_0_buf__A),
        {
            ((ti_sysbios_heaps_HeapMem_Header*)0),
            ((xdc_UArg)(0x10000)),
        },
        (xdc_SizeT)0x8,
    },
}
Definition at line 1397 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapBaseAddr)0)
Definition at line 4989 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr ti_sysbios_heaps_HeapMem_primaryHeapEndAddr__C = ((CT__ti_sysbios_heaps_HeapMem_primaryHeapEndAddr)0)
Definition at line 4993 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_heaps_HeapMem_reqAlign ti_sysbios_heaps_HeapMem_reqAlign__C = (xdc_SizeT)0x8
Definition at line 4997 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base ti_sysbios_interfaces_ICache_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 884 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_A_badThreadType ti_sysbios_knl_Clock_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5166 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_A_clockDisabled ti_sysbios_knl_Clock_A_clockDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5162 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_doTickFunc ti_sysbios_knl_Clock_doTickFunc__C = ((CT__ti_sysbios_knl_Clock_doTickFunc)((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I))
Definition at line 5190 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_LM_begin ti_sysbios_knl_Clock_LM_begin__C = (((xdc_runtime_Log_Event)14) << 16 | 768)
Definition at line 5158 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_LM_tick ti_sysbios_knl_Clock_LM_tick__C = (((xdc_runtime_Log_Event)13) << 16 | 768)
Definition at line 5154 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_LW_delayed ti_sysbios_knl_Clock_LW_delayed__C = (((xdc_runtime_Log_Event)12) << 16 | 1024)
Definition at line 5150 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsEnabled ti_sysbios_knl_Clock_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5082 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsIncluded ti_sysbios_knl_Clock_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5086 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__diagsMask ti_sysbios_knl_Clock_Module__diagsMask__C = ((CT__ti_sysbios_knl_Clock_Module__diagsMask)0)
Definition at line 5090 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__gateObj ti_sysbios_knl_Clock_Module__gateObj__C = ((CT__ti_sysbios_knl_Clock_Module__gateObj)0)
Definition at line 5094 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__gatePrms ti_sysbios_knl_Clock_Module__gatePrms__C = ((CT__ti_sysbios_knl_Clock_Module__gatePrms)0)
Definition at line 5098 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__id ti_sysbios_knl_Clock_Module__id__C = (xdc_Bits16)0x1d
Definition at line 5102 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerDefined ti_sysbios_knl_Clock_Module__loggerDefined__C = 0
Definition at line 5106 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn0 ti_sysbios_knl_Clock_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn0)0)
Definition at line 5114 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn1 ti_sysbios_knl_Clock_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn1)0)
Definition at line 5118 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn2 ti_sysbios_knl_Clock_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn2)0)
Definition at line 5122 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn4 ti_sysbios_knl_Clock_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn4)0)
Definition at line 5126 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerFxn8 ti_sysbios_knl_Clock_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Clock_Module__loggerFxn8)0)
Definition at line 5130 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Module__loggerObj ti_sysbios_knl_Clock_Module__loggerObj__C = ((CT__ti_sysbios_knl_Clock_Module__loggerObj)0)
Definition at line 5110 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_Module__ ti_sysbios_knl_Clock_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Clock_Module__root__V.link,
    &ti_sysbios_knl_Clock_Module__root__V.link},
}
Definition at line 5029 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_Module_State__ ti_sysbios_knl_Clock_Module__state__V
Initial value:
= {
    (xdc_UInt32)0x0,
    (xdc_UInt)0x0,
    (ti_sysbios_knl_Clock_TimerProxy_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    0,
    (xdc_UInt)0x1,
    (xdc_UInt32)0x1,
    (xdc_UInt32)0x0,
    0,
    0,
    0,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Object__table__V[0].elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Object__table__V[0].elem)),
        },
    },
}
Definition at line 1428 of file mmw_per4ft.c.
Referenced by ti_sysbios_knl_Clock_doTick__I().
__FAR__ const xdc_SizeT ti_sysbios_knl_Clock_Module_State_clockQ__O = offsetof(ti_sysbios_knl_Clock_Module_State__,Object_field_clockQ)
Definition at line 1898 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Object__count ti_sysbios_knl_Clock_Object__count__C = 1
Definition at line 5134 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Clock_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Clock_Module__root__V.link,
    sizeof(ti_sysbios_knl_Clock___S1) - sizeof(ti_sysbios_knl_Clock_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Clock_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Clock_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Clock_Params),
}
Definition at line 5010 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Object__heap ti_sysbios_knl_Clock_Object__heap__C = 0
Definition at line 5138 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_knl_Clock_Params ti_sysbios_knl_Clock_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Clock_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Clock_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt32)0x0,
    ((xdc_UArg)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5014 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Object__sizeof ti_sysbios_knl_Clock_Object__sizeof__C = sizeof(ti_sysbios_knl_Clock_Object__)
Definition at line 5142 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_Object__table ti_sysbios_knl_Clock_Object__table__C = ti_sysbios_knl_Clock_Object__table__V
Definition at line 5146 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_Object__ ti_sysbios_knl_Clock_Object__table__V
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Clock_Module__state__V.Object_field_clockQ.elem)),
        },
        (xdc_UInt32)0x4ea4,
        (xdc_UInt32)0x4ea4,
        (xdc_UInt32)20132.6592,
        1,
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_family_arm_a15_TimestampProvider_autoRefreshFxn__I)),
        ((xdc_UArg)0),
    },
}
Definition at line 1410 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_serviceMargin ti_sysbios_knl_Clock_serviceMargin__C = (xdc_UInt32)0x0
Definition at line 5170 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_tickMode ti_sysbios_knl_Clock_tickMode__C = ti_sysbios_knl_Clock_TickMode_PERIODIC
Definition at line 5178 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_tickPeriod ti_sysbios_knl_Clock_tickPeriod__C = (xdc_UInt32)0x3e8
Definition at line 5186 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_tickSource ti_sysbios_knl_Clock_tickSource__C = ti_sysbios_knl_Clock_TickSource_TIMER
Definition at line 5174 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Clock_timerId ti_sysbios_knl_Clock_timerId__C = (xdc_UInt)(-0x0 - 1)
Definition at line 5182 of file mmw_per4ft.c.
ti_sysbios_knl_Clock_TimerProxy_Module__ ti_sysbios_knl_Clock_TimerProxy_Module__root__V
__FAR__ const CT__ti_sysbios_knl_Clock_triggerClock ti_sysbios_knl_Clock_triggerClock__C = 0
Definition at line 5194 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_A_badContext ti_sysbios_knl_Event_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5318 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_A_eventInUse ti_sysbios_knl_Event_A_eventInUse__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5314 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_A_nullEventId ti_sysbios_knl_Event_A_nullEventId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5310 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_A_nullEventMasks ti_sysbios_knl_Event_A_nullEventMasks__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5306 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_A_pendTaskDisabled ti_sysbios_knl_Event_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5322 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_knl_Event_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Event_Object__,Object_field_pendQ)
Definition at line 1906 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_LM_pend ti_sysbios_knl_Event_LM_pend__C = (((xdc_runtime_Log_Event)16) << 16 | 768)
Definition at line 5302 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_LM_post ti_sysbios_knl_Event_LM_post__C = (((xdc_runtime_Log_Event)15) << 16 | 768)
Definition at line 5298 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsEnabled ti_sysbios_knl_Event_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5230 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsIncluded ti_sysbios_knl_Event_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5234 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__diagsMask ti_sysbios_knl_Event_Module__diagsMask__C = ((CT__ti_sysbios_knl_Event_Module__diagsMask)0)
Definition at line 5238 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__gateObj ti_sysbios_knl_Event_Module__gateObj__C = ((CT__ti_sysbios_knl_Event_Module__gateObj)0)
Definition at line 5242 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__gatePrms ti_sysbios_knl_Event_Module__gatePrms__C = ((CT__ti_sysbios_knl_Event_Module__gatePrms)0)
Definition at line 5246 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__id ti_sysbios_knl_Event_Module__id__C = (xdc_Bits16)0x20
Definition at line 5250 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerDefined ti_sysbios_knl_Event_Module__loggerDefined__C = 0
Definition at line 5254 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn0 ti_sysbios_knl_Event_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn0)0)
Definition at line 5262 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn1 ti_sysbios_knl_Event_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn1)0)
Definition at line 5266 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn2 ti_sysbios_knl_Event_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn2)0)
Definition at line 5270 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn4 ti_sysbios_knl_Event_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn4)0)
Definition at line 5274 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerFxn8 ti_sysbios_knl_Event_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Event_Module__loggerFxn8)0)
Definition at line 5278 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Module__loggerObj ti_sysbios_knl_Event_Module__loggerObj__C = ((CT__ti_sysbios_knl_Event_Module__loggerObj)0)
Definition at line 5258 of file mmw_per4ft.c.
ti_sysbios_knl_Event_Module__ ti_sysbios_knl_Event_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Event_Module__root__V.link,
    &ti_sysbios_knl_Event_Module__root__V.link},
}
Definition at line 5223 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Object__count ti_sysbios_knl_Event_Object__count__C = 0
Definition at line 5282 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Event_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Event_Module__root__V.link,
    sizeof(ti_sysbios_knl_Event___S1) - sizeof(ti_sysbios_knl_Event_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Event_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Event_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Event_Params),
}
Definition at line 5207 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Object__heap ti_sysbios_knl_Event_Object__heap__C = 0
Definition at line 5286 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_knl_Event_Params ti_sysbios_knl_Event_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Event_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Event_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5211 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Object__sizeof ti_sysbios_knl_Event_Object__sizeof__C = sizeof(ti_sysbios_knl_Event_Object__)
Definition at line 5290 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Event_Object__table ti_sysbios_knl_Event_Object__table__C = 0
Definition at line 5294 of file mmw_per4ft.c.
const __T1_ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__A
Initial value:
= {
    (xdc_UInt)0x0,
    (xdc_UInt)0x0,
    (xdc_UInt)0x0,
}
Definition at line 1458 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_coreList ti_sysbios_knl_Idle_coreList__C = {3, ((__T1_ti_sysbios_knl_Idle_coreList *)ti_sysbios_knl_Idle_coreList__A)}
Definition at line 5419 of file mmw_per4ft.c.
const __T1_ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)MmwDemo_sleep)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_checkStack)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_utils_Load_idleFxn__E)),
}
Definition at line 1455 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_funcList ti_sysbios_knl_Idle_funcList__C = {3, ((__T1_ti_sysbios_knl_Idle_funcList *)ti_sysbios_knl_Idle_funcList__A)}
Definition at line 5415 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsEnabled ti_sysbios_knl_Idle_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5347 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsIncluded ti_sysbios_knl_Idle_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5351 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__diagsMask ti_sysbios_knl_Idle_Module__diagsMask__C = ((CT__ti_sysbios_knl_Idle_Module__diagsMask)0)
Definition at line 5355 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__gateObj ti_sysbios_knl_Idle_Module__gateObj__C = ((CT__ti_sysbios_knl_Idle_Module__gateObj)0)
Definition at line 5359 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__gatePrms ti_sysbios_knl_Idle_Module__gatePrms__C = ((CT__ti_sysbios_knl_Idle_Module__gatePrms)0)
Definition at line 5363 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__id ti_sysbios_knl_Idle_Module__id__C = (xdc_Bits16)0x1e
Definition at line 5367 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerDefined ti_sysbios_knl_Idle_Module__loggerDefined__C = 0
Definition at line 5371 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn0 ti_sysbios_knl_Idle_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn0)0)
Definition at line 5379 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn1 ti_sysbios_knl_Idle_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn1)0)
Definition at line 5383 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn2 ti_sysbios_knl_Idle_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn2)0)
Definition at line 5387 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn4 ti_sysbios_knl_Idle_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn4)0)
Definition at line 5391 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerFxn8 ti_sysbios_knl_Idle_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Idle_Module__loggerFxn8)0)
Definition at line 5395 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Module__loggerObj ti_sysbios_knl_Idle_Module__loggerObj__C = ((CT__ti_sysbios_knl_Idle_Module__loggerObj)0)
Definition at line 5375 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Object__count ti_sysbios_knl_Idle_Object__count__C = 0
Definition at line 5399 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Object__heap ti_sysbios_knl_Idle_Object__heap__C = 0
Definition at line 5403 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Object__sizeof ti_sysbios_knl_Idle_Object__sizeof__C = 0
Definition at line 5407 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Idle_Object__table ti_sysbios_knl_Idle_Object__table__C = 0
Definition at line 5411 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsEnabled ti_sysbios_knl_Intrinsics_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5428 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsIncluded ti_sysbios_knl_Intrinsics_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5432 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__diagsMask ti_sysbios_knl_Intrinsics_Module__diagsMask__C = ((CT__ti_sysbios_knl_Intrinsics_Module__diagsMask)0)
Definition at line 5436 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__gateObj ti_sysbios_knl_Intrinsics_Module__gateObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gateObj)0)
Definition at line 5440 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__gatePrms ti_sysbios_knl_Intrinsics_Module__gatePrms__C = ((CT__ti_sysbios_knl_Intrinsics_Module__gatePrms)0)
Definition at line 5444 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__id ti_sysbios_knl_Intrinsics_Module__id__C = (xdc_Bits16)0x1f
Definition at line 5448 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerDefined ti_sysbios_knl_Intrinsics_Module__loggerDefined__C = 0
Definition at line 5452 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0 ti_sysbios_knl_Intrinsics_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn0)0)
Definition at line 5460 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1 ti_sysbios_knl_Intrinsics_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn1)0)
Definition at line 5464 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2 ti_sysbios_knl_Intrinsics_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn2)0)
Definition at line 5468 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4 ti_sysbios_knl_Intrinsics_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn4)0)
Definition at line 5472 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8 ti_sysbios_knl_Intrinsics_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerFxn8)0)
Definition at line 5476 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Module__loggerObj ti_sysbios_knl_Intrinsics_Module__loggerObj__C = ((CT__ti_sysbios_knl_Intrinsics_Module__loggerObj)0)
Definition at line 5456 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__count ti_sysbios_knl_Intrinsics_Object__count__C = 0
Definition at line 5480 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__heap ti_sysbios_knl_Intrinsics_Object__heap__C = 0
Definition at line 5484 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__sizeof ti_sysbios_knl_Intrinsics_Object__sizeof__C = 0
Definition at line 5488 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Intrinsics_Object__table ti_sysbios_knl_Intrinsics_Object__table__C = 0
Definition at line 5492 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsEnabled ti_sysbios_knl_Queue_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5528 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsIncluded ti_sysbios_knl_Queue_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5532 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__diagsMask ti_sysbios_knl_Queue_Module__diagsMask__C = ((CT__ti_sysbios_knl_Queue_Module__diagsMask)0)
Definition at line 5536 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__gateObj ti_sysbios_knl_Queue_Module__gateObj__C = ((CT__ti_sysbios_knl_Queue_Module__gateObj)0)
Definition at line 5540 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__gatePrms ti_sysbios_knl_Queue_Module__gatePrms__C = ((CT__ti_sysbios_knl_Queue_Module__gatePrms)0)
Definition at line 5544 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__id ti_sysbios_knl_Queue_Module__id__C = (xdc_Bits16)0x21
Definition at line 5548 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerDefined ti_sysbios_knl_Queue_Module__loggerDefined__C = 0
Definition at line 5552 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn0 ti_sysbios_knl_Queue_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn0)0)
Definition at line 5560 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn1 ti_sysbios_knl_Queue_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn1)0)
Definition at line 5564 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn2 ti_sysbios_knl_Queue_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn2)0)
Definition at line 5568 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn4 ti_sysbios_knl_Queue_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn4)0)
Definition at line 5572 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerFxn8 ti_sysbios_knl_Queue_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Queue_Module__loggerFxn8)0)
Definition at line 5576 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Module__loggerObj ti_sysbios_knl_Queue_Module__loggerObj__C = ((CT__ti_sysbios_knl_Queue_Module__loggerObj)0)
Definition at line 5556 of file mmw_per4ft.c.
ti_sysbios_knl_Queue_Module__ ti_sysbios_knl_Queue_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Queue_Module__root__V.link,
    &ti_sysbios_knl_Queue_Module__root__V.link},
}
Definition at line 5521 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Object__count ti_sysbios_knl_Queue_Object__count__C = 0
Definition at line 5580 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Queue_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Queue_Module__root__V.link,
    sizeof(ti_sysbios_knl_Queue___S1) - sizeof(ti_sysbios_knl_Queue_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Queue_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Queue_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Queue_Params),
}
Definition at line 5505 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Object__heap ti_sysbios_knl_Queue_Object__heap__C = 0
Definition at line 5584 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_knl_Queue_Params ti_sysbios_knl_Queue_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Queue_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Queue_Object__PARAMS__C.__iprms,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5509 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Object__sizeof ti_sysbios_knl_Queue_Object__sizeof__C = sizeof(ti_sysbios_knl_Queue_Object__)
Definition at line 5588 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Queue_Object__table ti_sysbios_knl_Queue_Object__table__C = 0
Definition at line 5592 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_badContext ti_sysbios_knl_Semaphore_A_badContext__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5710 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_invTimeout ti_sysbios_knl_Semaphore_A_invTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5706 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_noEvents ti_sysbios_knl_Semaphore_A_noEvents__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5702 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_overflow ti_sysbios_knl_Semaphore_A_overflow__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5714 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_A_pendTaskDisabled ti_sysbios_knl_Semaphore_A_pendTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 5718 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace ti_sysbios_knl_Semaphore_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)9) << 16 | 0)
Definition at line 5722 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_eventPost ti_sysbios_knl_Semaphore_eventPost__C = ((CT__ti_sysbios_knl_Semaphore_eventPost)0)
Definition at line 5734 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_eventSync ti_sysbios_knl_Semaphore_eventSync__C = ((CT__ti_sysbios_knl_Semaphore_eventSync)0)
Definition at line 5738 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_knl_Semaphore_Instance_State_pendQ__O = offsetof(ti_sysbios_knl_Semaphore_Object__,Object_field_pendQ)
Definition at line 1914 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_LM_pend ti_sysbios_knl_Semaphore_LM_pend__C = (((xdc_runtime_Log_Event)18) << 16 | 768)
Definition at line 5698 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_LM_post ti_sysbios_knl_Semaphore_LM_post__C = (((xdc_runtime_Log_Event)17) << 16 | 768)
Definition at line 5694 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsEnabled ti_sysbios_knl_Semaphore_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5626 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsIncluded ti_sysbios_knl_Semaphore_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 5630 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__diagsMask ti_sysbios_knl_Semaphore_Module__diagsMask__C = ((CT__ti_sysbios_knl_Semaphore_Module__diagsMask)0)
Definition at line 5634 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__gateObj ti_sysbios_knl_Semaphore_Module__gateObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__gateObj)0)
Definition at line 5638 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__gatePrms ti_sysbios_knl_Semaphore_Module__gatePrms__C = ((CT__ti_sysbios_knl_Semaphore_Module__gatePrms)0)
Definition at line 5642 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__id ti_sysbios_knl_Semaphore_Module__id__C = (xdc_Bits16)0x22
Definition at line 5646 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerDefined ti_sysbios_knl_Semaphore_Module__loggerDefined__C = 0
Definition at line 5650 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0 ti_sysbios_knl_Semaphore_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn0)0)
Definition at line 5658 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1 ti_sysbios_knl_Semaphore_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn1)0)
Definition at line 5662 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2 ti_sysbios_knl_Semaphore_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn2)0)
Definition at line 5666 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4 ti_sysbios_knl_Semaphore_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn4)0)
Definition at line 5670 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8 ti_sysbios_knl_Semaphore_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerFxn8)0)
Definition at line 5674 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Module__loggerObj ti_sysbios_knl_Semaphore_Module__loggerObj__C = ((CT__ti_sysbios_knl_Semaphore_Module__loggerObj)0)
Definition at line 5654 of file mmw_per4ft.c.
ti_sysbios_knl_Semaphore_Module__ ti_sysbios_knl_Semaphore_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Semaphore_Module__root__V.link,
    &ti_sysbios_knl_Semaphore_Module__root__V.link},
}
Definition at line 5619 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__count ti_sysbios_knl_Semaphore_Object__count__C = 0
Definition at line 5678 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Semaphore_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Semaphore_Module__root__V.link,
    sizeof(ti_sysbios_knl_Semaphore___S1) - sizeof(ti_sysbios_knl_Semaphore_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Semaphore_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Semaphore_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Semaphore_Params),
}
Definition at line 5600 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__heap ti_sysbios_knl_Semaphore_Object__heap__C = 0
Definition at line 5682 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_knl_Semaphore_Params ti_sysbios_knl_Semaphore_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Semaphore_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Semaphore_Object__PARAMS__C.__iprms,
    0,
    (xdc_UInt)0x1,
    ti_sysbios_knl_Semaphore_Mode_COUNTING,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5604 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__sizeof ti_sysbios_knl_Semaphore_Object__sizeof__C = sizeof(ti_sysbios_knl_Semaphore_Object__)
Definition at line 5686 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_Object__table ti_sysbios_knl_Semaphore_Object__table__C = 0
Definition at line 5690 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_supportsEvents ti_sysbios_knl_Semaphore_supportsEvents__C = 0
Definition at line 5726 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Semaphore_supportsPriority ti_sysbios_knl_Semaphore_supportsPriority__C = 1
Definition at line 5730 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_badAffinity ti_sysbios_knl_Task_A_badAffinity__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6132 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_badPriority ti_sysbios_knl_Task_A_badPriority__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6124 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_badTaskState ti_sysbios_knl_Task_A_badTaskState__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6112 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_badThreadType ti_sysbios_knl_Task_A_badThreadType__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6108 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_badTimeout ti_sysbios_knl_Task_A_badTimeout__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6128 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_invalidCoreId ti_sysbios_knl_Task_A_invalidCoreId__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6140 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_noPendElem ti_sysbios_knl_Task_A_noPendElem__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6116 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_sleepTaskDisabled ti_sysbios_knl_Task_A_sleepTaskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6136 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_A_taskDisabled ti_sysbios_knl_Task_A_taskDisabled__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6120 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_allBlockedFunc ti_sysbios_knl_Task_allBlockedFunc__C = ((CT__ti_sysbios_knl_Task_allBlockedFunc)0)
Definition at line 6156 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_checkStackFlag ti_sysbios_knl_Task_checkStackFlag__C = 1
Definition at line 6164 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_defaultStackHeap ti_sysbios_knl_Task_defaultStackHeap__C = 0
Definition at line 6152 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_defaultStackSize ti_sysbios_knl_Task_defaultStackSize__C = (xdc_SizeT)0x800
Definition at line 6148 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_deleteTerminatedTasks ti_sysbios_knl_Task_deleteTerminatedTasks__C = 0
Definition at line 6168 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_deleteNotAllowed ti_sysbios_knl_Task_E_deleteNotAllowed__C = (((xdc_runtime_Error_Id)12) << 16 | 0)
Definition at line 6092 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_moduleStateCheckFailed ti_sysbios_knl_Task_E_moduleStateCheckFailed__C = (((xdc_runtime_Error_Id)13) << 16 | 0)
Definition at line 6096 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_objectCheckFailed ti_sysbios_knl_Task_E_objectCheckFailed__C = (((xdc_runtime_Error_Id)14) << 16 | 0)
Definition at line 6100 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_objectNotInKernelSpace ti_sysbios_knl_Task_E_objectNotInKernelSpace__C = (((xdc_runtime_Error_Id)15) << 16 | 0)
Definition at line 6104 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_spOutOfBounds ti_sysbios_knl_Task_E_spOutOfBounds__C = (((xdc_runtime_Error_Id)11) << 16 | 0)
Definition at line 6088 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_E_stackOverflow ti_sysbios_knl_Task_E_stackOverflow__C = (((xdc_runtime_Error_Id)10) << 16 | 0)
Definition at line 6084 of file mmw_per4ft.c.
const __T1_ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__A
Initial value:
= {
    {
        ((xdc_Void(*)(xdc_Int))((xdc_Fxn)ti_sysbios_utils_Load_taskRegHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle,xdc_runtime_Error_Block*))((xdc_Fxn)ti_sysbios_utils_Load_taskCreateHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))0),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle,ti_sysbios_knl_Task_Handle))((xdc_Fxn)ti_sysbios_utils_Load_taskSwitchHook__E)),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))0),
        ((xdc_Void(*)(ti_sysbios_knl_Task_Handle))((xdc_Fxn)ti_sysbios_utils_Load_taskDeleteHook__E)),
    },
}
Definition at line 1546 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_hooks ti_sysbios_knl_Task_hooks__C = {1, ((__T1_ti_sysbios_knl_Task_hooks *)ti_sysbios_knl_Task_hooks__A)}
Definition at line 6172 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_initStackFlag ti_sysbios_knl_Task_initStackFlag__C = 1
Definition at line 6160 of file mmw_per4ft.c.
__T1_ti_sysbios_knl_Task_Instance_State__hookEnv ti_sysbios_knl_Task_Instance_State_0_hookEnv__A
Definition at line 1508 of file mmw_per4ft.c.
__T1_ti_sysbios_knl_Task_Instance_State__stack ti_sysbios_knl_Task_Instance_State_0_stack__A
Definition at line 1489 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LD_block ti_sysbios_knl_Task_LD_block__C = (((xdc_runtime_Log_Event)22) << 16 | 512)
Definition at line 6056 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LD_exit ti_sysbios_knl_Task_LD_exit__C = (((xdc_runtime_Log_Event)25) << 16 | 512)
Definition at line 6068 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LD_ready ti_sysbios_knl_Task_LD_ready__C = (((xdc_runtime_Log_Event)21) << 16 | 512)
Definition at line 6052 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_noWork ti_sysbios_knl_Task_LM_noWork__C = (((xdc_runtime_Log_Event)28) << 16 | 1024)
Definition at line 6080 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_schedule ti_sysbios_knl_Task_LM_schedule__C = (((xdc_runtime_Log_Event)27) << 16 | 1024)
Definition at line 6076 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_setAffinity ti_sysbios_knl_Task_LM_setAffinity__C = (((xdc_runtime_Log_Event)26) << 16 | 768)
Definition at line 6072 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_setPri ti_sysbios_knl_Task_LM_setPri__C = (((xdc_runtime_Log_Event)24) << 16 | 768)
Definition at line 6064 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_sleep ti_sysbios_knl_Task_LM_sleep__C = (((xdc_runtime_Log_Event)20) << 16 | 768)
Definition at line 6048 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_switch ti_sysbios_knl_Task_LM_switch__C = (((xdc_runtime_Log_Event)19) << 16 | 768)
Definition at line 6044 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_LM_yield ti_sysbios_knl_Task_LM_yield__C = (((xdc_runtime_Log_Event)23) << 16 | 768)
Definition at line 6060 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsEnabled ti_sysbios_knl_Task_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 5976 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsIncluded ti_sysbios_knl_Task_Module__diagsIncluded__C = (xdc_Bits32)0x190
Definition at line 5980 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__diagsMask ti_sysbios_knl_Task_Module__diagsMask__C = ((CT__ti_sysbios_knl_Task_Module__diagsMask)((void*)&ti_sysbios_knl_Task_Module__root__V.mask))
Definition at line 5984 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__gateObj ti_sysbios_knl_Task_Module__gateObj__C = ((CT__ti_sysbios_knl_Task_Module__gateObj)0)
Definition at line 5988 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__gatePrms ti_sysbios_knl_Task_Module__gatePrms__C = ((CT__ti_sysbios_knl_Task_Module__gatePrms)0)
Definition at line 5992 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__id ti_sysbios_knl_Task_Module__id__C = (xdc_Bits16)0x23
Definition at line 5996 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerDefined ti_sysbios_knl_Task_Module__loggerDefined__C = 0
Definition at line 6000 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn0 ti_sysbios_knl_Task_Module__loggerFxn0__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn0)0)
Definition at line 6008 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn1 ti_sysbios_knl_Task_Module__loggerFxn1__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn1)0)
Definition at line 6012 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn2 ti_sysbios_knl_Task_Module__loggerFxn2__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn2)0)
Definition at line 6016 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn4 ti_sysbios_knl_Task_Module__loggerFxn4__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn4)0)
Definition at line 6020 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerFxn8 ti_sysbios_knl_Task_Module__loggerFxn8__C = ((CT__ti_sysbios_knl_Task_Module__loggerFxn8)0)
Definition at line 6024 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Module__loggerObj ti_sysbios_knl_Task_Module__loggerObj__C = ((CT__ti_sysbios_knl_Task_Module__loggerObj)0)
Definition at line 6004 of file mmw_per4ft.c.
ti_sysbios_knl_Task_Module__ ti_sysbios_knl_Task_Module__root__V
Initial value:
= {
    {&ti_sysbios_knl_Task_Module__root__V.link,
    &ti_sysbios_knl_Task_Module__root__V.link},
    256,
}
Definition at line 5779 of file mmw_per4ft.c.
ti_sysbios_knl_Task_Module_State__ ti_sysbios_knl_Task_Module__state__V
Initial value:
= {
    1,
    (xdc_UInt)0x0,
    0,
    (xdc_UInt)0x1,
    0,
    0,
    ((void*)ti_sysbios_knl_Task_Module_State_0_readyQ__A),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)0),
    ((void*)ti_sysbios_knl_Task_Module_State_0_idleTask__A),
    ((void*)0),
    1,
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_inactiveQ.elem)),
        },
    },
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Module__state__V.Object_field_terminatedQ.elem)),
        },
    },
}
Definition at line 1540 of file mmw_per4ft.c.
__T1_ti_sysbios_knl_Task_Module_State__idleTask ti_sysbios_knl_Task_Module_State_0_idleTask__A
Initial value:
= {
    (ti_sysbios_knl_Task_Handle)&ti_sysbios_knl_Task_Object__table__V[0],
}
Definition at line 1537 of file mmw_per4ft.c.
__T1_ti_sysbios_knl_Task_Module_State__readyQ ti_sysbios_knl_Task_Module_State_0_readyQ__A
Definition at line 1534 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_knl_Task_Module_State_inactiveQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_inactiveQ)
Definition at line 1922 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_knl_Task_Module_State_terminatedQ__O = offsetof(ti_sysbios_knl_Task_Module_State__,Object_field_terminatedQ)
Definition at line 1924 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckFlag ti_sysbios_knl_Task_moduleStateCheckFlag__C = 0
Definition at line 6184 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckFxn ti_sysbios_knl_Task_moduleStateCheckFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_moduleStateCheck__I))
Definition at line 6176 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn ti_sysbios_knl_Task_moduleStateCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_moduleStateCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getModuleStateCheckValue__I))
Definition at line 6180 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_numConstructedTasks ti_sysbios_knl_Task_numConstructedTasks__C = (xdc_UInt)0x0
Definition at line 6200 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_numPriorities ti_sysbios_knl_Task_numPriorities__C = (xdc_UInt)0x10
Definition at line 6144 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Object__count ti_sysbios_knl_Task_Object__count__C = 1
Definition at line 6028 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_knl_Task_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)-1,
    &ti_sysbios_knl_Task_Module__root__V.link,
    sizeof(ti_sysbios_knl_Task___S1) - sizeof(ti_sysbios_knl_Task_Object2__),
    0,
    0,
    sizeof(ti_sysbios_knl_Task_Object2__),
    (xdc_CPtr)&ti_sysbios_knl_Task_Object__PARAMS__C,
    sizeof(ti_sysbios_knl_Task_Params),
}
Definition at line 5746 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Object__heap ti_sysbios_knl_Task_Object__heap__C = 0
Definition at line 6032 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_knl_Task_Params ti_sysbios_knl_Task_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_knl_Task_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_knl_Task_Object__PARAMS__C.__iprms,
    ((xdc_UArg)(0x0)),
    ((xdc_UArg)(0x0)),
    (xdc_Int)0x1,
    ((xdc_Ptr)0),
    (xdc_SizeT)0x0,
    0,
    ((xdc_Ptr)0),
    1,
    (xdc_UInt)0x0,
    1,
    ((xdc_Ptr)0),
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 5750 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Object__sizeof ti_sysbios_knl_Task_Object__sizeof__C = sizeof(ti_sysbios_knl_Task_Object__)
Definition at line 6036 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_Object__table ti_sysbios_knl_Task_Object__table__C = ti_sysbios_knl_Task_Object__table__V
Definition at line 6040 of file mmw_per4ft.c.
ti_sysbios_knl_Task_Object__ ti_sysbios_knl_Task_Object__table__V
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_knl_Task_Object__table__V[0].qElem)),
        },
        (xdc_Int)0x0,
        (xdc_UInt)0x1,
        ((xdc_Ptr)0),
        ti_sysbios_knl_Task_Mode_INACTIVE,
        ((ti_sysbios_knl_Task_PendElem*)0),
        (xdc_SizeT)0x320,
        ((void*)ti_sysbios_knl_Task_Instance_State_0_stack__A),
        0,
        ((xdc_Void(*)(xdc_UArg,xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Idle_loop__E)),
        ((xdc_UArg)(0x0)),
        ((xdc_UArg)(0x0)),
        ((xdc_Ptr)0),
        ((void*)ti_sysbios_knl_Task_Instance_State_0_hookEnv__A),
        1,
        0,
        (xdc_UInt)0x0,
        (xdc_UInt)0x0,
        1,
        ((xdc_Ptr)0),
        (xdc_UInt32)0x0,
        ((xdc_Ptr)0),
    },
}
Definition at line 1511 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckFlag ti_sysbios_knl_Task_objectCheckFlag__C = 0
Definition at line 6196 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckFxn ti_sysbios_knl_Task_objectCheckFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckFxn)((xdc_Fxn)ti_sysbios_knl_Task_objectCheck__I))
Definition at line 6188 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_objectCheckValueFxn ti_sysbios_knl_Task_objectCheckValueFxn__C = ((CT__ti_sysbios_knl_Task_objectCheckValueFxn)((xdc_Fxn)ti_sysbios_knl_Task_getObjectCheckValue__I))
Definition at line 6192 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_knl_Task_startupHookFunc ti_sysbios_knl_Task_startupHookFunc__C = ((CT__ti_sysbios_knl_Task_startupHookFunc)0)
Definition at line 6204 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_A_invalidTimer ti_sysbios_timers_rti_Timer_A_invalidTimer__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6393 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_anyMask ti_sysbios_timers_rti_Timer_anyMask__C = (xdc_UInt)0x3
Definition at line 6413 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_continueOnSuspend ti_sysbios_timers_rti_Timer_continueOnSuspend__C = 0
Definition at line 6417 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_cannotSupport ti_sysbios_timers_rti_Timer_E_cannotSupport__C = (((xdc_runtime_Error_Id)37) << 16 | 0)
Definition at line 6409 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_invalidHwiMask ti_sysbios_timers_rti_Timer_E_invalidHwiMask__C = (((xdc_runtime_Error_Id)36) << 16 | 0)
Definition at line 6405 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_invalidTimer ti_sysbios_timers_rti_Timer_E_invalidTimer__C = (((xdc_runtime_Error_Id)34) << 16 | 0)
Definition at line 6397 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_E_notAvailable ti_sysbios_timers_rti_Timer_E_notAvailable__C = (((xdc_runtime_Error_Id)35) << 16 | 0)
Definition at line 6401 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsEnabled ti_sysbios_timers_rti_Timer_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6325 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsIncluded ti_sysbios_timers_rti_Timer_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6329 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__diagsMask ti_sysbios_timers_rti_Timer_Module__diagsMask__C = ((CT__ti_sysbios_timers_rti_Timer_Module__diagsMask)0)
Definition at line 6333 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__gateObj ti_sysbios_timers_rti_Timer_Module__gateObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gateObj)0)
Definition at line 6337 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__gatePrms ti_sysbios_timers_rti_Timer_Module__gatePrms__C = ((CT__ti_sysbios_timers_rti_Timer_Module__gatePrms)0)
Definition at line 6341 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__id ti_sysbios_timers_rti_Timer_Module__id__C = (xdc_Bits16)0x38
Definition at line 6345 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerDefined ti_sysbios_timers_rti_Timer_Module__loggerDefined__C = 0
Definition at line 6349 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0 ti_sysbios_timers_rti_Timer_Module__loggerFxn0__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn0)0)
Definition at line 6357 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1 ti_sysbios_timers_rti_Timer_Module__loggerFxn1__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn1)0)
Definition at line 6361 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2 ti_sysbios_timers_rti_Timer_Module__loggerFxn2__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn2)0)
Definition at line 6365 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4 ti_sysbios_timers_rti_Timer_Module__loggerFxn4__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn4)0)
Definition at line 6369 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8 ti_sysbios_timers_rti_Timer_Module__loggerFxn8__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerFxn8)0)
Definition at line 6373 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Module__loggerObj ti_sysbios_timers_rti_Timer_Module__loggerObj__C = ((CT__ti_sysbios_timers_rti_Timer_Module__loggerObj)0)
Definition at line 6353 of file mmw_per4ft.c.
ti_sysbios_timers_rti_Timer_Module__ ti_sysbios_timers_rti_Timer_Module__root__V
Initial value:
= {
    {&ti_sysbios_timers_rti_Timer_Module__root__V.link,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link},
}
Definition at line 6245 of file mmw_per4ft.c.
ti_sysbios_timers_rti_Timer_Module_State__ ti_sysbios_timers_rti_Timer_Module__state__V
Initial value:
= {
    (xdc_UInt)0x2,
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_device__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A),
    ((void*)ti_sysbios_timers_rti_Timer_Module_State_0_handles__A),
}
Definition at line 1579 of file mmw_per4ft.c.
__T1_ti_sysbios_timers_rti_Timer_Module_State__device ti_sysbios_timers_rti_Timer_Module_State_0_device__A
Initial value:
= {
    {
        (xdc_Int)0x2,
        (xdc_Int)(-0x0 - 1),
        ((xdc_Ptr)((void*)0xfffffc00)),
    },
    {
        (xdc_Int)0x3,
        (xdc_Int)(-0x0 - 1),
        ((xdc_Ptr)((void*)0xfffffc00)),
    },
}
Definition at line 1570 of file mmw_per4ft.c.
__T1_ti_sysbios_timers_rti_Timer_Module_State__handles ti_sysbios_timers_rti_Timer_Module_State_0_handles__A
Initial value:
= {
    (ti_sysbios_timers_rti_Timer_Handle)&ti_sysbios_timers_rti_Timer_Object__table__V[0],
    0,
}
Definition at line 1576 of file mmw_per4ft.c.
__T1_ti_sysbios_timers_rti_Timer_Module_State__intFreqs ti_sysbios_timers_rti_Timer_Module_State_0_intFreqs__A
Initial value:
= {
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0xbebc200,
    },
}
Definition at line 1573 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_numTimerDevices ti_sysbios_timers_rti_Timer_numTimerDevices__C = (xdc_Int)0x2
Definition at line 6425 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__count ti_sysbios_timers_rti_Timer_Object__count__C = 1
Definition at line 6377 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc ti_sysbios_timers_rti_Timer_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)0,
    &ti_sysbios_timers_rti_Timer_Module__root__V.link,
    sizeof(ti_sysbios_timers_rti_Timer___S1) - sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    0,
    0,
    sizeof(ti_sysbios_timers_rti_Timer_Object2__),
    (xdc_CPtr)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C,
    sizeof(ti_sysbios_timers_rti_Timer_Params),
}
Definition at line 6217 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__heap ti_sysbios_timers_rti_Timer_Object__heap__C = 0
Definition at line 6381 of file mmw_per4ft.c.
__FAR__ const ti_sysbios_timers_rti_Timer_Params ti_sysbios_timers_rti_Timer_Object__PARAMS__C
Initial value:
= {
    sizeof (ti_sysbios_timers_rti_Timer_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&ti_sysbios_timers_rti_Timer_Object__PARAMS__C.__iprms,
    ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
    ti_sysbios_interfaces_ITimer_StartMode_AUTO,
    ((xdc_UArg)0),
    (xdc_UInt32)0x0,
    ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
    {
        (xdc_Bits32)0x0,
        (xdc_Bits32)0x0,
    },
    1,
    ((ti_sysbios_hal_Hwi_Params*)0),
    (xdc_UInt8)0x1,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 6221 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__sizeof ti_sysbios_timers_rti_Timer_Object__sizeof__C = sizeof(ti_sysbios_timers_rti_Timer_Object__)
Definition at line 6385 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_Object__table ti_sysbios_timers_rti_Timer_Object__table__C = ti_sysbios_timers_rti_Timer_Object__table__V
Definition at line 6389 of file mmw_per4ft.c.
ti_sysbios_timers_rti_Timer_Object__ ti_sysbios_timers_rti_Timer_Object__table__V
Initial value:
= {
    {
        0,
        1,
        (xdc_Int)0x0,
        ti_sysbios_interfaces_ITimer_RunMode_CONTINUOUS,
        ti_sysbios_interfaces_ITimer_StartMode_AUTO,
        (xdc_UInt)0x1,
        (xdc_UInt)0x3e8,
        ti_sysbios_interfaces_ITimer_PeriodType_MICROSECS,
        (xdc_UInt)0x2,
        ((xdc_UArg)0),
        ((xdc_Void(*)(xdc_UArg))((xdc_Fxn)ti_sysbios_knl_Clock_doTick__I)),
        {
            (xdc_Bits32)0x0,
            (xdc_Bits32)0x0,
        },
        (ti_sysbios_hal_Hwi_Handle)&ti_sysbios_hal_Hwi_Object__table__V[0],
        1,
    },
}
Definition at line 1559 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_timers_rti_Timer_startupNeeded ti_sysbios_timers_rti_Timer_startupNeeded__C = (xdc_UInt)0x1
Definition at line 6421 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_autoAddTasks ti_sysbios_utils_Load_autoAddTasks__C = 1
Definition at line 6631 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_hwiEnabled ti_sysbios_utils_Load_hwiEnabled__C = 0
Definition at line 6619 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_LS_cpuLoad ti_sysbios_utils_Load_LS_cpuLoad__C = (((xdc_runtime_Log_Event)31) << 16 | 2048)
Definition at line 6591 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_LS_hwiLoad ti_sysbios_utils_Load_LS_hwiLoad__C = (((xdc_runtime_Log_Event)32) << 16 | 2048)
Definition at line 6595 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_LS_swiLoad ti_sysbios_utils_Load_LS_swiLoad__C = (((xdc_runtime_Log_Event)33) << 16 | 2048)
Definition at line 6599 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_LS_taskLoad ti_sysbios_utils_Load_LS_taskLoad__C = (((xdc_runtime_Log_Event)34) << 16 | 2048)
Definition at line 6603 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsEnabled ti_sysbios_utils_Load_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6523 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsIncluded ti_sysbios_utils_Load_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6527 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__diagsMask ti_sysbios_utils_Load_Module__diagsMask__C = ((CT__ti_sysbios_utils_Load_Module__diagsMask)0)
Definition at line 6531 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__gateObj ti_sysbios_utils_Load_Module__gateObj__C = ((CT__ti_sysbios_utils_Load_Module__gateObj)0)
Definition at line 6535 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__gatePrms ti_sysbios_utils_Load_Module__gatePrms__C = ((CT__ti_sysbios_utils_Load_Module__gatePrms)0)
Definition at line 6539 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__id ti_sysbios_utils_Load_Module__id__C = (xdc_Bits16)0x34
Definition at line 6543 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerDefined ti_sysbios_utils_Load_Module__loggerDefined__C = 0
Definition at line 6547 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn0 ti_sysbios_utils_Load_Module__loggerFxn0__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn0)0)
Definition at line 6555 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn1 ti_sysbios_utils_Load_Module__loggerFxn1__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn1)0)
Definition at line 6559 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn2 ti_sysbios_utils_Load_Module__loggerFxn2__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn2)0)
Definition at line 6563 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn4 ti_sysbios_utils_Load_Module__loggerFxn4__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn4)0)
Definition at line 6567 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerFxn8 ti_sysbios_utils_Load_Module__loggerFxn8__C = ((CT__ti_sysbios_utils_Load_Module__loggerFxn8)0)
Definition at line 6571 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Module__loggerObj ti_sysbios_utils_Load_Module__loggerObj__C = ((CT__ti_sysbios_utils_Load_Module__loggerObj)0)
Definition at line 6551 of file mmw_per4ft.c.
ti_sysbios_utils_Load_Module_State__ ti_sysbios_utils_Load_Module__state__V
Definition at line 1625 of file mmw_per4ft.c.
__T1_ti_sysbios_utils_Load_Module_State__runningTask ti_sysbios_utils_Load_Module_State_0_runningTask__A
Initial value:
= {
    0,
}
Definition at line 1619 of file mmw_per4ft.c.
__T1_ti_sysbios_utils_Load_Module_State__taskEnv ti_sysbios_utils_Load_Module_State_0_taskEnv__A
Initial value:
= {
    {
        {
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_utils_Load_Module_State_0_taskEnv__A[0].qElem)),
            ((ti_sysbios_knl_Queue_Elem*)((void*)&ti_sysbios_utils_Load_Module_State_0_taskEnv__A[0].qElem)),
        },
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        (xdc_UInt32)0x0,
        ((xdc_Ptr)0),
    },
}
Definition at line 1622 of file mmw_per4ft.c.
__T1_ti_sysbios_utils_Load_Module_State__taskStartTime ti_sysbios_utils_Load_Module_State_0_taskStartTime__A
Initial value:
= {
    (xdc_UInt32)0x0,
}
Definition at line 1616 of file mmw_per4ft.c.
__FAR__ const xdc_SizeT ti_sysbios_utils_Load_Module_State_taskList__O = offsetof(ti_sysbios_utils_Load_Module_State__,Object_field_taskList)
Definition at line 1932 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Object__count ti_sysbios_utils_Load_Object__count__C = 0
Definition at line 6575 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Object__heap ti_sysbios_utils_Load_Object__heap__C = 0
Definition at line 6579 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Object__sizeof ti_sysbios_utils_Load_Object__sizeof__C = 0
Definition at line 6583 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_Object__table ti_sysbios_utils_Load_Object__table__C = 0
Definition at line 6587 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_postUpdate ti_sysbios_utils_Load_postUpdate__C = ((CT__ti_sysbios_utils_Load_postUpdate)0)
Definition at line 6607 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_swiEnabled ti_sysbios_utils_Load_swiEnabled__C = 0
Definition at line 6623 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_taskEnabled ti_sysbios_utils_Load_taskEnabled__C = 1
Definition at line 6627 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_updateInIdle ti_sysbios_utils_Load_updateInIdle__C = 0
Definition at line 6611 of file mmw_per4ft.c.
__FAR__ const CT__ti_sysbios_utils_Load_windowInMs ti_sysbios_utils_Load_windowInMs__C = (xdc_UInt)0x1f4
Definition at line 6615 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_E_assertFailed xdc_runtime_Assert_E_assertFailed__C = (((xdc_runtime_Error_Id)1) << 16 | 0)
Definition at line 6708 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__diagsEnabled xdc_runtime_Assert_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6640 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__diagsIncluded xdc_runtime_Assert_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6644 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__diagsMask xdc_runtime_Assert_Module__diagsMask__C = ((CT__xdc_runtime_Assert_Module__diagsMask)0)
Definition at line 6648 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__gateObj xdc_runtime_Assert_Module__gateObj__C = ((CT__xdc_runtime_Assert_Module__gateObj)0)
Definition at line 6652 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__gatePrms xdc_runtime_Assert_Module__gatePrms__C = ((CT__xdc_runtime_Assert_Module__gatePrms)0)
Definition at line 6656 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__id xdc_runtime_Assert_Module__id__C = (xdc_Bits16)0x1
Definition at line 6660 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerDefined xdc_runtime_Assert_Module__loggerDefined__C = 0
Definition at line 6664 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn0 xdc_runtime_Assert_Module__loggerFxn0__C = ((CT__xdc_runtime_Assert_Module__loggerFxn0)0)
Definition at line 6672 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn1 xdc_runtime_Assert_Module__loggerFxn1__C = ((CT__xdc_runtime_Assert_Module__loggerFxn1)0)
Definition at line 6676 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn2 xdc_runtime_Assert_Module__loggerFxn2__C = ((CT__xdc_runtime_Assert_Module__loggerFxn2)0)
Definition at line 6680 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn4 xdc_runtime_Assert_Module__loggerFxn4__C = ((CT__xdc_runtime_Assert_Module__loggerFxn4)0)
Definition at line 6684 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerFxn8 xdc_runtime_Assert_Module__loggerFxn8__C = ((CT__xdc_runtime_Assert_Module__loggerFxn8)0)
Definition at line 6688 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Module__loggerObj xdc_runtime_Assert_Module__loggerObj__C = ((CT__xdc_runtime_Assert_Module__loggerObj)0)
Definition at line 6668 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Object__count xdc_runtime_Assert_Object__count__C = 0
Definition at line 6692 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Object__heap xdc_runtime_Assert_Object__heap__C = 0
Definition at line 6696 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Object__sizeof xdc_runtime_Assert_Object__sizeof__C = 0
Definition at line 6700 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Assert_Object__table xdc_runtime_Assert_Object__table__C = 0
Definition at line 6704 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_A_initializedParams xdc_runtime_Core_A_initializedParams__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 6785 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__diagsEnabled xdc_runtime_Core_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6717 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__diagsIncluded xdc_runtime_Core_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6721 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__diagsMask xdc_runtime_Core_Module__diagsMask__C = ((CT__xdc_runtime_Core_Module__diagsMask)0)
Definition at line 6725 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__gateObj xdc_runtime_Core_Module__gateObj__C = ((CT__xdc_runtime_Core_Module__gateObj)0)
Definition at line 6729 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__gatePrms xdc_runtime_Core_Module__gatePrms__C = ((CT__xdc_runtime_Core_Module__gatePrms)0)
Definition at line 6733 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__id xdc_runtime_Core_Module__id__C = (xdc_Bits16)0x2
Definition at line 6737 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerDefined xdc_runtime_Core_Module__loggerDefined__C = 0
Definition at line 6741 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn0 xdc_runtime_Core_Module__loggerFxn0__C = ((CT__xdc_runtime_Core_Module__loggerFxn0)0)
Definition at line 6749 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn1 xdc_runtime_Core_Module__loggerFxn1__C = ((CT__xdc_runtime_Core_Module__loggerFxn1)0)
Definition at line 6753 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn2 xdc_runtime_Core_Module__loggerFxn2__C = ((CT__xdc_runtime_Core_Module__loggerFxn2)0)
Definition at line 6757 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn4 xdc_runtime_Core_Module__loggerFxn4__C = ((CT__xdc_runtime_Core_Module__loggerFxn4)0)
Definition at line 6761 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerFxn8 xdc_runtime_Core_Module__loggerFxn8__C = ((CT__xdc_runtime_Core_Module__loggerFxn8)0)
Definition at line 6765 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Module__loggerObj xdc_runtime_Core_Module__loggerObj__C = ((CT__xdc_runtime_Core_Module__loggerObj)0)
Definition at line 6745 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Object__count xdc_runtime_Core_Object__count__C = 0
Definition at line 6769 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Object__heap xdc_runtime_Core_Object__heap__C = 0
Definition at line 6773 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Object__sizeof xdc_runtime_Core_Object__sizeof__C = 0
Definition at line 6777 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Core_Object__table xdc_runtime_Core_Object__table__C = 0
Definition at line 6781 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsEnabled xdc_runtime_Defaults_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6794 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsIncluded xdc_runtime_Defaults_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6798 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__diagsMask xdc_runtime_Defaults_Module__diagsMask__C = ((CT__xdc_runtime_Defaults_Module__diagsMask)0)
Definition at line 6802 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__gateObj xdc_runtime_Defaults_Module__gateObj__C = ((CT__xdc_runtime_Defaults_Module__gateObj)0)
Definition at line 6806 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__gatePrms xdc_runtime_Defaults_Module__gatePrms__C = ((CT__xdc_runtime_Defaults_Module__gatePrms)0)
Definition at line 6810 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__id xdc_runtime_Defaults_Module__id__C = (xdc_Bits16)0x3
Definition at line 6814 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerDefined xdc_runtime_Defaults_Module__loggerDefined__C = 0
Definition at line 6818 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn0 xdc_runtime_Defaults_Module__loggerFxn0__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn0)0)
Definition at line 6826 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn1 xdc_runtime_Defaults_Module__loggerFxn1__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn1)0)
Definition at line 6830 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn2 xdc_runtime_Defaults_Module__loggerFxn2__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn2)0)
Definition at line 6834 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn4 xdc_runtime_Defaults_Module__loggerFxn4__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn4)0)
Definition at line 6838 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerFxn8 xdc_runtime_Defaults_Module__loggerFxn8__C = ((CT__xdc_runtime_Defaults_Module__loggerFxn8)0)
Definition at line 6842 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Module__loggerObj xdc_runtime_Defaults_Module__loggerObj__C = ((CT__xdc_runtime_Defaults_Module__loggerObj)0)
Definition at line 6822 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Object__count xdc_runtime_Defaults_Object__count__C = 0
Definition at line 6846 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Object__heap xdc_runtime_Defaults_Object__heap__C = 0
Definition at line 6850 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Object__sizeof xdc_runtime_Defaults_Object__sizeof__C = 0
Definition at line 6854 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Defaults_Object__table xdc_runtime_Defaults_Object__table__C = 0
Definition at line 6858 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_dictBase xdc_runtime_Diags_dictBase__C = ((CT__xdc_runtime_Diags_dictBase)0)
Definition at line 6939 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__diagsEnabled xdc_runtime_Diags_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 6867 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__diagsIncluded xdc_runtime_Diags_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 6871 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__diagsMask xdc_runtime_Diags_Module__diagsMask__C = ((CT__xdc_runtime_Diags_Module__diagsMask)0)
Definition at line 6875 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__gateObj xdc_runtime_Diags_Module__gateObj__C = ((CT__xdc_runtime_Diags_Module__gateObj)0)
Definition at line 6879 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__gatePrms xdc_runtime_Diags_Module__gatePrms__C = ((CT__xdc_runtime_Diags_Module__gatePrms)0)
Definition at line 6883 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__id xdc_runtime_Diags_Module__id__C = (xdc_Bits16)0x4
Definition at line 6887 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerDefined xdc_runtime_Diags_Module__loggerDefined__C = 0
Definition at line 6891 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn0 xdc_runtime_Diags_Module__loggerFxn0__C = ((CT__xdc_runtime_Diags_Module__loggerFxn0)0)
Definition at line 6899 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn1 xdc_runtime_Diags_Module__loggerFxn1__C = ((CT__xdc_runtime_Diags_Module__loggerFxn1)0)
Definition at line 6903 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn2 xdc_runtime_Diags_Module__loggerFxn2__C = ((CT__xdc_runtime_Diags_Module__loggerFxn2)0)
Definition at line 6907 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn4 xdc_runtime_Diags_Module__loggerFxn4__C = ((CT__xdc_runtime_Diags_Module__loggerFxn4)0)
Definition at line 6911 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerFxn8 xdc_runtime_Diags_Module__loggerFxn8__C = ((CT__xdc_runtime_Diags_Module__loggerFxn8)0)
Definition at line 6915 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Module__loggerObj xdc_runtime_Diags_Module__loggerObj__C = ((CT__xdc_runtime_Diags_Module__loggerObj)0)
Definition at line 6895 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Object__count xdc_runtime_Diags_Object__count__C = 0
Definition at line 6919 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Object__heap xdc_runtime_Diags_Object__heap__C = 0
Definition at line 6923 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Object__sizeof xdc_runtime_Diags_Object__sizeof__C = 0
Definition at line 6927 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_Object__table xdc_runtime_Diags_Object__table__C = 0
Definition at line 6931 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Diags_setMaskEnabled xdc_runtime_Diags_setMaskEnabled__C = 0
Definition at line 6935 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_E_generic xdc_runtime_Error_E_generic__C = (((xdc_runtime_Error_Id)2) << 16 | 0)
Definition at line 7035 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_E_memory xdc_runtime_Error_E_memory__C = (((xdc_runtime_Error_Id)3) << 16 | 0)
Definition at line 7039 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_E_msgCode xdc_runtime_Error_E_msgCode__C = (((xdc_runtime_Error_Id)4) << 16 | 0)
Definition at line 7043 of file mmw_per4ft.c.
xdc_runtime_Error_Block xdc_runtime_Error_IgnoreBlock
Initial value:
= {
    ~0,
    {
        {0, 0}
    },
    0,
    0,
    {
        0,
        0,
        0
    }
}
Definition at line 1989 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_maxDepth xdc_runtime_Error_maxDepth__C = (xdc_UInt16)0x10
Definition at line 7055 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__diagsEnabled xdc_runtime_Error_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 6963 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__diagsIncluded xdc_runtime_Error_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 6967 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__diagsMask xdc_runtime_Error_Module__diagsMask__C = ((CT__xdc_runtime_Error_Module__diagsMask)0)
Definition at line 6971 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__gateObj xdc_runtime_Error_Module__gateObj__C = ((CT__xdc_runtime_Error_Module__gateObj)0)
Definition at line 6975 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__gatePrms xdc_runtime_Error_Module__gatePrms__C = ((CT__xdc_runtime_Error_Module__gatePrms)0)
Definition at line 6979 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__id xdc_runtime_Error_Module__id__C = (xdc_Bits16)0x5
Definition at line 6983 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerDefined xdc_runtime_Error_Module__loggerDefined__C = 0
Definition at line 6987 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn0 xdc_runtime_Error_Module__loggerFxn0__C = ((CT__xdc_runtime_Error_Module__loggerFxn0)0)
Definition at line 6995 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn1 xdc_runtime_Error_Module__loggerFxn1__C = ((CT__xdc_runtime_Error_Module__loggerFxn1)0)
Definition at line 6999 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn2 xdc_runtime_Error_Module__loggerFxn2__C = ((CT__xdc_runtime_Error_Module__loggerFxn2)0)
Definition at line 7003 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn4 xdc_runtime_Error_Module__loggerFxn4__C = ((CT__xdc_runtime_Error_Module__loggerFxn4)0)
Definition at line 7007 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerFxn8 xdc_runtime_Error_Module__loggerFxn8__C = ((CT__xdc_runtime_Error_Module__loggerFxn8)0)
Definition at line 7011 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Module__loggerObj xdc_runtime_Error_Module__loggerObj__C = ((CT__xdc_runtime_Error_Module__loggerObj)0)
Definition at line 6991 of file mmw_per4ft.c.
xdc_runtime_Error_Module_State__ xdc_runtime_Error_Module__state__V
Initial value:
= {
    (xdc_UInt16)0x0,
}
Definition at line 1658 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Object__count xdc_runtime_Error_Object__count__C = 0
Definition at line 7015 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Object__heap xdc_runtime_Error_Object__heap__C = 0
Definition at line 7019 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Object__sizeof xdc_runtime_Error_Object__sizeof__C = 0
Definition at line 7023 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_Object__table xdc_runtime_Error_Object__table__C = 0
Definition at line 7027 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_policy xdc_runtime_Error_policy__C = xdc_runtime_Error_UNWIND
Definition at line 7047 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_policyFxn xdc_runtime_Error_policyFxn__C = ((CT__xdc_runtime_Error_policyFxn)((xdc_Fxn)xdc_runtime_Error_policyDefault__E))
Definition at line 7031 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Error_raiseHook xdc_runtime_Error_raiseHook__C = ((CT__xdc_runtime_Error_raiseHook)((xdc_Fxn)ti_sysbios_BIOS_errorRaiseHook__I))
Definition at line 7051 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__diagsEnabled xdc_runtime_Gate_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7064 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__diagsIncluded xdc_runtime_Gate_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7068 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__diagsMask xdc_runtime_Gate_Module__diagsMask__C = ((CT__xdc_runtime_Gate_Module__diagsMask)0)
Definition at line 7072 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__gateObj xdc_runtime_Gate_Module__gateObj__C = ((CT__xdc_runtime_Gate_Module__gateObj)0)
Definition at line 7076 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__gatePrms xdc_runtime_Gate_Module__gatePrms__C = ((CT__xdc_runtime_Gate_Module__gatePrms)0)
Definition at line 7080 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__id xdc_runtime_Gate_Module__id__C = (xdc_Bits16)0x6
Definition at line 7084 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerDefined xdc_runtime_Gate_Module__loggerDefined__C = 0
Definition at line 7088 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn0 xdc_runtime_Gate_Module__loggerFxn0__C = ((CT__xdc_runtime_Gate_Module__loggerFxn0)0)
Definition at line 7096 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn1 xdc_runtime_Gate_Module__loggerFxn1__C = ((CT__xdc_runtime_Gate_Module__loggerFxn1)0)
Definition at line 7100 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn2 xdc_runtime_Gate_Module__loggerFxn2__C = ((CT__xdc_runtime_Gate_Module__loggerFxn2)0)
Definition at line 7104 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn4 xdc_runtime_Gate_Module__loggerFxn4__C = ((CT__xdc_runtime_Gate_Module__loggerFxn4)0)
Definition at line 7108 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerFxn8 xdc_runtime_Gate_Module__loggerFxn8__C = ((CT__xdc_runtime_Gate_Module__loggerFxn8)0)
Definition at line 7112 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Module__loggerObj xdc_runtime_Gate_Module__loggerObj__C = ((CT__xdc_runtime_Gate_Module__loggerObj)0)
Definition at line 7092 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Object__count xdc_runtime_Gate_Object__count__C = 0
Definition at line 7116 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Object__heap xdc_runtime_Gate_Object__heap__C = 0
Definition at line 7120 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Object__sizeof xdc_runtime_Gate_Object__sizeof__C = 0
Definition at line 7124 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Gate_Object__table xdc_runtime_Gate_Object__table__C = 0
Definition at line 7128 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IFilterLogger_Interface__BASE__C = {&xdc_runtime_ILogger_Interface__BASE__C}
Definition at line 896 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IGateProvider_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 893 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IHeap_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 881 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ILogger_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 899 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_IModule_Interface__BASE__C = {0}
Definition at line 902 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ISystemSupport_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 887 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ITimestampClient_Interface__BASE__C = {&xdc_runtime_IModule_Interface__BASE__C}
Definition at line 905 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Types_Base xdc_runtime_ITimestampProvider_Interface__BASE__C = {&xdc_runtime_ITimestampClient_Interface__BASE__C}
Definition at line 890 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_construct xdc_runtime_Log_L_construct__C = (((xdc_runtime_Log_Event)1) << 16 | 4)
Definition at line 7205 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_create xdc_runtime_Log_L_create__C = (((xdc_runtime_Log_Event)2) << 16 | 4)
Definition at line 7209 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_delete xdc_runtime_Log_L_delete__C = (((xdc_runtime_Log_Event)4) << 16 | 4)
Definition at line 7217 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_destruct xdc_runtime_Log_L_destruct__C = (((xdc_runtime_Log_Event)3) << 16 | 4)
Definition at line 7213 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_error xdc_runtime_Log_L_error__C = (((xdc_runtime_Log_Event)5) << 16 | 192)
Definition at line 7221 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_info xdc_runtime_Log_L_info__C = (((xdc_runtime_Log_Event)7) << 16 | 16384)
Definition at line 7229 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_start xdc_runtime_Log_L_start__C = (((xdc_runtime_Log_Event)8) << 16 | 32768)
Definition at line 7233 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_startInstance xdc_runtime_Log_L_startInstance__C = (((xdc_runtime_Log_Event)10) << 16 | 32768)
Definition at line 7241 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_stop xdc_runtime_Log_L_stop__C = (((xdc_runtime_Log_Event)9) << 16 | 32768)
Definition at line 7237 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_stopInstance xdc_runtime_Log_L_stopInstance__C = (((xdc_runtime_Log_Event)11) << 16 | 32768)
Definition at line 7245 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_L_warning xdc_runtime_Log_L_warning__C = (((xdc_runtime_Log_Event)6) << 16 | 224)
Definition at line 7225 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__diagsEnabled xdc_runtime_Log_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7137 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__diagsIncluded xdc_runtime_Log_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7141 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__diagsMask xdc_runtime_Log_Module__diagsMask__C = ((CT__xdc_runtime_Log_Module__diagsMask)0)
Definition at line 7145 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__gateObj xdc_runtime_Log_Module__gateObj__C = ((CT__xdc_runtime_Log_Module__gateObj)0)
Definition at line 7149 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__gatePrms xdc_runtime_Log_Module__gatePrms__C = ((CT__xdc_runtime_Log_Module__gatePrms)0)
Definition at line 7153 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__id xdc_runtime_Log_Module__id__C = (xdc_Bits16)0x7
Definition at line 7157 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerDefined xdc_runtime_Log_Module__loggerDefined__C = 0
Definition at line 7161 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn0 xdc_runtime_Log_Module__loggerFxn0__C = ((CT__xdc_runtime_Log_Module__loggerFxn0)0)
Definition at line 7169 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn1 xdc_runtime_Log_Module__loggerFxn1__C = ((CT__xdc_runtime_Log_Module__loggerFxn1)0)
Definition at line 7173 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn2 xdc_runtime_Log_Module__loggerFxn2__C = ((CT__xdc_runtime_Log_Module__loggerFxn2)0)
Definition at line 7177 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn4 xdc_runtime_Log_Module__loggerFxn4__C = ((CT__xdc_runtime_Log_Module__loggerFxn4)0)
Definition at line 7181 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerFxn8 xdc_runtime_Log_Module__loggerFxn8__C = ((CT__xdc_runtime_Log_Module__loggerFxn8)0)
Definition at line 7185 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Module__loggerObj xdc_runtime_Log_Module__loggerObj__C = ((CT__xdc_runtime_Log_Module__loggerObj)0)
Definition at line 7165 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Object__count xdc_runtime_Log_Object__count__C = 0
Definition at line 7189 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Object__heap xdc_runtime_Log_Object__heap__C = 0
Definition at line 7193 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Object__sizeof xdc_runtime_Log_Object__sizeof__C = 0
Definition at line 7197 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Log_Object__table xdc_runtime_Log_Object__table__C = 0
Definition at line 7201 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_E_badLevel xdc_runtime_LoggerBuf_E_badLevel__C = (((xdc_runtime_Error_Id)5) << 16 | 0)
Definition at line 7389 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_enableFlush xdc_runtime_LoggerBuf_enableFlush__C = 0
Definition at line 7393 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_filterByLevel xdc_runtime_LoggerBuf_filterByLevel__C = 0
Definition at line 7385 of file mmw_per4ft.c.
__T1_xdc_runtime_LoggerBuf_Instance_State__entryArr xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A
Definition at line 1676 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_level1Mask xdc_runtime_LoggerBuf_level1Mask__C = (xdc_Bits16)0x0
Definition at line 7401 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_level2Mask xdc_runtime_LoggerBuf_level2Mask__C = (xdc_Bits16)0x0
Definition at line 7405 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_level3Mask xdc_runtime_LoggerBuf_level3Mask__C = (xdc_Bits16)0x0
Definition at line 7409 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_level4Mask xdc_runtime_LoggerBuf_level4Mask__C = (xdc_Bits16)0xff87
Definition at line 7413 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsEnabled xdc_runtime_LoggerBuf_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7317 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsIncluded xdc_runtime_LoggerBuf_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7321 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__diagsMask xdc_runtime_LoggerBuf_Module__diagsMask__C = ((CT__xdc_runtime_LoggerBuf_Module__diagsMask)0)
Definition at line 7325 of file mmw_per4ft.c.
const xdc_runtime_LoggerBuf_Fxns__ xdc_runtime_LoggerBuf_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_IFilterLogger_Interface__BASE__C,
    &xdc_runtime_LoggerBuf_Module__FXNS__C.__sfxns,
    xdc_runtime_LoggerBuf_enable__E,
    xdc_runtime_LoggerBuf_disable__E,
    xdc_runtime_LoggerBuf_write0__E,
    xdc_runtime_LoggerBuf_write1__E,
    xdc_runtime_LoggerBuf_write2__E,
    xdc_runtime_LoggerBuf_write4__E,
    xdc_runtime_LoggerBuf_write8__E,
    xdc_runtime_LoggerBuf_setFilterLevel__E,
    xdc_runtime_LoggerBuf_getFilterLevel__E,
    {
        xdc_runtime_LoggerBuf_Object__create__S,
        xdc_runtime_LoggerBuf_Object__delete__S,
        xdc_runtime_LoggerBuf_Handle__label__S,
        0x8,
    }
}
Definition at line 1026 of file mmw_per4ft.c.
Referenced by xdc_runtime_Timestamp_SupportProxy_getFreq__E().
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__gateObj xdc_runtime_LoggerBuf_Module__gateObj__C = ((CT__xdc_runtime_LoggerBuf_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7329 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__gatePrms xdc_runtime_LoggerBuf_Module__gatePrms__C = ((CT__xdc_runtime_LoggerBuf_Module__gatePrms)0)
Definition at line 7333 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__id xdc_runtime_LoggerBuf_Module__id__C = (xdc_Bits16)0x8
Definition at line 7337 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerDefined xdc_runtime_LoggerBuf_Module__loggerDefined__C = 0
Definition at line 7341 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn0 xdc_runtime_LoggerBuf_Module__loggerFxn0__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn0)0)
Definition at line 7349 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn1 xdc_runtime_LoggerBuf_Module__loggerFxn1__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn1)0)
Definition at line 7353 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn2 xdc_runtime_LoggerBuf_Module__loggerFxn2__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn2)0)
Definition at line 7357 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn4 xdc_runtime_LoggerBuf_Module__loggerFxn4__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn4)0)
Definition at line 7361 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerFxn8 xdc_runtime_LoggerBuf_Module__loggerFxn8__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerFxn8)0)
Definition at line 7365 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Module__loggerObj xdc_runtime_LoggerBuf_Module__loggerObj__C = ((CT__xdc_runtime_LoggerBuf_Module__loggerObj)0)
Definition at line 7345 of file mmw_per4ft.c.
xdc_runtime_LoggerBuf_Module__ xdc_runtime_LoggerBuf_Module__root__V
Initial value:
= {
    {&xdc_runtime_LoggerBuf_Module__root__V.link,
    &xdc_runtime_LoggerBuf_Module__root__V.link},
}
Definition at line 7276 of file mmw_per4ft.c.
xdc_runtime_LoggerBuf_Module_State__ xdc_runtime_LoggerBuf_Module__state__V
Initial value:
= {
    (xdc_Bits16)0x0,
    (xdc_Bits16)0x0,
    (xdc_Bits16)0x0,
}
Definition at line 1689 of file mmw_per4ft.c.
xdc_runtime_LoggerBuf_Module_GateProxy_Module__ xdc_runtime_LoggerBuf_Module_GateProxy_Module__root__V
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__count xdc_runtime_LoggerBuf_Object__count__C = 1
Definition at line 7369 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_Core_ObjDesc xdc_runtime_LoggerBuf_Object__DESC__C
Initial value:
= {
    (xdc_CPtr)&xdc_runtime_LoggerBuf_Module__FXNS__C,
    &xdc_runtime_LoggerBuf_Module__root__V.link,
    sizeof(xdc_runtime_LoggerBuf___S1) - sizeof(xdc_runtime_LoggerBuf_Object2__),
    0,
    0,
    sizeof(xdc_runtime_LoggerBuf_Object2__),
    (xdc_CPtr)&xdc_runtime_LoggerBuf_Object__PARAMS__C,
    sizeof(xdc_runtime_LoggerBuf_Params),
}
Definition at line 7253 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__heap xdc_runtime_LoggerBuf_Object__heap__C = 0
Definition at line 7373 of file mmw_per4ft.c.
__FAR__ const xdc_runtime_LoggerBuf_Params xdc_runtime_LoggerBuf_Object__PARAMS__C
Initial value:
= {
    sizeof (xdc_runtime_LoggerBuf_Params),
    0,
    0,
    (xdc_runtime_IInstance_Params*)&xdc_runtime_LoggerBuf_Object__PARAMS__C.__iprms,
    (xdc_UInt)0x40,
    xdc_runtime_LoggerBuf_BufType_CIRCULAR,
    0,
    0,
    {
        sizeof (xdc_runtime_IInstance_Params),
        0,
    },
}
Definition at line 7257 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__sizeof xdc_runtime_LoggerBuf_Object__sizeof__C = sizeof(xdc_runtime_LoggerBuf_Object__)
Definition at line 7377 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_Object__table xdc_runtime_LoggerBuf_Object__table__C = xdc_runtime_LoggerBuf_Object__table__V
Definition at line 7381 of file mmw_per4ft.c.
xdc_runtime_LoggerBuf_Object__ xdc_runtime_LoggerBuf_Object__table__V
Initial value:
= {
    {
        &xdc_runtime_LoggerBuf_Module__FXNS__C,
        0,
        ((void*)xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A),
        ((xdc_runtime_LoggerBuf_Entry*)(&xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A[0])),
        ((xdc_runtime_LoggerBuf_Entry*)(&xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A[199])),
        ((xdc_runtime_LoggerBuf_Entry*)(&xdc_runtime_LoggerBuf_Instance_State_0_entryArr__A[0])),
        (xdc_Bits32)0x1,
        (xdc_UInt16)0xc8,
        (xdc_Int8)0x0,
        0,
        0,
    },
}
Definition at line 1679 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_LoggerBuf_statusLogger xdc_runtime_LoggerBuf_statusLogger__C = 0
Definition at line 7397 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__diagsEnabled xdc_runtime_Main_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7437 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__diagsIncluded xdc_runtime_Main_Module__diagsIncluded__C = (xdc_Bits32)0x190
Definition at line 7441 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__diagsMask xdc_runtime_Main_Module__diagsMask__C = ((CT__xdc_runtime_Main_Module__diagsMask)((void*)&xdc_runtime_Main_Module__root__V.mask))
Definition at line 7445 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__gateObj xdc_runtime_Main_Module__gateObj__C = ((CT__xdc_runtime_Main_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7449 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__gatePrms xdc_runtime_Main_Module__gatePrms__C = ((CT__xdc_runtime_Main_Module__gatePrms)0)
Definition at line 7453 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__id xdc_runtime_Main_Module__id__C = (xdc_Bits16)0x9
Definition at line 7457 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerDefined xdc_runtime_Main_Module__loggerDefined__C = 1
Definition at line 7461 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn0 xdc_runtime_Main_Module__loggerFxn0__C = ((CT__xdc_runtime_Main_Module__loggerFxn0)((xdc_Fxn)xdc_runtime_LoggerBuf_write0))
Definition at line 7469 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn1 xdc_runtime_Main_Module__loggerFxn1__C = ((CT__xdc_runtime_Main_Module__loggerFxn1)((xdc_Fxn)xdc_runtime_LoggerBuf_write1))
Definition at line 7473 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn2 xdc_runtime_Main_Module__loggerFxn2__C = ((CT__xdc_runtime_Main_Module__loggerFxn2)((xdc_Fxn)xdc_runtime_LoggerBuf_write2))
Definition at line 7477 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn4 xdc_runtime_Main_Module__loggerFxn4__C = ((CT__xdc_runtime_Main_Module__loggerFxn4)((xdc_Fxn)xdc_runtime_LoggerBuf_write4))
Definition at line 7481 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerFxn8 xdc_runtime_Main_Module__loggerFxn8__C = ((CT__xdc_runtime_Main_Module__loggerFxn8)((xdc_Fxn)xdc_runtime_LoggerBuf_write8))
Definition at line 7485 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Module__loggerObj xdc_runtime_Main_Module__loggerObj__C = ((CT__xdc_runtime_Main_Module__loggerObj)((const void*)(xdc_runtime_ILogger_Handle)&xdc_runtime_LoggerBuf_Object__table__V[0]))
Definition at line 7465 of file mmw_per4ft.c.
xdc_runtime_Main_Module__ xdc_runtime_Main_Module__root__V
Initial value:
= {
    256,
}
Definition at line 7431 of file mmw_per4ft.c.
xdc_runtime_Main_Module_GateProxy_Module__ xdc_runtime_Main_Module_GateProxy_Module__root__V
__FAR__ const CT__xdc_runtime_Main_Object__count xdc_runtime_Main_Object__count__C = 0
Definition at line 7489 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Object__heap xdc_runtime_Main_Object__heap__C = 0
Definition at line 7493 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Object__sizeof xdc_runtime_Main_Object__sizeof__C = 0
Definition at line 7497 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Main_Object__table xdc_runtime_Main_Object__table__C = 0
Definition at line 7501 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_defaultHeapInstance xdc_runtime_Memory_defaultHeapInstance__C = (xdc_runtime_IHeap_Handle)&ti_sysbios_heaps_HeapMem_Object__table__V[0]
Definition at line 7598 of file mmw_per4ft.c.
xdc_runtime_Memory_HeapProxy_Module__ xdc_runtime_Memory_HeapProxy_Module__root__V
__FAR__ const CT__xdc_runtime_Memory_Module__diagsEnabled xdc_runtime_Memory_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7530 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__diagsIncluded xdc_runtime_Memory_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7534 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__diagsMask xdc_runtime_Memory_Module__diagsMask__C = ((CT__xdc_runtime_Memory_Module__diagsMask)0)
Definition at line 7538 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__gateObj xdc_runtime_Memory_Module__gateObj__C = ((CT__xdc_runtime_Memory_Module__gateObj)0)
Definition at line 7542 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__gatePrms xdc_runtime_Memory_Module__gatePrms__C = ((CT__xdc_runtime_Memory_Module__gatePrms)0)
Definition at line 7546 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__id xdc_runtime_Memory_Module__id__C = (xdc_Bits16)0xa
Definition at line 7550 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerDefined xdc_runtime_Memory_Module__loggerDefined__C = 0
Definition at line 7554 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn0 xdc_runtime_Memory_Module__loggerFxn0__C = ((CT__xdc_runtime_Memory_Module__loggerFxn0)0)
Definition at line 7562 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn1 xdc_runtime_Memory_Module__loggerFxn1__C = ((CT__xdc_runtime_Memory_Module__loggerFxn1)0)
Definition at line 7566 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn2 xdc_runtime_Memory_Module__loggerFxn2__C = ((CT__xdc_runtime_Memory_Module__loggerFxn2)0)
Definition at line 7570 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn4 xdc_runtime_Memory_Module__loggerFxn4__C = ((CT__xdc_runtime_Memory_Module__loggerFxn4)0)
Definition at line 7574 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerFxn8 xdc_runtime_Memory_Module__loggerFxn8__C = ((CT__xdc_runtime_Memory_Module__loggerFxn8)0)
Definition at line 7578 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Module__loggerObj xdc_runtime_Memory_Module__loggerObj__C = ((CT__xdc_runtime_Memory_Module__loggerObj)0)
Definition at line 7558 of file mmw_per4ft.c.
xdc_runtime_Memory_Module_State__ xdc_runtime_Memory_Module__state__V
Initial value:
= {
    (xdc_SizeT)0x8,
}
Definition at line 1722 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Object__count xdc_runtime_Memory_Object__count__C = 0
Definition at line 7582 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Object__heap xdc_runtime_Memory_Object__heap__C = 0
Definition at line 7586 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Object__sizeof xdc_runtime_Memory_Object__sizeof__C = 0
Definition at line 7590 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Memory_Object__table xdc_runtime_Memory_Object__table__C = 0
Definition at line 7594 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__diagsEnabled xdc_runtime_Registry_Module__diagsEnabled__C = (xdc_Bits32)0x90
Definition at line 7628 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__diagsIncluded xdc_runtime_Registry_Module__diagsIncluded__C = (xdc_Bits32)0x90
Definition at line 7632 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__diagsMask xdc_runtime_Registry_Module__diagsMask__C = ((CT__xdc_runtime_Registry_Module__diagsMask)0)
Definition at line 7636 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__gateObj xdc_runtime_Registry_Module__gateObj__C = ((CT__xdc_runtime_Registry_Module__gateObj)0)
Definition at line 7640 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__gatePrms xdc_runtime_Registry_Module__gatePrms__C = ((CT__xdc_runtime_Registry_Module__gatePrms)0)
Definition at line 7644 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__id xdc_runtime_Registry_Module__id__C = (xdc_Bits16)0xb
Definition at line 7648 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerDefined xdc_runtime_Registry_Module__loggerDefined__C = 0
Definition at line 7652 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn0 xdc_runtime_Registry_Module__loggerFxn0__C = ((CT__xdc_runtime_Registry_Module__loggerFxn0)0)
Definition at line 7660 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn1 xdc_runtime_Registry_Module__loggerFxn1__C = ((CT__xdc_runtime_Registry_Module__loggerFxn1)0)
Definition at line 7664 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn2 xdc_runtime_Registry_Module__loggerFxn2__C = ((CT__xdc_runtime_Registry_Module__loggerFxn2)0)
Definition at line 7668 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn4 xdc_runtime_Registry_Module__loggerFxn4__C = ((CT__xdc_runtime_Registry_Module__loggerFxn4)0)
Definition at line 7672 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerFxn8 xdc_runtime_Registry_Module__loggerFxn8__C = ((CT__xdc_runtime_Registry_Module__loggerFxn8)0)
Definition at line 7676 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Module__loggerObj xdc_runtime_Registry_Module__loggerObj__C = ((CT__xdc_runtime_Registry_Module__loggerObj)0)
Definition at line 7656 of file mmw_per4ft.c.
xdc_runtime_Registry_Module_State__ xdc_runtime_Registry_Module__state__V
Initial value:
= {
    ((xdc_runtime_Types_RegDesc*)0),
    (xdc_Bits16)0x7fff,
}
Definition at line 1741 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Object__count xdc_runtime_Registry_Object__count__C = 0
Definition at line 7680 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Object__heap xdc_runtime_Registry_Object__heap__C = 0
Definition at line 7684 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Object__sizeof xdc_runtime_Registry_Object__sizeof__C = 0
Definition at line 7688 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Registry_Object__table xdc_runtime_Registry_Object__table__C = 0
Definition at line 7692 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_execImpl xdc_runtime_Startup_execImpl__C = ((CT__xdc_runtime_Startup_execImpl)((xdc_Fxn)xdc_runtime_Startup_exec__I))
Definition at line 7843 of file mmw_per4ft.c.
const __T1_xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_heaps_HeapMem_init__I)),
    ((xdc_Void(*)(xdc_Void))((xdc_Fxn)ti_sysbios_hal_Hwi_initStack)),
}
Definition at line 1762 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_firstFxns xdc_runtime_Startup_firstFxns__C = {2, ((__T1_xdc_runtime_Startup_firstFxns *)xdc_runtime_Startup_firstFxns__A)}
Definition at line 7831 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_lastFxns xdc_runtime_Startup_lastFxns__C = {0, 0}
Definition at line 7835 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_maxPasses xdc_runtime_Startup_maxPasses__C = (xdc_Int)0x20
Definition at line 7827 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__diagsEnabled xdc_runtime_Startup_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7759 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__diagsIncluded xdc_runtime_Startup_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7763 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__diagsMask xdc_runtime_Startup_Module__diagsMask__C = ((CT__xdc_runtime_Startup_Module__diagsMask)0)
Definition at line 7767 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__gateObj xdc_runtime_Startup_Module__gateObj__C = ((CT__xdc_runtime_Startup_Module__gateObj)0)
Definition at line 7771 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__gatePrms xdc_runtime_Startup_Module__gatePrms__C = ((CT__xdc_runtime_Startup_Module__gatePrms)0)
Definition at line 7775 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__id xdc_runtime_Startup_Module__id__C = (xdc_Bits16)0xc
Definition at line 7779 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerDefined xdc_runtime_Startup_Module__loggerDefined__C = 0
Definition at line 7783 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn0 xdc_runtime_Startup_Module__loggerFxn0__C = ((CT__xdc_runtime_Startup_Module__loggerFxn0)0)
Definition at line 7791 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn1 xdc_runtime_Startup_Module__loggerFxn1__C = ((CT__xdc_runtime_Startup_Module__loggerFxn1)0)
Definition at line 7795 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn2 xdc_runtime_Startup_Module__loggerFxn2__C = ((CT__xdc_runtime_Startup_Module__loggerFxn2)0)
Definition at line 7799 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn4 xdc_runtime_Startup_Module__loggerFxn4__C = ((CT__xdc_runtime_Startup_Module__loggerFxn4)0)
Definition at line 7803 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerFxn8 xdc_runtime_Startup_Module__loggerFxn8__C = ((CT__xdc_runtime_Startup_Module__loggerFxn8)0)
Definition at line 7807 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Module__loggerObj xdc_runtime_Startup_Module__loggerObj__C = ((CT__xdc_runtime_Startup_Module__loggerObj)0)
Definition at line 7787 of file mmw_per4ft.c.
xdc_runtime_Startup_Module_State__ xdc_runtime_Startup_Module__state__V
Initial value:
= {
    ((xdc_Int*)0),
    0,
    0,
}
Definition at line 1756 of file mmw_per4ft.c.
Referenced by ti_sysbios_family_arm_a15_TimestampProvider_Module__startupDone__F(), ti_sysbios_family_arm_exc_Exception_Module__startupDone__F(), ti_sysbios_family_arm_v7a_Pmu_Module__startupDone__F(), ti_sysbios_family_arm_v7r_tms570_Core_Module__startupDone__F(), ti_sysbios_family_arm_v7r_vim_Hwi_Module__startupDone__F(), ti_sysbios_hal_Hwi_Module__startupDone__F(), ti_sysbios_heaps_HeapBuf_Module__startupDone__F(), ti_sysbios_knl_Clock_Module__startupDone__F(), ti_sysbios_knl_Task_Module__startupDone__F(), ti_sysbios_timers_rti_Timer_Module__startupDone__F(), xdc_runtime_LoggerBuf_Module__startupDone__F(), and xdc_runtime_System_Module__startupDone__F().
__FAR__ const CT__xdc_runtime_Startup_Object__count xdc_runtime_Startup_Object__count__C = 0
Definition at line 7811 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Object__heap xdc_runtime_Startup_Object__heap__C = 0
Definition at line 7815 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Object__sizeof xdc_runtime_Startup_Object__sizeof__C = 0
Definition at line 7819 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_Object__table xdc_runtime_Startup_Object__table__C = 0
Definition at line 7823 of file mmw_per4ft.c.
const __T1_xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__A
Initial value:
= {
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
}
Definition at line 1804 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_sfxnRts xdc_runtime_Startup_sfxnRts__C = ((CT__xdc_runtime_Startup_sfxnRts)xdc_runtime_Startup_sfxnRts__A)
Definition at line 7851 of file mmw_per4ft.c.
const __T1_xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__A
Initial value:
= {
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)xdc_runtime_LoggerBuf_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)xdc_runtime_System_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Clock_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_knl_Task_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_heaps_HeapBuf_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_v7r_vim_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_exc_Exception_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_hal_Hwi_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_v7a_Pmu_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_v7r_tms570_Core_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_timers_rti_Timer_Module_startup__E)),
    ((xdc_Int(*)(xdc_Int))((xdc_Fxn)ti_sysbios_family_arm_a15_TimestampProvider_Module_startup__E)),
}
Definition at line 1801 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_sfxnTab xdc_runtime_Startup_sfxnTab__C = ((CT__xdc_runtime_Startup_sfxnTab)xdc_runtime_Startup_sfxnTab__A)
Definition at line 7847 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Startup_startModsFxn xdc_runtime_Startup_startModsFxn__C = ((CT__xdc_runtime_Startup_startModsFxn)((xdc_Fxn)xdc_runtime_Startup_startMods__I))
Definition at line 7839 of file mmw_per4ft.c.
Referenced by xdc_runtime_Startup_exec__I().
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsEnabled xdc_runtime_SysStd_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7860 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsIncluded xdc_runtime_SysStd_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7864 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__diagsMask xdc_runtime_SysStd_Module__diagsMask__C = ((CT__xdc_runtime_SysStd_Module__diagsMask)0)
Definition at line 7868 of file mmw_per4ft.c.
const xdc_runtime_SysStd_Fxns__ xdc_runtime_SysStd_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ISystemSupport_Interface__BASE__C,
    &xdc_runtime_SysStd_Module__FXNS__C.__sfxns,
    xdc_runtime_SysStd_abort__E,
    xdc_runtime_SysStd_exit__E,
    xdc_runtime_SysStd_flush__E,
    xdc_runtime_SysStd_putch__E,
    xdc_runtime_SysStd_ready__E,
    {
        NULL,
        NULL,
        NULL,
        0xe,
    }
}
Definition at line 1053 of file mmw_per4ft.c.
Referenced by xdc_runtime_System_SupportProxy_Proxy__delegate__S().
__FAR__ const CT__xdc_runtime_SysStd_Module__gateObj xdc_runtime_SysStd_Module__gateObj__C = ((CT__xdc_runtime_SysStd_Module__gateObj)0)
Definition at line 7872 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__gatePrms xdc_runtime_SysStd_Module__gatePrms__C = ((CT__xdc_runtime_SysStd_Module__gatePrms)0)
Definition at line 7876 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__id xdc_runtime_SysStd_Module__id__C = (xdc_Bits16)0xe
Definition at line 7880 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerDefined xdc_runtime_SysStd_Module__loggerDefined__C = 0
Definition at line 7884 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn0 xdc_runtime_SysStd_Module__loggerFxn0__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn0)0)
Definition at line 7892 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn1 xdc_runtime_SysStd_Module__loggerFxn1__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn1)0)
Definition at line 7896 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn2 xdc_runtime_SysStd_Module__loggerFxn2__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn2)0)
Definition at line 7900 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn4 xdc_runtime_SysStd_Module__loggerFxn4__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn4)0)
Definition at line 7904 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerFxn8 xdc_runtime_SysStd_Module__loggerFxn8__C = ((CT__xdc_runtime_SysStd_Module__loggerFxn8)0)
Definition at line 7908 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Module__loggerObj xdc_runtime_SysStd_Module__loggerObj__C = ((CT__xdc_runtime_SysStd_Module__loggerObj)0)
Definition at line 7888 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Object__count xdc_runtime_SysStd_Object__count__C = 0
Definition at line 7912 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Object__heap xdc_runtime_SysStd_Object__heap__C = 0
Definition at line 7916 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Object__sizeof xdc_runtime_SysStd_Object__sizeof__C = 0
Definition at line 7920 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_SysStd_Object__table xdc_runtime_SysStd_Object__table__C = 0
Definition at line 7924 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_A_cannotFitIntoArg xdc_runtime_System_A_cannotFitIntoArg__C = (((xdc_runtime_Assert_Id)0) << 16 | 16)
Definition at line 8029 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_abortFxn xdc_runtime_System_abortFxn__C = ((CT__xdc_runtime_System_abortFxn)((xdc_Fxn)xdc_runtime_System_abortStd__E))
Definition at line 8037 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_exitFxn xdc_runtime_System_exitFxn__C = ((CT__xdc_runtime_System_exitFxn)((xdc_Fxn)xdc_runtime_System_exitStd__E))
Definition at line 8041 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_extendFxn xdc_runtime_System_extendFxn__C = ((CT__xdc_runtime_System_extendFxn)((xdc_Fxn)xdc_runtime_System_printfExtend__I))
Definition at line 8045 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_maxAtexitHandlers xdc_runtime_System_maxAtexitHandlers__C = (xdc_Int)0x8
Definition at line 8033 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__diagsEnabled xdc_runtime_System_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 7961 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__diagsIncluded xdc_runtime_System_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 7965 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__diagsMask xdc_runtime_System_Module__diagsMask__C = ((CT__xdc_runtime_System_Module__diagsMask)0)
Definition at line 7969 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__gateObj xdc_runtime_System_Module__gateObj__C = ((CT__xdc_runtime_System_Module__gateObj)((const void*)(xdc_runtime_IGateProvider_Handle)&ti_sysbios_gates_GateHwi_Object__table__V[0]))
Definition at line 7973 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__gatePrms xdc_runtime_System_Module__gatePrms__C = ((CT__xdc_runtime_System_Module__gatePrms)0)
Definition at line 7977 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__id xdc_runtime_System_Module__id__C = (xdc_Bits16)0xd
Definition at line 7981 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerDefined xdc_runtime_System_Module__loggerDefined__C = 0
Definition at line 7985 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn0 xdc_runtime_System_Module__loggerFxn0__C = ((CT__xdc_runtime_System_Module__loggerFxn0)0)
Definition at line 7993 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn1 xdc_runtime_System_Module__loggerFxn1__C = ((CT__xdc_runtime_System_Module__loggerFxn1)0)
Definition at line 7997 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn2 xdc_runtime_System_Module__loggerFxn2__C = ((CT__xdc_runtime_System_Module__loggerFxn2)0)
Definition at line 8001 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn4 xdc_runtime_System_Module__loggerFxn4__C = ((CT__xdc_runtime_System_Module__loggerFxn4)0)
Definition at line 8005 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerFxn8 xdc_runtime_System_Module__loggerFxn8__C = ((CT__xdc_runtime_System_Module__loggerFxn8)0)
Definition at line 8009 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Module__loggerObj xdc_runtime_System_Module__loggerObj__C = ((CT__xdc_runtime_System_Module__loggerObj)0)
Definition at line 7989 of file mmw_per4ft.c.
xdc_runtime_System_Module_State__ xdc_runtime_System_Module__state__V
Initial value:
= {
    ((void*)xdc_runtime_System_Module_State_0_atexitHandlers__A),
    (xdc_Int)0x0,
}
Definition at line 1826 of file mmw_per4ft.c.
xdc_runtime_System_Module_GateProxy_Module__ xdc_runtime_System_Module_GateProxy_Module__root__V
__T1_xdc_runtime_System_Module_State__atexitHandlers xdc_runtime_System_Module_State_0_atexitHandlers__A
Initial value:
= {
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
    ((xdc_Void(*)(xdc_Int))0),
}
Definition at line 1823 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Object__count xdc_runtime_System_Object__count__C = 0
Definition at line 8013 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Object__heap xdc_runtime_System_Object__heap__C = 0
Definition at line 8017 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Object__sizeof xdc_runtime_System_Object__sizeof__C = 0
Definition at line 8021 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_System_Object__table xdc_runtime_System_Object__table__C = 0
Definition at line 8025 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_charCnt xdc_runtime_Text_charCnt__C = (xdc_Int16)0x1
Definition at line 8187 of file mmw_per4ft.c.
const __T1_xdc_runtime_Text_charTab xdc_runtime_Text_charTab__A
Initial value:
= {
    (xdc_Char)0x0,
}
Definition at line 1856 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_charTab xdc_runtime_Text_charTab__C = ((CT__xdc_runtime_Text_charTab)xdc_runtime_Text_charTab__A)
Definition at line 8179 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_isLoaded xdc_runtime_Text_isLoaded__C = 0
Definition at line 8175 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__diagsEnabled xdc_runtime_Text_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8095 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__diagsIncluded xdc_runtime_Text_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8099 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__diagsMask xdc_runtime_Text_Module__diagsMask__C = ((CT__xdc_runtime_Text_Module__diagsMask)0)
Definition at line 8103 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__gateObj xdc_runtime_Text_Module__gateObj__C = ((CT__xdc_runtime_Text_Module__gateObj)0)
Definition at line 8107 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__gatePrms xdc_runtime_Text_Module__gatePrms__C = ((CT__xdc_runtime_Text_Module__gatePrms)0)
Definition at line 8111 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__id xdc_runtime_Text_Module__id__C = (xdc_Bits16)0xf
Definition at line 8115 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerDefined xdc_runtime_Text_Module__loggerDefined__C = 0
Definition at line 8119 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn0 xdc_runtime_Text_Module__loggerFxn0__C = ((CT__xdc_runtime_Text_Module__loggerFxn0)0)
Definition at line 8127 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn1 xdc_runtime_Text_Module__loggerFxn1__C = ((CT__xdc_runtime_Text_Module__loggerFxn1)0)
Definition at line 8131 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn2 xdc_runtime_Text_Module__loggerFxn2__C = ((CT__xdc_runtime_Text_Module__loggerFxn2)0)
Definition at line 8135 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn4 xdc_runtime_Text_Module__loggerFxn4__C = ((CT__xdc_runtime_Text_Module__loggerFxn4)0)
Definition at line 8139 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerFxn8 xdc_runtime_Text_Module__loggerFxn8__C = ((CT__xdc_runtime_Text_Module__loggerFxn8)0)
Definition at line 8143 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Module__loggerObj xdc_runtime_Text_Module__loggerObj__C = ((CT__xdc_runtime_Text_Module__loggerObj)0)
Definition at line 8123 of file mmw_per4ft.c.
xdc_runtime_Text_Module_State__ xdc_runtime_Text_Module__state__V
Initial value:
= {
    ((xdc_CPtr)(&xdc_runtime_Text_charTab__A[0])),
    ((xdc_CPtr)(&xdc_runtime_Text_nodeTab__A[0])),
}
Definition at line 1853 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_nameEmpty xdc_runtime_Text_nameEmpty__C = "{empty-instance-name}"
Definition at line 8167 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_nameStatic xdc_runtime_Text_nameStatic__C = "{static-instance-name}"
Definition at line 8171 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_nameUnknown xdc_runtime_Text_nameUnknown__C = "{unknown-instance-name}"
Definition at line 8163 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_nodeCnt xdc_runtime_Text_nodeCnt__C = (xdc_Int16)0x1
Definition at line 8191 of file mmw_per4ft.c.
const __T1_xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__A
Initial value:
= {
    {
        (xdc_Bits16)0x0,
        (xdc_Bits16)0x0,
    },
}
Definition at line 1859 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_nodeTab xdc_runtime_Text_nodeTab__C = ((CT__xdc_runtime_Text_nodeTab)xdc_runtime_Text_nodeTab__A)
Definition at line 8183 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Object__count xdc_runtime_Text_Object__count__C = 0
Definition at line 8147 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Object__heap xdc_runtime_Text_Object__heap__C = 0
Definition at line 8151 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Object__sizeof xdc_runtime_Text_Object__sizeof__C = 0
Definition at line 8155 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_Object__table xdc_runtime_Text_Object__table__C = 0
Definition at line 8159 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_registryModsLastId xdc_runtime_Text_registryModsLastId__C = (xdc_UInt16)0x7fff
Definition at line 8199 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_unnamedModsLastId xdc_runtime_Text_unnamedModsLastId__C = (xdc_UInt16)0x4000
Definition at line 8195 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_visitRopeFxn2 xdc_runtime_Text_visitRopeFxn2__C = ((CT__xdc_runtime_Text_visitRopeFxn2)((xdc_Fxn)xdc_runtime_Text_visitRope2__I))
Definition at line 8207 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Text_visitRopeFxn xdc_runtime_Text_visitRopeFxn__C = ((CT__xdc_runtime_Text_visitRopeFxn)((xdc_Fxn)xdc_runtime_Text_visitRope__I))
Definition at line 8203 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsEnabled xdc_runtime_Timestamp_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8216 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsIncluded xdc_runtime_Timestamp_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8220 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__diagsMask xdc_runtime_Timestamp_Module__diagsMask__C = ((CT__xdc_runtime_Timestamp_Module__diagsMask)0)
Definition at line 8224 of file mmw_per4ft.c.
const xdc_runtime_Timestamp_Fxns__ xdc_runtime_Timestamp_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ITimestampClient_Interface__BASE__C,
    &xdc_runtime_Timestamp_Module__FXNS__C.__sfxns,
    xdc_runtime_Timestamp_get32__E,
    xdc_runtime_Timestamp_get64__E,
    xdc_runtime_Timestamp_getFreq__E,
    {
        NULL,
        NULL,
        NULL,
        0x10,
    }
}
Definition at line 1076 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__gateObj xdc_runtime_Timestamp_Module__gateObj__C = ((CT__xdc_runtime_Timestamp_Module__gateObj)0)
Definition at line 8228 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__gatePrms xdc_runtime_Timestamp_Module__gatePrms__C = ((CT__xdc_runtime_Timestamp_Module__gatePrms)0)
Definition at line 8232 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__id xdc_runtime_Timestamp_Module__id__C = (xdc_Bits16)0x10
Definition at line 8236 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerDefined xdc_runtime_Timestamp_Module__loggerDefined__C = 0
Definition at line 8240 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn0 xdc_runtime_Timestamp_Module__loggerFxn0__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn0)0)
Definition at line 8248 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn1 xdc_runtime_Timestamp_Module__loggerFxn1__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn1)0)
Definition at line 8252 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn2 xdc_runtime_Timestamp_Module__loggerFxn2__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn2)0)
Definition at line 8256 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn4 xdc_runtime_Timestamp_Module__loggerFxn4__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn4)0)
Definition at line 8260 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerFxn8 xdc_runtime_Timestamp_Module__loggerFxn8__C = ((CT__xdc_runtime_Timestamp_Module__loggerFxn8)0)
Definition at line 8264 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Module__loggerObj xdc_runtime_Timestamp_Module__loggerObj__C = ((CT__xdc_runtime_Timestamp_Module__loggerObj)0)
Definition at line 8244 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Object__count xdc_runtime_Timestamp_Object__count__C = 0
Definition at line 8268 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Object__heap xdc_runtime_Timestamp_Object__heap__C = 0
Definition at line 8272 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Object__sizeof xdc_runtime_Timestamp_Object__sizeof__C = 0
Definition at line 8276 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_Timestamp_Object__table xdc_runtime_Timestamp_Object__table__C = 0
Definition at line 8280 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsEnabled xdc_runtime_TimestampNull_Module__diagsEnabled__C = (xdc_Bits32)0x10
Definition at line 8289 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsIncluded xdc_runtime_TimestampNull_Module__diagsIncluded__C = (xdc_Bits32)0x10
Definition at line 8293 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__diagsMask xdc_runtime_TimestampNull_Module__diagsMask__C = ((CT__xdc_runtime_TimestampNull_Module__diagsMask)0)
Definition at line 8297 of file mmw_per4ft.c.
const xdc_runtime_TimestampNull_Fxns__ xdc_runtime_TimestampNull_Module__FXNS__C
Initial value:
= {
    &xdc_runtime_ITimestampProvider_Interface__BASE__C,
    &xdc_runtime_TimestampNull_Module__FXNS__C.__sfxns,
    xdc_runtime_TimestampNull_get32__E,
    xdc_runtime_TimestampNull_get64__E,
    xdc_runtime_TimestampNull_getFreq__E,
    {
        NULL,
        NULL,
        NULL,
        0x11,
    }
}
Definition at line 1097 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__gateObj xdc_runtime_TimestampNull_Module__gateObj__C = ((CT__xdc_runtime_TimestampNull_Module__gateObj)0)
Definition at line 8301 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__gatePrms xdc_runtime_TimestampNull_Module__gatePrms__C = ((CT__xdc_runtime_TimestampNull_Module__gatePrms)0)
Definition at line 8305 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__id xdc_runtime_TimestampNull_Module__id__C = (xdc_Bits16)0x11
Definition at line 8309 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerDefined xdc_runtime_TimestampNull_Module__loggerDefined__C = 0
Definition at line 8313 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn0 xdc_runtime_TimestampNull_Module__loggerFxn0__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn0)0)
Definition at line 8321 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn1 xdc_runtime_TimestampNull_Module__loggerFxn1__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn1)0)
Definition at line 8325 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn2 xdc_runtime_TimestampNull_Module__loggerFxn2__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn2)0)
Definition at line 8329 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn4 xdc_runtime_TimestampNull_Module__loggerFxn4__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn4)0)
Definition at line 8333 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerFxn8 xdc_runtime_TimestampNull_Module__loggerFxn8__C = ((CT__xdc_runtime_TimestampNull_Module__loggerFxn8)0)
Definition at line 8337 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Module__loggerObj xdc_runtime_TimestampNull_Module__loggerObj__C = ((CT__xdc_runtime_TimestampNull_Module__loggerObj)0)
Definition at line 8317 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Object__count xdc_runtime_TimestampNull_Object__count__C = 0
Definition at line 8341 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Object__heap xdc_runtime_TimestampNull_Object__heap__C = 0
Definition at line 8345 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Object__sizeof xdc_runtime_TimestampNull_Object__sizeof__C = 0
Definition at line 8349 of file mmw_per4ft.c.
__FAR__ const CT__xdc_runtime_TimestampNull_Object__table xdc_runtime_TimestampNull_Object__table__C = 0
Definition at line 8353 of file mmw_per4ft.c.
Copyright 2020, Texas Instruments Incorporated