xwr18xx/mmw/dss/data_path.c File Reference
data_path.c File Reference
Implements Data path processing functionality.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/hwa/hwa.h>
#include <ti/drivers/edma/edma.h>
#include <ti/demo/xwr18xx/mmw/dss/mmw_dss.h>
#include <ti/demo/xwr18xx/mmw/mmw_res.h>
Functions
static void MmwDemo_hwaInit (MmwDemo_DataPathObj *obj)
static void MmwDemo_edmaInit (MmwDemo_DataPathObj *obj)
static void MmwDemo_hwaOpen (MmwDemo_DataPathObj *obj, SOC_Handle socHandle)
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj *obj)
static void MmwDemo_edmaClose (MmwDemo_DataPathObj *obj)
static void MmwDemo_hwaClose (MmwDemo_DataPathObj *obj)
static void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
static void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
void MmwDemo_dataPathInit (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathClose (MmwDemo_DataPathObj *obj)
Variables
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
Implements Data path processing functionality.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file data_path.c.
Function Documentation
void MmwDemo_dataPathClose (MmwDemo_DataPathObj * obj)
Description
This function is called to close data path driver instances.
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 305 of file data_path.c.
References DPM_deinit(), MmwDemo_edmaClose(), MmwDemo_hwaClose(), and MmwDemo_DataPathObj_t::objDetDpmHandle.
void MmwDemo_dataPathInit (MmwDemo_DataPathObj * obj)
Description
This function is called at the init time to initialze data path driver.
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 265 of file data_path.c.
References MmwDemo_edmaInit(), and MmwDemo_hwaInit().
Referenced by MmwDemo_dssInitTask().
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj * obj)
Description
This function is called at the init time to open data path driver instances.
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 286 of file data_path.c.
References MmwDemo_edmaOpen(), MmwDemo_hwaOpen(), and MmwDemo_DSS_MCB_t::socHandle.
Referenced by MmwDemo_dssInitTask().
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo) static
Description
Call back function for EDMA CC (Channel controller) error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 131 of file data_path.c.
References MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_errorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo) static
Description
Call back function for EDMA transfer controller error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 144 of file data_path.c.
References MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_edmaClose (MmwDemo_DataPathObj * obj) static
Description
Close EDMA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 250 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle.
Referenced by MmwDemo_dataPathClose().
void MmwDemo_edmaInit (MmwDemo_DataPathObj * obj) static
Description
EDMA driver init
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 108 of file data_path.c.
References DPC_OBJDET_EDMA_INSTANCE, MmwDemo_DataPathObj_t::EDMA_errorInfo, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathInit().
static void MmwDemo_edmaOpen (MmwDemo_DataPathObj * obj) static
Description
Open EDMA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 209 of file data_path.c.
References DPC_OBJDET_EDMA_INSTANCE, MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_debugAssert, MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Referenced by MmwDemo_dataPathOpen().
static void MmwDemo_hwaClose (MmwDemo_DataPathObj * obj) static
Description
Close HWA driver instance
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 186 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathClose().
static void MmwDemo_hwaInit (MmwDemo_DataPathObj * obj) static
Description
HWA driver init
Parameters
[in] obj Pointer to data path object
Return values
Not Applicable.
Definition at line 92 of file data_path.c.
Referenced by MmwDemo_dataPathInit().
static void MmwDemo_hwaOpen (MmwDemo_DataPathObj * obj, SOC_Handle socHandle) static
Description
Open HWA driver instance
Parameters
[in] obj Pointer to data path object
[in] socHandle SOC driver handle
Return values
Not Applicable.
Definition at line 162 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathOpen().
Variable Documentation
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
HSRAM for processing results
Definition at line 125 of file dss_main.c.
Copyright 2020, Texas Instruments Incorporated