RF Parser Internal Functions
RF Parser Internal Functions
Mmwdemo RFparser Internal
The section has a list of all internal API which are not exposed to the external applications.
Functions
static float MmwDemo_RFParser_getFramePeriod_ms (MMWave_CtrlCfg *ctrlCfg, uint8_t subFrameIndx)
static uint16_t MmwDemo_RFParser_getChirpStartIdx (MMWave_CtrlCfg *ctrlCfg, uint8_t subFrameIndx)
static uint16_t MmwDemo_RFParser_getChirpEndIdx (MMWave_CtrlCfg *ctrlCfg, uint8_t subFrameIndx)
static uint16_t MmwDemo_RFParser_getNumLoops (MMWave_CtrlCfg *ctrlCfg, uint8_t subFrameIndx)
static MMWave_ProfileHandle MmwDemo_RFParser_getProfileHandle (MMWave_CtrlCfg *ctrlCfg, uint32_t profileLoopIdx)
static int32_t MmwDemo_RFParser_setAoAParams (MmwDemo_RFParserOutParams *outParams, bool *pFoundValidProfile, int16_t frameTotalChirps, uint16_t *validChirpTxEnBits, bool bpmEnabled)
static int32_t MmwDemo_RFParser_parseCtrlConfig (MmwDemo_RFParserOutParams *outParams, uint8_t subFrameIdx, MMWave_OpenCfg *openCfg, MMWave_CtrlCfg *ctrlCfg, float rfFreqScaleFactor, bool bpmEnabled)
static int32_t MmwDemo_RFParser_parseADCBufCfg (MmwDemo_RFParserOutParams *outParams, MmwDemo_ADCBufCfg *adcBufCfg)
Detailed Description
The section has a list of all internal API which are not exposed to the external applications.
Function Documentation
static uint16_t MmwDemo_RFParser_getChirpEndIdx (MMWave_CtrlCfg * ctrlCfg, uint8_t subFrameIndx) static
Description
Help Function to get chirp stop Index
Parameters
[in] ctrlCfg Handle to MMWave control configuration
[in] subFrameIndx Sub frame index
Return values
Chirp stop index
Definition at line 271 of file mmwdemo_rfparser.c.
References MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CtrlCfg_t::frameCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MMWave_FrameCfg_t::frameCfg, and MMWave_DFEDataOutputMode_ADVANCED_FRAME.
Referenced by MmwDemo_RFParser_parseCtrlConfig().
static uint16_t MmwDemo_RFParser_getChirpStartIdx (MMWave_CtrlCfg * ctrlCfg, uint8_t subFrameIndx) static
Description
Help Function to get chirp start Index
Parameters
[in] ctrlCfg Handle to MMWave control configuration
[in] subFrameIndx Sub frame index
Return values
Chirp start index
Definition at line 246 of file mmwdemo_rfparser.c.
References MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CtrlCfg_t::frameCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MMWave_FrameCfg_t::frameCfg, and MMWave_DFEDataOutputMode_ADVANCED_FRAME.
Referenced by MmwDemo_RFParser_parseCtrlConfig().
static float MmwDemo_RFParser_getFramePeriod_ms (MMWave_CtrlCfg * ctrlCfg, uint8_t subFrameIndx) static
Description
Help Function to get frame period
Parameters
[in] ctrlCfg Handle to MMWave control configuration
[in] subFrameIndx Sub frame index
Return values
Frame period
Definition at line 220 of file mmwdemo_rfparser.c.
References MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CtrlCfg_t::frameCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MMWave_FrameCfg_t::frameCfg, and MMWave_DFEDataOutputMode_ADVANCED_FRAME.
Referenced by MmwDemo_RFParser_parseCtrlConfig().
static uint16_t MmwDemo_RFParser_getNumLoops (MMWave_CtrlCfg * ctrlCfg, uint8_t subFrameIndx) static
Description
Help Function to get number of loops
Parameters
[in] ctrlCfg Handle to MMWave control configuration
[in] subFrameIndx Sub frame index
Return values
Number of loops
Definition at line 297 of file mmwdemo_rfparser.c.
References MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CtrlCfg_t::frameCfg, MMWave_AdvancedFrameCfg_t::frameCfg, MMWave_FrameCfg_t::frameCfg, and MMWave_DFEDataOutputMode_ADVANCED_FRAME.
Referenced by MmwDemo_RFParser_parseCtrlConfig().
static MMWave_ProfileHandle MmwDemo_RFParser_getProfileHandle (MMWave_CtrlCfg * ctrlCfg, uint32_t profileLoopIdx) static
Description
Help Function to get profile handle
Parameters
[in] ctrlCfg Handle to MMWave control configuration
[in] profileLoopIdx Profile index
Return values
Profile handle
Definition at line 322 of file mmwdemo_rfparser.c.
References MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_CtrlCfg_t::dfeDataOutputMode, MMWave_CtrlCfg_t::frameCfg, MMWave_DFEDataOutputMode_ADVANCED_FRAME, MMWDEMO_RFPARSER_EINVAL__NUM_RX_ANTENNAS, MMWDEMO_RFPARSER_EINVAL__NUM_VIRTUAL_ANTENNAS, MMWDEMO_RFPARSER_EINVAL_NUM_TX_ANTENNAS, MmwDemo_RFParser_setAoAParams(), MmwDemo_RFParserOutParams_t::numRxAntennas, MmwDemo_RFParserOutParams_t::numTxAntennas, MmwDemo_RFParserOutParams_t::numVirtualAntAzim, MmwDemo_RFParserOutParams_t::numVirtualAntElev, MmwDemo_RFParserOutParams_t::numVirtualAntennas, MMWave_AdvancedFrameCfg_t::profileHandle, MMWave_FrameCfg_t::profileHandle, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_RFParserOutParams_t::txAntOrder, and MmwDemo_RFParserOutParams_t::validProfileHasOneTxPerChirp.
Referenced by MmwDemo_RFParser_parseCtrlConfig().
static int32_t MmwDemo_RFParser_parseADCBufCfg (MmwDemo_RFParserOutParams * outParams, MmwDemo_ADCBufCfg * adcBufCfg) static
Description
Helper function that parses ADCBuf configuration to be used to configure ADCBuf driver
Parameters
[out] outParams Pointer to parameters generated after parsing configuration
[in] adcBufCfg Pointer to ADCBuf configuration
Return values
Success - 0 Fail < 0, one of RF Parser Error Codes
Definition at line 951 of file mmwdemo_rfparser.c.
References MmwDemo_RFParserOutParams_t::adcBufChanDataSize, MmwDemo_RFParserHwAttr_t::adcBufSize, MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_ADCBufCfg_t::chirpThreshold, MMWDEMO_RFPARSER_EINVAL__CHIRP_THRESH_GREATER_THAN_MAX_ALLOWED, MMWDEMO_RFPARSER_ENOTSUPPORT__NON_DIVISIBILITY_OF_CHIRP_THRESH, MMWDEMO_RFPARSER_ENOTSUPPORT__NONCOMPLEX_ADC_FORMAT, MmwDemo_RFParser_parseConfig(), MmwDemo_RFParserOutParams_t::numAdcSamples, MmwDemo_RFParserOutParams_t::numChirpsPerChirpEvent, MmwDemo_RFParserOutParams_t::numChirpsPerFrame, MmwDemo_RFParserOutParams_t::numRxAntennas, and SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD.
Referenced by MmwDemo_RFParser_parseConfig(), and MmwDemo_RFParser_parseCtrlConfig().
static int32_t MmwDemo_RFParser_parseCtrlConfig (MmwDemo_RFParserOutParams * outParams, uint8_t subFrameIdx, MMWave_OpenCfg * openCfg, MMWave_CtrlCfg * ctrlCfg, float rfFreqScaleFactor, bool bpmEnabled) static
Description
Helper function that parses Profile, Chirp and Frame config and extracts parameters needed for processing chain configuration
Parameters
[out] outParams Pointer to parameters generated after parsing configuration
[in] subFrameIdx Sub-frame index
[in] openCfg Pointer to the MMWave Open configuration
[in] ctrlCfg Pointer to the MMWave Control configuration
[in] rfFreqScaleFactor RF frequency scale factor, see SOC_getDeviceRFFreqScaleFactor API in SOC driver
[in] bpmEnabled BPM flag, 0 -disabled, 1-enabled
Return values
Success - 0 Fail <0, one of error codes RF Parser Error Codes
Definition at line 696 of file mmwdemo_rfparser.c.
References MMWave_OpenCfg_t::adcOutCfg, MMWave_CtrlCfg_t::advancedFrameCfg, MMWave_OpenCfg_t::chCfg, MmwDemo_RFParserOutParams_t::chirpInterval, MMWave_CtrlCfg_t::dfeDataOutputMode, MmwDemo_RFParserOutParams_t::dopplerResolution, MmwDemo_RFParserOutParams_t::dopplerStep, MMWave_AdvancedFrameCfg_t::frameCfg, MmwDemo_RFParserOutParams_t::framePeriod, MMWave_DFEDataOutputMode_ADVANCED_FRAME, MMWave_getChirpCfg(), MMWave_getChirpHandle(), MMWave_getNumChirps(), MMWave_getProfileCfg(), MMWAVE_MAX_PROFILE, MMWDEMO_RFPARSER_EINVAL__VALID_PROFILECFG_NOT_FOUND, MMWDEMO_RFPARSER_ENOIMPL__NUM_UNIQUE_CHIRPS_MORE_THAN_32, MMWDEMO_RFPARSER_ENOTSUPPORT__NEGATIVE_FREQ_SLOPE, MMWDEMO_RFPARSER_ENOTSUPPORT__NON_16BITS_ADC, MMWDEMO_RFPARSER_ENOTSUPPORT__NON_COMPLEX_ADC_FORMAT, MMWDEMO_RFPARSER_ENOTSUPPORT__NON_ONE_NUMOFBURST_FOR_ADVANCED_FRAME, MmwDemo_RFParser_getChirpEndIdx(), MmwDemo_RFParser_getChirpStartIdx(), MmwDemo_RFParser_getFramePeriod_ms(), MmwDemo_RFParser_getNumLoops(), MmwDemo_RFParser_getProfileHandle(), MmwDemo_RFParser_parseADCBufCfg(), MmwDemo_RFParser_setAoAParams(), MMWDEMO_RFPARSER_SPEED_OF_LIGHT_IN_METERS_PER_SEC, MmwDemo_RFParserOutParams_t::numAdcSamples, MmwDemo_RFParserOutParams_t::numChirpsPerFrame, MmwDemo_RFParserOutParams_t::numDopplerBins, MmwDemo_RFParserOutParams_t::numDopplerChirps, MmwDemo_RFParserOutParams_t::numRangeBins, MmwDemo_RFParserOutParams_t::numRxAntennas, MmwDemo_RFParserOutParams_t::numTxAntennas, MmwDemo_RFParserOutParams_t::numVirtualAntAzim, MmwDemo_RFParserOutParams_t::numVirtualAntElev, MmwDemo_RFParserOutParams_t::rangeResolution, MmwDemo_RFParserOutParams_t::rangeStep, MmwDemo_RFParserOutParams_t::rxAntOrder, SYS_COMMON_NUM_RX_CHANNEL, and MmwDemo_RFParserOutParams_t::validProfileIdx.
Referenced by MmwDemo_RFParser_parseConfig(), and MmwDemo_RFParser_setAoAParams().
static int32_t MmwDemo_RFParser_setAoAParams (MmwDemo_RFParserOutParams * outParams, bool * pFoundValidProfile, int16_t frameTotalChirps, uint16_t * validChirpTxEnBits, bool bpmEnabled) static
Description
Helper function that parses chirp Tx antenna configuration and extracts parameters needed for AoA configuration depending on the AoA DPU needs
Parameters
[in,out] outParams Pointer to parameters generated after parsing configuration
[in,out] pFoundValidProfile flag to indicate if this is valid profile; if not, advance to the next one
[in] frameTotalChirps Total chirps in the frame (used for looping through validChirpTxEnBits)
[in] validChirpTxEnBits Array of chirp's txEn bits. Dimension is provided by frameTotalChirps
[in] bpmEnabled BPM flag, 0 -disabled, 1-enabled
Return values
Success - 0 Fail <0, one of error codes RF Parser Error Codes
Definition at line 487 of file mmwdemo_rfparser.c.
References MmwDemo_RFParserHwAttr_t::azimTxAntMask, MmwDemo_RFParserHwAttr_t::elevTxAntMask, MMWDEMO_RFPARSER_EINVAL__NUM_VIRTUAL_ANTENNAS, MMWDEMO_RFPARSER_EINVAL_NUM_TX_ANTENNAS, MmwDemo_RFParser_parseCtrlConfig(), MmwDemo_RFParserOutParams_t::numRxAntennas, MmwDemo_RFParserOutParams_t::numTxAntennas, MmwDemo_RFParserOutParams_t::numVirtualAntAzim, MmwDemo_RFParserOutParams_t::numVirtualAntElev, MmwDemo_RFParserOutParams_t::numVirtualAntennas, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_RFParserOutParams_t::txAntOrder, and MmwDemo_RFParserOutParams_t::validProfileHasOneTxPerChirp.
Referenced by MmwDemo_RFParser_getProfileHandle(), and MmwDemo_RFParser_parseCtrlConfig().
Copyright 2020, Texas Instruments Incorporated