/*
 *  Copyright 2018 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,0; 7-20-2018 13:58:27; /db/ztree/library/trees/xdctargets/xdctargets-r09/src/ xlibrary

 */

