Object Detection DPC Internal Functions
Object Detection DPC Internal Functions
Object Detection Range HWA only DPC (Data Path Chain) Internal
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Functions
static uint32_t DPC_ObjDetRangeHwa_GetRangeWinGenLen (uint16_t numAdcSamples)
static void DPC_ObjDetRangeHwa_GenRangeWindow (DPU_RangeProcHWA_Config *cfg)
static int32_t DPC_ObjDetRangeHwa_reconfigSubFrame (ObjDetObj *objDetObj, uint8_t subFrameIndx)
static int32_t DPC_ObjDetRangeHwa_rangeConfig (DPU_RangeProcHWA_Handle dpuHandle, DPC_ObjectDetectionRangeHWA_StaticCfg *staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreLocalRamObj, DPU_RangeProcHWA_Config *cfgSave)
static int32_t DPC_ObjDetRangeHwa_preStartConfig (SubFrameObj *subFrmObj, ObjDetObj *objDetObj, DPC_ObjectDetectionRangeHWA_StaticCfg *staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg *dynCfg, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage *memUsage)
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer *ptrResult)
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void *arg, uint32_t argLen)
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg *ptrInitCfg, int32_t *errCode)
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle)
Detailed Description
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Function Documentation
static void DPC_ObjDetRangeHwa_GenRangeWindow (DPU_RangeProcHWA_Config * cfg) static
Description
Generate the range DPU window using mathutils API.
Parameters
[in] cfg Range DPU configuration, output window is generated in window pointer in the staticCfg of this.
Return values
None
Definition at line 291 of file objdetrangehwa.c.
References DPU_RangeProcHWA_StaticConfig_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE, DPC_OBJDET_QFORMAT_RANGE_FFT, DPC_ObjDetRangeHwa_GetRangeWinGenLen(), DPIF_ADCBufProperty_t::numAdcSamples, DPU_RangeProcHWA_Config_t::staticCfg, and DPU_RangeProcHWA_StaticConfig_t::window.
Referenced by DPC_ObjDetRangeHwa_rangeConfig(), and DPC_ObjDetRangeHwa_reconfigSubFrame().
static uint32_t DPC_ObjDetRangeHwa_GetRangeWinGenLen (uint16_t numAdcSamples) static
Description
Computes the length of window to generate for range DPU.
Parameters
[in] numAdcSamples Number of ADC samples
Return values
Length of window to generate
Definition at line 267 of file objdetrangehwa.c.
Referenced by DPC_ObjDetRangeHwa_GenRangeWindow(), and DPC_ObjDetRangeHwa_rangeConfig().
static int32_t DPC_ObjDetRangeHwa_preStartConfig (SubFrameObj * subFrmObj, ObjDetObj * objDetObj, DPC_ObjectDetectionRangeHWA_StaticCfg * staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg * dynCfg, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage * memUsage) static
Description
Performs processing related to pre-start configuration, which is per sub-frame, by configuring each of the DPUs involved in the processing chain. Memory management notes:
Core Local Memory that needs to be preserved across sub-frames (such as range DPU's calib DC buffer) will be allocated using MemoryP_alloc.
Core Local Memory that needs to be preserved within a sub-frame across DPU calls (the DPIF * type memory) or for intermediate private scratch memory for DPU (i.e no preservation is required from process call to process call of the DPUs within the sub-frame) will be allocated from the Core Local RAM configuration supplied in DPC_ObjectDetectionRangeHWA_InitParams given to DPC_ObjectDetection_init API
L3 memory will only be allocated from the L3 RAM configuration supplied in DPC_ObjectDetectionRangeHWA_InitParams given to DPC_ObjectDetection_init API No L3 buffers are presently required that need to be preserved across sub-frames (type described in #1 above), neither are L3 scratch buffers required for intermediate processing within DPU process call.
Parameters
[in] subFrmObj Pointer to sub-frame object
[in] objDetObj Pointer to objDetObj
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[out] memUsage Pointer to memory usage structure to report mmemory usage in this DPC
Return values
Success - 0
Error - <0
Definition at line 565 of file objdetrangehwa.c.
References ObjDetObj_t::CoreLocalRamObj, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::CoreLocalRamUsage, DPIF_RadarCube_t::data, DPIF_RadarCube_t::datafmt, DPIF_RadarCube_t::dataSize, DPC_OBJDETRANGEHWA_ENOMEM__L3_RAM_RADAR_CUBE, DPC_ObjDetRangeHwa_MemPoolAlloc(), DPC_ObjDetRangeHwa_MemPoolGetMaxUsage(), DPC_ObjDetRangeHwa_MemPoolReset(), DPC_OBJDETRANGEHWA_RADAR_CUBE_DATABUF_BYTE_ALIGNMENT, DPC_ObjDetRangeHwa_rangeConfig(), SubFrameObj_t::dpuRangeObj, ObjDetObj_t::edmaHandle, ObjDetObj_t::L3RamObj, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::L3RamUsage, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numDopplerChirps, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numRangeBins, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numVirtualAntennas, DPC_ObjectDetectionRangeHWA_StaticCfg_t::radarCubeFormat, and SubFrameObj_t::rangeCfg.
Referenced by DPC_ObjDetRangeHwa_rangeConfig(), and DPC_ObjectDetection_ioctl().
static int32_t DPC_ObjDetRangeHwa_rangeConfig (DPU_RangeProcHWA_Handle dpuHandle, DPC_ObjectDetectionRangeHWA_StaticCfg * staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, MemPoolObj * CoreLocalRamObj, DPU_RangeProcHWA_Config * cfgSave) static
Description
Configure range DPU.
Parameters
[in] dpuHandle Handle to DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which is output of range processing.
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, only for scratch purposes
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 364 of file objdetrangehwa.c.
References DPU_RangeProcHWA_StaticConfig_t::ADCBufData, DPC_ObjectDetectionRangeHWA_StaticCfg_t::ADCBufData, DPU_RangeProcHWA_DynamicConfig_t::calibDcRangeSigCfg, DPC_ObjectDetectionRangeHWA_DynCfg_t::calibDcRangeSigCfg, DPIF_RadarCube_t::datafmt, DPU_RangeProcHWA_EDMAInputConfig_t::dataIn, DPU_RangeProcHWA_HwaConfig_t::dataInputMode, DPU_RangeProcHWA_EDMAInputConfig_t::dataInSignature, DPU_RangeProcHWA_EDMAOutputConfigFmt2_t::dataOutPing, DPU_RangeProcHWA_EDMAOutputConfigFmt1_t::dataOutPing, DPU_RangeProcHWA_EDMAOutputConfigFmt2_t::dataOutPong, DPU_RangeProcHWA_EDMAOutputConfigFmt1_t::dataOutPong, DPU_RangeProcHWA_EDMAOutputConfig_t::dataOutSignature, DPIF_ADCBufData_t::dataProperty, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMean, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMeanSize, DPC_OBJDETRANGEHWA_ENOMEM__CORE_LOCAL_RAM_RANGE_HWA_WINDOW, DPC_OBJDETRANGEHWA_ENOMEM_HWA_WINDOW_RAM, DPC_ObjDetRangeHwa_GenRangeWindow(), DPC_ObjDetRangeHwa_GetRangeWinGenLen(), DPC_OBJDETRANGEHWA_HWA_MAX_WINDOW_RAM_SIZE_IN_SAMPLES, DPC_ObjDetRangeHwa_MemPoolAlloc(), DPC_ObjDetRangeHwa_preStartConfig(), DPIF_RADARCUBE_FORMAT_1, DPIF_RXCHAN_NON_INTERLEAVE_MODE, DPU_RANGEPROC_SIGNATURE_COMP_MAX_BIN_SIZE, DPU_RangeProcHWA_config(), DPU_RangeProcHWA_InputMode_ISOLATED, DPU_RANGEPROCHWA_NUM_HWA_PARAM_SETS, DPU_RangeProcHWA_Config_t::dynCfg, DPU_RangeProcHWA_HW_Resources_t::edmaHandle, DPU_RangeProcHWA_HW_Resources_t::edmaInCfg, DPU_RangeProcHWA_HW_Resources_t::edmaOutCfg, DPU_RangeProcHWA_FFTtuning_t::fftOutputDivShift, DPU_RangeProcHWA_EDMAOutputConfig_t::fmt1, DPU_RangeProcHWA_EDMAOutputConfig_t::fmt2, DPU_RangeProcHWA_HW_Resources_t::hwaCfg, DPU_RangeProcHWA_HwaConfig_t::hwaWinRamOffset, DPU_RangeProcHWA_HwaConfig_t::hwaWinSym, DPU_RangeProcHWA_Config_t::hwRes, DPIF_ADCBufProperty_t::interleave, DPIF_ADCBufProperty_t::numAdcSamples, DPU_RangeProcHWA_StaticConfig_t::numChirpsPerFrame, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numChirpsPerFrame, DPU_RangeProcHWA_FFTtuning_t::numLastButterflyStagesToScale, DPU_RangeProcHWA_HwaConfig_t::numParamSet, DPU_RangeProcHWA_StaticConfig_t::numRangeBins, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPU_RangeProcHWA_StaticConfig_t::numTxAntennas, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numTxAntennas, DPU_RangeProcHWA_StaticConfig_t::numVirtualAntennas, DPC_ObjectDetectionRangeHWA_StaticCfg_t::numVirtualAntennas, DPU_RangeProcHWA_HwaConfig_t::paramSetStartIdx, DPU_RangeProcHWA_HW_Resources_t::radarCube, DPU_RangeProcHWA_StaticConfig_t::rangeFFTtuning, DPC_ObjectDetectionRangeHWA_StaticCfg_t::rangeFFTtuning, DPU_RangeProcHWA_StaticConfig_t::resetDcRangeSigMeanBuffer, DPU_RangeProcHWA_Config_t::staticCfg, DPU_RangeProcHWA_StaticConfig_t::window, and DPU_RangeProcHWA_StaticConfig_t::windowSize.
Referenced by DPC_ObjDetRangeHwa_preStartConfig(), and DPC_ObjDetRangeHwa_reconfigSubFrame().
static int32_t DPC_ObjDetRangeHwa_reconfigSubFrame (ObjDetObj * objDetObj, uint8_t subFrameIndx) static
Description
Sub-frame reconfiguration, used when switching sub-frames. Invokes the DPU configuration using the configuration that was stored during the pre-start configuration so reconstruction time is saved because this will happen in real-time.
Parameters
[in] objDetObj Pointer to DPC object
[in] subFrameIndx Sub-frame index.
Return values
Success - 0
Error - <0
Definition at line 318 of file objdetrangehwa.c.
References ObjDetObj_t::commonCfg, DPC_ObjDetRangeHwa_GenRangeWindow(), DPC_ObjDetRangeHwa_rangeConfig(), DPU_RangeProcHWA_config(), SubFrameObj_t::dpuRangeObj, DPC_ObjectDetectionRangeHWA_PreStartCommonCfg_t::numSubFrames, SubFrameObj_t::rangeCfg, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_execute(), and DPC_ObjectDetection_start().
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) de-initialization function which is invoked by the application using DPM_deinit API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 1148 of file objdetrangehwa.c.
References DPC_OBJDETRANGEHWA_EINVAL, DPU_RangeProcHWA_deinit(), SubFrameObj_t::dpuRangeObj, and ObjDetObj_t::subFrameObj.
int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer * ptrResult) static
Description
DPC's (DPM registered) execute function which is invoked by the application in the DPM's execute context when the DPC issues DPM_notifyExecute API from its registered DPC_ObjectDetection_frameStart API that is invoked every frame interrupt.
Parameters
[in] handle DPM's DPC handle
[out] ptrResult Pointer to the result
Return values
Success - 0
Error - <0
Definition at line 673 of file objdetrangehwa.c.
References ObjDetObj_t::commonCfg, DPIF_RadarCube_t::data, DPIF_RadarCube_t::dataSize, DPC_Objdet_Assert, DPC_ObjDetRangeHwa_reconfigSubFrame(), DPM_relayResult(), ObjDetObj_t::dpmHandle, DPU_RangeProcHWA_Cmd_triggerProc, DPU_RangeProcHWA_control(), DPU_RangeProcHWA_process(), SubFrameObj_t::dpuRangeObj, DPU_RangeProcHWA_OutParams_t::endOfChirp, DPU_RangeProcHWA_Config_t::hwRes, DPC_ObjectDetectionRangeHWA_Stats_t::interChirpProcessingMargin, DPC_ObjectDetectionRangeHWA_Stats_t::interFrameStartTimeStamp, ObjDetObj_t::interSubFrameProcToken, DPC_ObjectDetectionRangeHWA_PreStartCommonCfg_t::numSubFrames, ObjDetObj_t::processCallBackFxn, DPC_ObjectDetectionRangeHWA_ProcessCallBackCfg_t::processFrameBeginCallBackFxn, DPC_ObjectDetectionRangeHWA_ProcessCallBackCfg_t::processInterFrameBeginCallBackFxn, DPM_Buffer_t::ptrBuffer, DPU_RangeProcHWA_HW_Resources_t::radarCube, SubFrameObj_t::rangeCfg, DPM_Buffer_t::size, ObjDetObj_t::stats, ObjDetObj_t::subFrameIndx, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_frameStart().
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle) static
Description
DPC frame start function registered with DPM. This is invoked on reception of the frame start ISR from the RF front-end.
Parameters
[in] handle DPM's DPC handle
Return values
Not applicable
Definition at line 630 of file objdetrangehwa.c.
References DPC_Objdet_Assert, DPC_ObjectDetection_execute(), DPM_notifyExecute(), ObjDetObj_t::dpmHandle, DPC_ObjectDetectionRangeHWA_Stats_t::frameStartIntCounter, DPC_ObjectDetectionRangeHWA_Stats_t::frameStartTimeStamp, ObjDetObj_t::interSubFrameProcToken, ObjDetObj_t::stats, and ObjDetObj_t::subFrameIndx.
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg * ptrInitCfg, int32_t * errCode) static
Description
DPC's (DPM registered) initialization function which is invoked by the application using DPM_init API. Among other things, this API allocates DPC instance and DPU instances (by calling DPU's init APIs) from the MemoryP osal heap. If this API returns an error of any type, the heap is not guaranteed to be in the same state as before calling the API (i.e any allocations from the heap while executing the API are not guaranteed to be deallocated in case of error), so any error from this API should be considered fatal and if the error is of _ENOMEM type, the application will have to be built again with a bigger heap size to address the problem.
Parameters
[in] dpmHandle DPM's DPC handle
[in] ptrInitCfg Handle to the framework semaphore
[out] errCode Error code populated on error
Return values
Success - 0
Error - <0
Definition at line 1034 of file objdetrangehwa.c.
References DPM_InitCfg_t::arg, DPM_InitCfg_t::argSize, DPC_ObjectDetectionRangeHWA_InitParams_t::CoreLocalRamCfg, DPC_OBJDETRANGEHWA_EINVAL, DPC_OBJDETRANGEHWA_EINVAL__INIT_CFG_ARGSIZE, DPC_OBJDETRANGEHWA_ENOMEM, DPU_RangeProcHWA_init(), DPC_ObjectDetectionRangeHWA_InitParams_t::edmaHandle, DPU_RangeProcHWA_InitParams_t::hwaHandle, DPC_ObjectDetectionRangeHWA_InitParams_t::hwaHandle, DPC_ObjectDetectionRangeHWA_InitParams_t::L3ramCfg, DPC_ObjectDetectionRangeHWA_InitParams_t::processCallBackFxn, and DPM_InitCfg_t::socHandle.
Referenced by DPC_ObjectDetection_ioctl().
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void * arg, uint32_t argLen) static
Description
DPC IOCTL commands configuration API which will be invoked by the application using DPM_ioctl API
Parameters
[in] handle DPM's DPC handle
[in] cmd Capture DPC specific commands
[in] arg Command specific arguments
[in] argLen Length of the arguments which is also command specific
Return values
Success - 0
Error - <0
Definition at line 862 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_preStartCfg_radarCubeMem_t::addr, DPC_ObjectDetectionRangeHWA_DynCfg_t::calibDcRangeSigCfg, MemPoolObj_t::cfg, DPC_ObjectDetectionRangeHWA_CalibDcRangeSigCfg_t::cfg, ObjDetObj_t::commonCfg, ObjDetObj_t::CoreLocalRamObj, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::CoreLocalRamTotal, DPIF_RadarCube_t::data, DPIF_RadarCube_t::dataSize, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMean, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMeanSize, DPC_OBJDETRANGEHWA_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPC_OBJDETRANGEHWA_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDETRANGEHWA_IOCTL__STATIC_PRE_START_COMMON_CFG, DPC_OBJDETRANGEHWA_PRE_START_CONFIG_BEFORE_PRE_START_COMMON_CONFIG, DPC_ObjDetRangeHwa_preStartConfig(), DPC_ObjectDetection_init(), DPM_EINVCMD, DPU_RangeProcHWA_Cmd_dcRangeCfg, DPU_RangeProcHWA_control(), SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dynCfg, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::dynCfg, DPU_RangeProcHWA_Config_t::hwRes, ObjDetObj_t::isCommonCfgReceived, ObjDetObj_t::L3RamObj, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::L3RamTotal, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::memUsage, DPC_ObjectDetectionRangeHWA_PreStartCommonCfg_t::numSubFrames, DPU_RangeProcHWA_HW_Resources_t::radarCube, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::radarCubeMem, SubFrameObj_t::rangeCfg, DPC_ObjectDetectionRangeHWA_MemCfg_t::size, DPC_ObjectDetectionRangeHWA_preStartCfg_radarCubeMem_t::size, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::staticCfg, DPC_ObjectDetectionRangeHWA_PreStartCfg_t::subFrameNum, ObjDetObj_t::subFrameObj, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage_t::SystemHeapUsed.
Referenced by DPC_ObjectDetection_stop().
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) start function which is invoked by the application using DPM_start API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 771 of file objdetrangehwa.c.
References ObjDetObj_t::commonCfg, DPC_ObjDetRangeHwa_reconfigSubFrame(), DPU_RangeProcHWA_Cmd_triggerProc, DPU_RangeProcHWA_control(), SubFrameObj_t::dpuRangeObj, DPC_ObjectDetectionRangeHWA_Stats_t::frameStartIntCounter, ObjDetObj_t::isCommonCfgReceived, DPC_ObjectDetectionRangeHWA_PreStartCommonCfg_t::numSubFrames, ObjDetObj_t::stats, ObjDetObj_t::subFrameIndx, and ObjDetObj_t::subFrameObj.
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) stop function which is invoked by the application using DPM_stop API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 828 of file objdetrangehwa.c.
References DPC_ObjectDetection_ioctl(), and ObjDetObj_t::subFrameIndx.
Copyright 2020, Texas Instruments Incorporated