objectdetection/objdetrangehwa/src/objdetrangehwa.c File Reference
objdetrangehwa.c File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <ti/drivers/soc/soc.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/osal/MemoryP.h>
#include <ti/drivers/edma/edma.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
#include <ti/control/dpm/dpm.h>
#include <ti/datapath/dpu/rangeproc/rangeprochwa.h>
#include <ti/datapath/dpc/objectdetection/objdetrangehwa/include/objdetrangehwainternal.h>
#include <ti/datapath/dpc/objectdetection/objdetrangehwa/objdetrangehwa.h>
Macros
#define DBG_DPC_OBJDETRANGEHWA
#define DPC_OBJDETRANGEHWA_RADAR_CUBE_DATABUF_BYTE_ALIGNMENT (sizeof(int16_t))
#define DPC_OBJDETRANGEHWA_HWA_MAX_WINDOW_RAM_SIZE_IN_SAMPLES SOC_HWA_WINDOW_RAM_SIZE_IN_SAMPLES
#define DPC_USE_SYMMETRIC_WINDOW_RANGE_DPU
#define DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE MATHUTILS_WIN_BLACKMAN
#define DPC_OBJDET_QFORMAT_RANGE_FFT 17
Functions
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg *ptrInitCfg, int32_t *errCode)
static int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer *ptrResult)
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void *arg, uint32_t argLen)
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle)
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle)
static void DPC_ObjDetRangeHwa_MemPoolReset (MemPoolObj *pool)
static uint32_t DPC_ObjDetRangeHwa_MemPoolGetMaxUsage (MemPoolObj *pool)
static void * DPC_ObjDetRangeHwa_MemPoolAlloc (MemPoolObj *pool, uint32_t size, uint8_t align)
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char *file, int32_t line)
static uint32_t DPC_ObjDetRangeHwa_GetRangeWinGenLen (uint16_t numAdcSamples)
static void DPC_ObjDetRangeHwa_GenRangeWindow (DPU_RangeProcHWA_Config *cfg)
static int32_t DPC_ObjDetRangeHwa_reconfigSubFrame (ObjDetObj *objDetObj, uint8_t subFrameIndx)
static int32_t DPC_ObjDetRangeHwa_rangeConfig (DPU_RangeProcHWA_Handle dpuHandle, DPC_ObjectDetectionRangeHWA_StaticCfg *staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreLocalRamObj, DPU_RangeProcHWA_Config *cfgSave)
static int32_t DPC_ObjDetRangeHwa_preStartConfig (SubFrameObj *subFrmObj, ObjDetObj *objDetObj, DPC_ObjectDetectionRangeHWA_StaticCfg *staticCfg, DPC_ObjectDetectionRangeHWA_DynCfg *dynCfg, DPC_ObjectDetectionRangeHWA_preStartCfg_memUsage *memUsage)
Variables
ObjDetObj * gObjDetObj
DPM_ProcChainCfg gDPC_ObjDetRangeHWACfg
Global used to register Object Detection DPC in DPM.
Macro Definition Documentation
#define DBG_DPC_OBJDETRANGEHWA
Definition at line 47 of file objdetrangehwa.c.
#define DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE MATHUTILS_WIN_BLACKMAN
Definition at line 97 of file objdetrangehwa.c.
Referenced by DPC_ObjDetRangeHwa_GenRangeWindow().
#define DPC_OBJDET_QFORMAT_RANGE_FFT 17
Definition at line 100 of file objdetrangehwa.c.
Referenced by DPC_ObjDetRangeHwa_GenRangeWindow().
#define DPC_OBJDETRANGEHWA_HWA_MAX_WINDOW_RAM_SIZE_IN_SAMPLES SOC_HWA_WINDOW_RAM_SIZE_IN_SAMPLES
Definition at line 92 of file objdetrangehwa.c.
Referenced by DPC_ObjDetRangeHwa_rangeConfig().
#define DPC_USE_SYMMETRIC_WINDOW_RANGE_DPU
Definition at line 96 of file objdetrangehwa.c.
Function Documentation
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char * file, int32_t line)
Description
Sends Assert
Return values
Not Applicable.
Definition at line 235 of file objdetrangehwa.c.
References DPM_DPCAssert_t::arg0, DPM_DPCAssert_t::arg1, DPM_CMD_DPC_ASSERT, DPM_ioctl(), DPM_MAX_FILE_NAME_LEN, DPM_DPCAssert_t::fileName, and DPM_DPCAssert_t::lineNum.
static void* DPC_ObjDetRangeHwa_MemPoolAlloc (MemPoolObj * pool, uint32_t size, uint8_t align) static
Description
Utility function for allocating from a static memory pool.
Parameters
[in] pool Handle to pool object.
[in] size Size in bytes to be allocated.
[in] align Alignment in bytes
Return values
pointer to beginning of allocated block. NULL indicates could not allocate.
Definition at line 208 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, MemPoolObj_t::maxCurrAddr, and DPC_ObjectDetectionRangeHWA_MemCfg_t::size.
Referenced by DPC_ObjDetRangeHwa_preStartConfig(), and DPC_ObjDetRangeHwa_rangeConfig().
static uint32_t DPC_ObjDetRangeHwa_MemPoolGetMaxUsage (MemPoolObj * pool) static
Description
Utility function for getting maximum memory pool usage.
Parameters
[in] pool Handle to pool object.
Return values
Amount of pool used in bytes.
Definition at line 188 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetRangeHwa_preStartConfig().
static void DPC_ObjDetRangeHwa_MemPoolReset (MemPoolObj * pool) static
Description
Utility function for reseting memory pool.
Parameters
[in] pool Handle to pool object.
Return values
none.
Definition at line 169 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetRangeHwa_preStartConfig().
Copyright 2020, Texas Instruments Incorporated