Object Detection DPC Internal Functions
Object Detection DPC Internal Functions
Object Detection DPC (Data Path Chain) Internal
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Functions
static void DPC_ObjDet_MemPoolReset (MemPoolObj *pool)
static void DPC_ObjDet_MemPoolSet (MemPoolObj *pool, void *addr)
static void * DPC_ObjDet_MemPoolGet (MemPoolObj *pool)
static uint32_t DPC_ObjDet_MemPoolGetMaxUsage (MemPoolObj *pool)
static void * DPC_ObjDet_MemPoolAlloc (MemPoolObj *pool, uint32_t size, uint8_t align)
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle)
static void DPC_ObjDet_quadFit (float *x, float *y, float *xv, float *yv)
static void DPC_ObjDet_rangeBiasRxChPhaseMeasure (DPC_ObjectDetection_StaticCfg *staticCfg, float targetDistance, float searchWinSize, uint16_t *detMatrix, uint32_t *symbolMatrix, DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static uint32_t DPC_ObjDet_GetRangeWinGenLen (DPU_RangeProcHWA_Config *cfg)
static void DPC_ObjDet_GenRangeWindow (DPU_RangeProcHWA_Config *cfg)
static uint32_t DPC_ObjDet_GetDopplerWinGenLen (DPU_DopplerProcHWA_Config *cfg)
static uint32_t DPC_ObjDet_GenDopplerWindow (DPU_DopplerProcHWA_Config *cfg)
static void DPC_ObjDet_GetRxChPhaseComp (DPC_ObjectDetection_StaticCfg *staticCfg, DPU_AoAProc_compRxChannelBiasCfg *inpCfg, DPU_AoAProc_compRxChannelBiasCfg *outCfg)
static void DPC_ObjDet_GetAntGeometryDef (DPC_ObjectDetection_StaticCfg *staticCfg, ANTDEF_AntGeometry *antDef)
static int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer *ptrResult)
static int32_t DPC_ObjDet_reconfigSubFrame (ObjDetObj *objDetObj, uint8_t subFrameIndx)
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle)
static void DPC_ObjDet_Config_StaticClutterRemovalCfg (SubFrameObj *obj, DPC_ObjectDetection_StaticClutterRemovalCfg_Base *cfg)
static int32_t DPC_ObjDet_Config_MeasureRxChannelBiasCfg (ObjDetObj *obj, DPC_ObjectDetection_MeasureRxChannelBiasCfg *cfg)
static int32_t DPC_ObjDet_rangeConfig (DPU_RangeProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreLocalRamObj, uint32_t *windowOffset, uint32_t *CoreLocalRamScratchUsage, DPU_RangeProcHWA_Config *cfgSave)
static int32_t DPC_ObjDet_dopplerConfig (DPU_DopplerProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_DetMatrix *detMatrix, MemPoolObj *CoreLocalRamObj, uint32_t *windowOffset, uint32_t *CoreLocalRamScratchUsage, DPU_DopplerProcHWA_Config *cfgSave)
static int32_t DPC_ObjDet_staticClutterConfig (DPU_StaticClutterProc_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreLocalRamObj, uint32_t *CoreLocalRamScratchUsage, DPU_StaticClutterProc_Config *cfgSave)
static int32_t DPC_ObjDet_CFARCAconfig (DPU_CFARCAProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_DetMatrix *detMatrix, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreLocalRamObj, uint32_t hwaMemBankAddr[4], uint16_t hwaMemBankSize, float rangeBias, uint32_t *CoreLocalRamScratchUsage, DPU_CFARCAProcHWA_Config *cfgSave)
static int32_t DPC_ObjDet_AoAconfig (DPU_AoAProcHWA_Handle dpuHandle, DPU_AoAProc_compRxChannelBiasCfg *inpCommonCompRxCfg, ANTDEF_AntGeometry *antDef, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreLocalRamObj, MemPoolObj *L3RamObj, uint8_t dopplerWindowSym, uint32_t dopplerWinSize, int32_t *dopplerWindow, uint32_t dopplerWinRamOffset, uint8_t cfarParamSetStartIdx, bool *isAoAHWAparamSetOverlappedWithCFAR, DPU_AoAProcHWA_Config *cfgSave)
static int32_t DPC_ObjDet_preStartConfig (SubFrameObj *obj, DPC_ObjectDetection_PreStartCommonCfg *commonCfg, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle[EDMA_NUM_CC], MemPoolObj *L3ramObj, MemPoolObj *CoreLocalRamObj, uint32_t hwaMemBankAddr[4], uint16_t hwaMemBankSize, uint32_t *L3RamUsage, uint32_t *CoreLocalRamUsage)
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void *arg, uint32_t argLen)
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg *ptrInitCfg, int32_t *errCode)
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle)
Detailed Description
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Function Documentation
static int32_t DPC_ObjDet_AoAconfig (DPU_AoAProcHWA_Handle dpuHandle, DPU_AoAProc_compRxChannelBiasCfg * inpCommonCompRxCfg, ANTDEF_AntGeometry * antDef, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, DPIF_CFARDetList * cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj * CoreLocalRamObj, MemPoolObj * L3RamObj, uint8_t dopplerWindowSym, uint32_t dopplerWinSize, int32_t * dopplerWindow, uint32_t dopplerWinRamOffset, uint8_t cfarParamSetStartIdx, bool * isAoAHWAparamSetOverlappedWithCFAR, DPU_AoAProcHWA_Config * cfgSave) static
Description
Configure AoA DPU. Note window information is passed to this function that is expected to be the same that was used in doppler processing because the AoA recomputes the doppler (2D) FFT. The reason for this recompute is because doppler does not update the radar cube (radar cube is range (1D) output). The window is used in AoA only for doppler FFT recompute, no window (in other words rectangular) is used for angle (3D) FFT computation. Note no DPIF info is passed here for AoA output because these DPIF buffers are not required to be shared with any other DPUs (but only at the exit f DPC's processing chain which will be consumed by the app) hence they are allocated within this function, this way more allocation remains localized in this function instead of being managed by the caller.
Parameters
[in] dpuHandle Handle to DPU
[in] inpCommonCompRxCfg Range bias and rx phase compensation common (across sub-frames) configuration, this will be used to extract the rx phase for sub-frame specific configuration based on antenna order.
[in] antDef Pointer to the antenna configuration for the board
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which will be the input for AoA processing
[in] cfarRngDopSnrList Pointer to range-doppler SNR list, which will be input for AoA processing
[in] cfarRngDopSnrListSize Range-doppler SNR List Size to which the list was capped by cfar processing
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, all allocated memory will be permanent (within frame/sub-frame)
[in] L3RamObj Pointer to L3 RAM object to allocate L3RAM memory for the DPU, all allocated memory will be permanent (within frame/sub-frame)
[in] dopplerWindowSym Flag to indicate if HWA windowing is symmetric see HWA_WINDOW_SYMM definitions in HWA driver's doxygen documentation
[in] dopplerWinSize Doppler FFT window size in bytes. See doppler DPU configuration for more information.
[in] dopplerWindow Pointer to doppler FFT window coefficients
[in] dopplerWinRamOffset HWA window RAM offset of doppler FFT
[in] cfarParamSetStartIdx Start index of the cfar param set, will be used as the start of AoA's param set if overlap with CFAR is needed based on configuration.
[out] isAoAHWAparamSetOverlappedWithCFAR true if AoA's param set overlaps with CFAR (depends on the configuration input)
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1894 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPU_AoAProcHWA_StaticConfig_t::antDef, DPC_ObjectDetection_StaticCfg_t::antDef, DPU_AoAProcHWA_Resources_t::azimuthStaticHeatMap, DPU_AoAProcHWA_Resources_t::azimuthStaticHeatMapSize, DPU_AoAProcHWA_Resources_t::cfarRngDopSnrList, DPU_AoAProcHWA_Resources_t::cfarRngDopSnrListSize, DPU_AoAProcHWA_ChanCfg_t::channel, DPU_AoAProcHWA_EdmaHwaDataInOut_t::chIn, DPU_AoAProcHWA_EdmaHwaDataInOut_t::chOut, DPU_AoAProc_DynamicConfig_t::compRxChanCfg, DPIF_ADCBufData_t::dataProperty, DPU_AoAProcHWA_Resources_t::detObj2dAzimIdx, DPU_AoAProcHWA_Resources_t::detObjElevationAngle, DPU_AoAProcHWA_Resources_t::detObjOut, DPU_AoAProcHWA_Resources_t::detObjOutMaxSize, DPU_AoAProcHWA_Resources_t::detObjOutSideInfo, DPU_AoAProcHWA_StaticConfig_t::dopplerStep, DPC_ObjectDetection_StaticCfg_t::dopplerStep, DPC_OBJDET_AZIMUTH_STATIC_HEAT_MAP_BYTE_ALIGNMENT, DPC_OBJDET_DET_OBJ_ELEVATION_ANGLE_BYTE_ALIGNMENT, DPC_ObjDet_GetAntGeometryDef(), DPC_ObjDet_GetRxChPhaseComp(), DPC_OBJDET_MAX_NUM_OBJECTS, DPC_ObjDet_MemPoolAlloc(), DPC_OBJDET_POINT_CLOUD_CARTESIAN_BYTE_ALIGNMENT, DPC_OBJDET_POINT_CLOUD_SIDE_INFO_BYTE_ALIGNMENT, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_AZIMUTH_STATIC_HEAT_MAP, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_DET_OBJ_2_AZIM_IDX, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_DET_OBJ_ELEVATION_ANGLE, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_DET_OBJ_OUT, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_DET_OBJ_OUT_SIDE_INFO, DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_AOA_SCRATCH_BUFFER, DPU_AoAProcHWA_config(), DPU_AoAProcHWA_getNumHwaParamSets(), DPU_AOAPROCHWA_LOCAL_SCRATCH_BYTE_ALIGNMENT, DPU_AOAPROCHWA_NUM_LOCAL_SCRATCH_BUFFER_SIZE_BYTES, DPU_AOAPROCHWA_NUM_LOCAL_SCRATCH_BUFFERS, DPU_AoAProcHWA_Config_t::dynCfg, DPU_AoAProcHWA_Resources_t::edmaHandle, DPU_AoAProcHWA_Resources_t::edmaHwa, DPU_AoAProcHWA_Resources_t::edmaHwaExt, DPU_AoAProcHWA_ChanCfg_t::eventQueue, DPU_AoAProcHWA_EdmaHwaDataInOut_t::eventQueue, DPU_AoAProc_DynamicConfig_t::extMaxVelCfg, DPC_ObjectDetection_DynCfg_t::extMaxVelCfg, DPU_AoAProc_DynamicConfig_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPU_AoAProcHWA_Resources_t::hwaCfg, DPU_AoAProcHWA_EdmaHwaInOut_t::in, DPU_AoAProcHWA_EdmaHwaInOut_t::inSignature, DPU_AoAProcHWA_Resources_t::localScratchBuffer, DPU_AoAProcHWA_Resources_t::localScratchBufferSizeBytes, DPU_AoAProc_DynamicConfig_t::multiObjBeamFormingCfg, DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, DPU_AoAProcHWA_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_AoAProcHWA_StaticConfig_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPU_AoAProcHWA_hwaAoAConfig_t::numParamSet, DPU_AoAProcHWA_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_AoAProcHWA_StaticConfig_t::numRxAntennas, DPIF_ADCBufProperty_t::numRxAntennas, DPU_AoAProcHWA_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_AoAProcHWA_StaticConfig_t::numVirtualAnt, DPU_AoAProcHWA_StaticConfig_t::numVirtualAntAzim, DPC_ObjectDetection_StaticCfg_t::numVirtualAntAzim, DPU_AoAProcHWA_StaticConfig_t::numVirtualAntElev, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_AoAProcHWA_EdmaHwaInOut_t::out, DPU_AoAProcHWA_EdmaHwaInOutParamId_t::paramHwaContinue, DPU_AoAProcHWA_EdmaHwaInOutParamId_t::paramIn, DPU_AoAProcHWA_EdmaHwaInOutParamId_t::paramInSignature, DPU_AoAProcHWA_EdmaHwaInOutParamId_t::paramOut, DPU_AoAProcHWA_EdmaHwaInOutParamId_t::paramPeakCnt, DPU_AoAProcHWA_hwaAoAConfig_t::paramSetStartIdx, DPU_AoAProc_DynamicConfig_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, DPU_AoAProcHWA_Resources_t::radarCube, DPU_AoAProcHWA_StaticConfig_t::rangeStep, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_AoAProcHWA_Config_t::res, DPU_AoAProcHWA_EdmaHwaDataInOut_t::stage, DPU_AoAProcHWA_Config_t::staticCfg, DPU_AoAProcHWA_hwaAoAConfig_t::window, DPU_AoAProcHWA_hwaAoAConfig_t::windowSize, DPU_AoAProcHWA_hwaAoAConfig_t::winRamOffset, and DPU_AoAProcHWA_hwaAoAConfig_t::winSym.
Referenced by DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjDet_CFARCAconfig (DPU_CFARCAProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_DetMatrix * detMatrix, DPIF_CFARDetList * cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj * CoreLocalRamObj, uint32_t hwaMemBankAddr[4], uint16_t hwaMemBankSize, float rangeBias, uint32_t * CoreLocalRamScratchUsage, DPU_CFARCAProcHWA_Config * cfgSave) static
Description
Configure CFARCA DPU.
Parameters
[in] dpuHandle Handle to DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] log2NumDopplerBins log2 of numDopplerBins of the static config.
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] detMatrix Pointer to DPIF detection matrix, which will be the input to the CFARCA
[in] cfarRngDopSnrList Pointer to range-doppler SNR list, which will be the output of CFARCA
[in] cfarRngDopSnrListSize Range-doppler SNR List Size to which the list will be capped.
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, only for scratch purposes
[in] hwaMemBankAddr pointer to HWA Memory Bank addresses that will be used to allocate various scratch areas for the DPU processing
[in] hwaMemBankSize Size in bytes of each of HWA memory banks
[in] rangeBias Range Bias which will be used to adjust fov min value.
[out] CoreLocalRamScratchUsage Core Local RAM's scratch usage in bytes
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1737 of file objectdetection.c.
References DPU_CFARCAProcHWA_DynamicConfig_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPU_CFARCAProcHWA_DynamicConfig_t::cfarCfgRange, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPU_CFARCAProcHWA_Resources_t::cfarDopplerDetOutBitMask, DPU_CFARCAProcHWA_Resources_t::cfarDopplerDetOutBitMaskSize, DPU_CFARCAProcHWA_Resources_t::cfarRngDopSnrList, DPU_CFARCAProcHWA_Resources_t::cfarRngDopSnrListSize, DPU_CFARCAProcHWA_Resources_t::detMatrix, DPU_CFARCAProcHWA_StaticConfig_t::dopplerStep, DPC_ObjectDetection_StaticCfg_t::dopplerStep, DPC_ObjDet_MemPoolAlloc(), DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_CFARCA_DOPPLER_DET_OUT_BIT_MASK, DPU_CFARCAProcHWA_config(), DPU_CFARCAPROCHWA_DOPPLER_DET_OUT_BIT_MASK_BYTE_ALIGNMENT, DPU_CFARCAPROCHWA_NUM_HWA_PARAM_SETS, DPU_CFARCAProcHWA_Config_t::dynCfg, DPU_CFARCAProcHWA_Resources_t::edmaHandle, DPU_CFARCAProcHWA_Resources_t::edmaHwaIn, DPU_CFARCAProcHWA_Resources_t::edmaHwaInSignature, DPU_CFARCAProcHWA_DynamicConfig_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPU_CFARCAProcHWA_DynamicConfig_t::fovRange, DPC_ObjectDetection_DynCfg_t::fovRange, DPU_CFARCAProcHWA_Resources_t::hwaCfg, DPU_CFARCAProcHWA_Resources_t::hwaMemInp, DPU_CFARCAProcHWA_Resources_t::hwaMemInpSize, DPU_CFARCAProcHWA_Resources_t::hwaMemOutDoppler, DPU_CFARCAProcHWA_Resources_t::hwaMemOutDopplerSize, DPU_CFARCAProcHWA_Resources_t::hwaMemOutRange, DPU_CFARCAProcHWA_Resources_t::hwaMemOutRangeSize, DPU_CFARCAProcHWA_StaticConfig_t::log2NumDopplerBins, DPU_CFARCAProc_FovCfg_t::min, DPU_CFARCAProcHWA_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_CFARCAProcHWA_HwaCfarConfig_t::numParamSet, DPU_CFARCAProcHWA_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_CFARCAProcHWA_HwaCfarConfig_t::paramSetStartIdx, DPU_CFARCAProcHWA_StaticConfig_t::rangeStep, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_CFARCAProcHWA_Config_t::res, and DPU_CFARCAProcHWA_Config_t::staticCfg.
Referenced by DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjDet_Config_MeasureRxChannelBiasCfg (ObjDetObj * obj, DPC_ObjectDetection_MeasureRxChannelBiasCfg * cfg) static
Description
Configures DPC for Range Bias and Phase Comp measurement.
Parameters
[in] obj Pointer to DPC object
[in] cfg Pointer to Range Bias and Phase Comp measurement configuration
Return values
Success - 0
Error - <0
Definition at line 1203 of file objectdetection.c.
References ObjDetObj_t::commonCfg, DPC_OBJECTDETECTION_EINVAL__MEASURE_RX_CHANNEL_BIAS_CFG, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::searchWinSize, and DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::targetDistance.
Referenced by DPC_ObjectDetection_ioctl().
static void DPC_ObjDet_Config_StaticClutterRemovalCfg (SubFrameObj * obj, DPC_ObjectDetection_StaticClutterRemovalCfg_Base * cfg) static
Description
Configures DPC for static clutter removal.
Parameters
[in] obj Pointer to sub-frame object
[in] cfg Pointer to static clutter removal configuration
Return values
None
Definition at line 1180 of file objectdetection.c.
References SubFrameObj_t::dynCfg, and DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg.
Referenced by DPC_ObjectDetection_ioctl().
static int32_t DPC_ObjDet_dopplerConfig (DPU_DopplerProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, DPIF_DetMatrix * detMatrix, MemPoolObj * CoreLocalRamObj, uint32_t * windowOffset, uint32_t * CoreLocalRamScratchUsage, DPU_DopplerProcHWA_Config * cfgSave) static
Description
Configure Doppler DPU.
Parameters
[in] dpuHandle Handle to DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] log2NumDopplerBins log2 of numDopplerBins of the static config.
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which will be the input to doppler processing
[in] detMatrix Pointer to DPIF detection matrix, which will be the output of doppler processing
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, only for scratch purposes
[in,out] windowOffset Window coefficients that are generated by this function (in heap memory) are passed to DPU configuration API to configure the HWA window RAM starting from this offset. The end offset after this configuration will be returned in this variable which could be the begin offset for the next DPU window RAM.
[out] CoreLocalRamScratchUsage Core Local RAM's scratch usage in bytes
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1464 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPU_DopplerProcHWA_HW_Resources_t::detMatrix, DPC_ObjDet_GenDopplerWindow(), DPC_ObjDet_GetDopplerWinGenLen(), DPC_OBJDET_HWA_MAX_WINDOW_RAM_SIZE_IN_SAMPLES, DPC_ObjDet_MemPoolAlloc(), DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_DOPPLER_HWA_WINDOW, DPC_OBJECTDETECTION_ENOMEM_HWA_WINDOW_RAM, DPU_DopplerProcHWA_config(), DPU_DOPPLERPROCHWA_FIRST_SCALING_DISABLED, DPU_DOPPLERPROCHWA_FIRST_SCALING_ENABLED, DPU_DopplerProcHWA_HW_Resources_t::edmaCfg, DPU_DopplerProcHWA_EdmaCfg_t::edmaHandle, DPU_DopplerProcHWA_EdmaCfg_t::edmaHotSig, DPU_DopplerProcHWA_EdmaCfg_t::edmaIn, DPU_DopplerProcHWA_EdmaCfg_t::edmaOut, DPU_DopplerProcHWA_HwaCfg_t::firstStageScaling, DPU_DopplerProcHWA_HW_Resources_t::hwaCfg, DPU_DopplerProcHWA_Config_t::hwRes, DPU_DopplerProcHWA_StaticConfig_t::log2NumDopplerBins, DPU_DopplerProcHWA_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_DopplerProcHWA_StaticConfig_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPU_DopplerProcHWA_HwaCfg_t::numParamSets, DPU_DopplerProcHWA_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_DopplerProcHWA_StaticConfig_t::numRxAntennas, DPIF_ADCBufProperty_t::numRxAntennas, DPU_DopplerProcHWA_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_DopplerProcHWA_StaticConfig_t::numVirtualAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_DopplerProcHWA_HwaCfg_t::paramSetStartIdx, DPU_DopplerProc_Edma_t::ping, DPU_DopplerProc_Edma_t::pong, DPU_DopplerProcHWA_HW_Resources_t::radarCube, DPU_DopplerProcHWA_Config_t::staticCfg, DPU_DopplerProcHWA_HwaCfg_t::window, DPU_DopplerProcHWA_HwaCfg_t::windowSize, DPU_DopplerProcHWA_HwaCfg_t::winRamOffset, and DPU_DopplerProcHWA_HwaCfg_t::winSym.
Referenced by DPC_ObjDet_preStartConfig().
static uint32_t DPC_ObjDet_GenDopplerWindow (DPU_DopplerProcHWA_Config * cfg) static
Description
Generate the doppler DPU window using mathutils API.
Parameters
[in] cfg Doppler DPU configuration, output window is generated in window pointer embedded in this configuration.
Return values
winType window type, see mathutils.h
Definition at line 705 of file objectdetection.c.
References DPC_DPU_DOPPLERPROC_FFT_WINDOW_TYPE, DPC_ObjDet_GetDopplerWinGenLen(), DPC_OBJDET_QFORMAT_DOPPLER_FFT, DPU_DopplerProcHWA_HW_Resources_t::hwaCfg, DPU_DopplerProcHWA_Config_t::hwRes, DPU_DopplerProcHWA_StaticConfig_t::numDopplerChirps, DPU_DopplerProcHWA_Config_t::staticCfg, and DPU_DopplerProcHWA_HwaCfg_t::window.
Referenced by DPC_ObjDet_dopplerConfig(), DPC_ObjDet_reconfigSubFrame(), and DPC_ObjectDetection_execute().
static void DPC_ObjDet_GenRangeWindow (DPU_RangeProcHWA_Config * cfg) static
Description
Generate the range DPU window using mathutils API.
Parameters
[in] cfg Range DPU configuration, output window is generated in window pointer in the staticCfg of this.
Return values
None
Definition at line 658 of file objectdetection.c.
References DPU_RangeProcHWA_StaticConfig_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE, DPC_ObjDet_GetRangeWinGenLen(), DPC_OBJDET_QFORMAT_RANGE_FFT, DPIF_ADCBufProperty_t::numAdcSamples, DPU_RangeProcHWA_Config_t::staticCfg, and DPU_RangeProcHWA_StaticConfig_t::window.
Referenced by DPC_ObjDet_rangeConfig(), DPC_ObjDet_reconfigSubFrame(), DPC_ObjectDetection_ioctl(), and DPC_ObjectDetection_start().
static void DPC_ObjDet_GetAntGeometryDef (DPC_ObjectDetection_StaticCfg * staticCfg, ANTDEF_AntGeometry * antDef) static
Description
Function transfers antenna geometry definition from the common area which holds all antennas, to the area per subframe according to subframe antenna usage (antena order and number of used antennas)
Parameters
[in] staticCfg Static configuration of the sub-frame
[in] antDef Full antenna geometry definition
Return values
None
Definition at line 796 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPC_ObjectDetection_StaticCfg_t::antDef, DPIF_ADCBufData_t::dataProperty, DPC_ObjectDetection_execute(), DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, ANTDEF_AntGeometry_t::rxAnt, DPC_ObjectDetection_StaticCfg_t::rxAntOrder, ANTDEF_AntGeometry_t::txAnt, and DPC_ObjectDetection_StaticCfg_t::txAntOrder.
Referenced by DPC_ObjDet_AoAconfig().
static uint32_t DPC_ObjDet_GetDopplerWinGenLen (DPU_DopplerProcHWA_Config * cfg) static
Description
Computes the length of window to generate for doppler DPU.
Parameters
[in] cfg Doppler DPU configuration
Return values
Length of window to generate
Definition at line 678 of file objectdetection.c.
References DPU_DopplerProcHWA_StaticConfig_t::numDopplerChirps, and DPU_DopplerProcHWA_Config_t::staticCfg.
Referenced by DPC_ObjDet_dopplerConfig(), and DPC_ObjDet_GenDopplerWindow().
static uint32_t DPC_ObjDet_GetRangeWinGenLen (DPU_RangeProcHWA_Config * cfg) static
Description
Computes the length of window to generate for range DPU.
Parameters
[in] cfg Range DPU configuration
Return values
Length of window to generate
Definition at line 628 of file objectdetection.c.
References DPU_RangeProcHWA_StaticConfig_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPIF_ADCBufProperty_t::numAdcSamples, and DPU_RangeProcHWA_Config_t::staticCfg.
Referenced by DPC_ObjDet_GenRangeWindow(), and DPC_ObjDet_rangeConfig().
static void DPC_ObjDet_GetRxChPhaseComp (DPC_ObjectDetection_StaticCfg * staticCfg, DPU_AoAProc_compRxChannelBiasCfg * inpCfg, DPU_AoAProc_compRxChannelBiasCfg * outCfg) static
Description
Extracts the sub-frame specific vector from the common (full vector for all antennnas) input vector of the range bias and rx phase compensation. Uses the antenna order of the sub-frame.
Parameters
[in] staticCfg Static configuration of the sub-frame
[in] inpCfg The full vector.
[out] outCfg Sub-frame specific compensation vector that will be used during processing
Return values
None
Definition at line 743 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_ObjectDetection_StaticCfg_t::isValidProfileHasOneTxPerChirp, DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DPC_ObjectDetection_StaticCfg_t::rxAntOrder, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, and DPC_ObjectDetection_StaticCfg_t::txAntOrder.
Referenced by DPC_ObjDet_AoAconfig(), DPC_ObjDet_reconfigSubFrame(), DPC_ObjectDetection_execute(), and DPC_ObjectDetection_ioctl().
static void* DPC_ObjDet_MemPoolAlloc (MemPoolObj * pool, uint32_t size, uint8_t align) static
Description
Utility function for allocating from a static memory pool.
Parameters
[in] pool Handle to pool object.
[in] size Size in bytes to be allocated.
[in] align Alignment in bytes
Return values
pointer to beginning of allocated block. NULL indicates could not allocate.
Definition at line 305 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, DPC_ObjectDetection_deinit(), DPC_ObjectDetection_execute(), DPC_ObjectDetection_frameStart(), DPC_ObjectDetection_init(), DPC_ObjectDetection_ioctl(), DPC_ObjectDetection_start(), DPC_ObjectDetection_stop(), MemPoolObj_t::maxCurrAddr, and DPC_ObjectDetection_MemCfg_t::size.
Referenced by DPC_ObjDet_AoAconfig(), DPC_ObjDet_CFARCAconfig(), DPC_ObjDet_dopplerConfig(), DPC_ObjDet_preStartConfig(), DPC_ObjDet_rangeConfig(), and DPC_ObjDet_staticClutterConfig().
static void* DPC_ObjDet_MemPoolGet (MemPoolObj * pool) static
Description
Utility function for getting memory pool current address.
Parameters
[in] pool Handle to pool object.
Return values
pointer to current address of the pool (from which next allocation will allocate to the desired alignment).
Definition at line 251 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, and MemPoolObj_t::currAddr.
Referenced by DPC_ObjDet_preStartConfig().
static uint32_t DPC_ObjDet_MemPoolGetMaxUsage (MemPoolObj * pool) static
Description
Utility function for getting maximum memory pool usage.
Parameters
[in] pool Handle to pool object.
Return values
Amount of pool used in bytes.
Definition at line 285 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDet_preStartConfig().
static void DPC_ObjDet_MemPoolReset (MemPoolObj * pool) static
Description
Utility function for reseting memory pool.
Parameters
[in] pool Handle to pool object.
Return values
none.
Definition at line 212 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDet_preStartConfig().
static void DPC_ObjDet_MemPoolSet (MemPoolObj * pool, void * addr) static
Description
Utility function for setting memory pool to desired address in the pool. Helps to rewind for example.
Parameters
[in] pool Handle to pool object.
[in] addr Address to assign to the pool's current address.
Return values
None
Definition at line 232 of file objectdetection.c.
References MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjDet_preStartConfig (SubFrameObj * obj, DPC_ObjectDetection_PreStartCommonCfg * commonCfg, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle[EDMA_NUM_CC], MemPoolObj * L3ramObj, MemPoolObj * CoreLocalRamObj, uint32_t hwaMemBankAddr[4], uint16_t hwaMemBankSize, uint32_t * L3RamUsage, uint32_t * CoreLocalRamUsage) static
Description
Performs processing related to pre-start configuration, which is per sub-frame, by configuring each of the DPUs involved in the processing chain. Memory management notes:
Core Local Memory that needs to be preserved across sub-frames (such as range DPU's calib DC buffer) will be allocated using MemoryP_alloc.
Core Local Memory that needs to be preserved within a sub-frame across DPU calls (the DPIF * type memory) or for intermediate private scratch memory for DPU (i.e no preservation is required from process call to process call of the DPUs within the sub-frame) will be allocated from the Core Local RAM configuration supplied in DPC_ObjectDetection_InitParams given to DPC_ObjectDetection_init API
L3 memory will only be allocated from the L3 RAM configuration supplied in DPC_ObjectDetection_InitParams given to DPC_ObjectDetection_init API No L3 buffers are presently required that need to be preserved across sub-frames (type described in #1 above), neither are L3 scratch buffers required for intermediate processing within DPU process call.
Parameters
[in] obj Pointer to sub-frame object
[in] commonCfg Pointer to pre-start common configuration
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Pointer to array of EDMA handles for the device, this can be distributed among the DPUs, although presently we only use the first handle for all DPUs.
[in] L3ramObj Pointer to L3 RAM memory pool object
[in] CoreLocalRamObj Pointer to Core Local RAM memory pool object
[in] hwaMemBankAddr pointer to HWA Memory Bank addresses that will be used to allocate various scratch areas for the DPU processing
[in] hwaMemBankSize Size in bytes of each of HWA memory banks
[out] L3RamUsage Net L3 RAM memory usage in bytes as a result of allocation by the DPUs.
[out] CoreLocalRamUsage Net Core Local RAM memory usage in bytes as a result of allocation by the DPUs.
Return values
Success - 0
Error - <0
Definition at line 2152 of file objectdetection.c.
References DPC_ObjectDetection_PreStartCommonCfg_t::antDef, DpuConfigs_t::aoaCfg, DpuConfigs_t::cfarCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DPIF_RadarCube_t::data, DPIF_DetMatrix_t::data, DPIF_DetMatrix_t::datafmt, DPIF_RadarCube_t::datafmt, DPIF_DetMatrix_t::dataSize, DPIF_RadarCube_t::dataSize, DpuConfigs_t::dopplerCfg, DPC_ObjDet_AoAconfig(), DPC_OBJDET_CFAR_DET_LIST_BYTE_ALIGNMENT, DPC_ObjDet_CFARCAconfig(), DPC_OBJDET_DET_MATRIX_DATABUF_BYTE_ALIGNMENT, DPC_ObjDet_dopplerConfig(), DPC_OBJDET_MAX_NUM_OBJECTS, DPC_ObjDet_MemPoolAlloc(), DPC_ObjDet_MemPoolGet(), DPC_ObjDet_MemPoolGetMaxUsage(), DPC_ObjDet_MemPoolReset(), DPC_ObjDet_MemPoolSet(), DPC_OBJDET_RADAR_CUBE_DATABUF_BYTE_ALIGNMENT, DPC_ObjDet_rangeConfig(), DPC_ObjDet_staticClutterConfig(), DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_CFARCA_OUT_DET_LIST, DPC_OBJECTDETECTION_ENOMEM__L3_RAM_DET_MATRIX, DPC_OBJECTDETECTION_ENOMEM__L3_RAM_RADAR_CUBE, DPC_ObjectDetection_ioctl(), DPIF_DETMATRIX_FORMAT_1, DPIF_RADARCUBE_FORMAT_1, SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dpuStaticClutterObj, SubFrameObj_t::dynCfg, DPU_DopplerProcHWA_HW_Resources_t::hwaCfg, DPU_DopplerProcHWA_Config_t::hwRes, SubFrameObj_t::isAoAHWAparamSetOverlappedWithCFAR, SubFrameObj_t::log2NumDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DpuConfigs_t::rangeCfg, SubFrameObj_t::staticCfg, DpuConfigs_t::staticClutterCfg, DPU_DopplerProcHWA_HwaCfg_t::window, DPU_DopplerProcHWA_HwaCfg_t::windowSize, DPU_DopplerProcHWA_HwaCfg_t::winRamOffset, and DPU_DopplerProcHWA_HwaCfg_t::winSym.
Referenced by DPC_ObjectDetection_ioctl().
static void DPC_ObjDet_quadFit (float * x, float * y, float * xv, float * yv) static
Description
Utility function to do a parabolic/quadratic fit on 3 input points and return the coordinates of the peak. This is used to accurately estimate range bias.
Parameters
[in] x Pointer to array of 3 elements representing the x-coordinate of the points to fit
[in] y Pointer to array of 3 elements representing the y-coordinate of the points to fit
[out] xv Pointer to output x-coordinate of the peak value
[out] yv Pointer to output y-coordinate of the peak value
Return values
None
Definition at line 460 of file objectdetection.c.
References DPC_ObjDet_rangeBiasRxChPhaseMeasure().
Referenced by DPC_ObjDet_rangeBiasRxChPhaseMeasure().
static void DPC_ObjDet_rangeBiasRxChPhaseMeasure (DPC_ObjectDetection_StaticCfg * staticCfg, float targetDistance, float searchWinSize, uint16_t * detMatrix, uint32_t * symbolMatrix, DPU_AoAProc_compRxChannelBiasCfg * compRxChanCfg) static
Description
Computes the range bias and rx phase compensation from the detection matrix during calibration measurement procedure of these parameters.
Parameters
[in] staticCfg Pointer to static configuration
[in] targetDistance Target distance in meters
[in] searchWinSize Search window size in meters
[in] detMatrix Pointer to detection matrix
[in] symbolMatrix Pointer to symbol matrix
[out] compRxChanCfg computed output range bias and rx phase comp vector
Return values
None
Definition at line 497 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_ObjDet_quadFit(), DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, and DPC_ObjectDetection_StaticCfg_t::txAntOrder.
Referenced by DPC_ObjDet_quadFit(), and DPC_ObjectDetection_execute().
static int32_t DPC_ObjDet_rangeConfig (DPU_RangeProcHWA_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, MemPoolObj * CoreLocalRamObj, uint32_t * windowOffset, uint32_t * CoreLocalRamScratchUsage, DPU_RangeProcHWA_Config * cfgSave) static
Description
Configure range DPU.
Parameters
[in] dpuHandle Handle to DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which is output of range processing.
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, only for scratch purposes
[in,out] windowOffset Window coefficients that are generated by this function (in heap memory) are passed to DPU configuration API to configure the HWA window RAM starting from this offset. The end offset after this configuration will be returned in this variable which could be the begin offset for the next DPU window RAM.
[out] CoreLocalRamScratchUsage Core Local RAM's scratch usage in bytes
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1254 of file objectdetection.c.
References DPU_RangeProcHWA_StaticConfig_t::ADCBufData, DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPU_RangeProcHWA_DynamicConfig_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPU_RangeProcHWA_EDMAInputConfig_t::dataIn, DPU_RangeProcHWA_HwaConfig_t::dataInputMode, DPU_RangeProcHWA_EDMAInputConfig_t::dataInSignature, DPU_RangeProcHWA_EDMAOutputConfigFmt2_t::dataOutPing, DPU_RangeProcHWA_EDMAOutputConfigFmt1_t::dataOutPing, DPU_RangeProcHWA_EDMAOutputConfigFmt2_t::dataOutPong, DPU_RangeProcHWA_EDMAOutputConfigFmt1_t::dataOutPong, DPU_RangeProcHWA_EDMAOutputConfig_t::dataOutSignature, DPIF_ADCBufData_t::dataProperty, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMean, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMeanSize, DPC_ObjDet_GenRangeWindow(), DPC_ObjDet_GetRangeWinGenLen(), DPC_OBJDET_HWA_MAX_WINDOW_RAM_SIZE_IN_SAMPLES, DPC_ObjDet_MemPoolAlloc(), DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_RANGE_HWA_WINDOW, DPC_OBJECTDETECTION_ENOMEM_HWA_WINDOW_RAM, DPIF_RXCHAN_NON_INTERLEAVE_MODE, DPU_RANGEPROC_SIGNATURE_COMP_MAX_BIN_SIZE, DPU_RangeProcHWA_config(), DPU_RangeProcHWA_InputMode_ISOLATED, DPU_RANGEPROCHWA_NUM_HWA_PARAM_SETS, DPU_RangeProcHWA_Config_t::dynCfg, DPU_RangeProcHWA_HW_Resources_t::edmaHandle, DPU_RangeProcHWA_HW_Resources_t::edmaInCfg, DPU_RangeProcHWA_HW_Resources_t::edmaOutCfg, DPU_RangeProcHWA_FFTtuning_t::fftOutputDivShift, DPU_RangeProcHWA_EDMAOutputConfig_t::fmt1, DPU_RangeProcHWA_EDMAOutputConfig_t::fmt2, DPU_RangeProcHWA_HW_Resources_t::hwaCfg, DPU_RangeProcHWA_HwaConfig_t::hwaWinRamOffset, DPU_RangeProcHWA_HwaConfig_t::hwaWinSym, DPU_RangeProcHWA_Config_t::hwRes, DPIF_ADCBufProperty_t::interleave, DPU_RangeProcHWA_StaticConfig_t::numChirpsPerFrame, DPC_ObjectDetection_StaticCfg_t::numChirpsPerFrame, DPU_RangeProcHWA_FFTtuning_t::numLastButterflyStagesToScale, DPU_RangeProcHWA_HwaConfig_t::numParamSet, DPU_RangeProcHWA_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPU_RangeProcHWA_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_RangeProcHWA_StaticConfig_t::numVirtualAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_RangeProcHWA_HwaConfig_t::paramSetStartIdx, DPU_RangeProcHWA_HW_Resources_t::radarCube, DPU_RangeProcHWA_StaticConfig_t::rangeFFTtuning, DPC_ObjectDetection_StaticCfg_t::rangeFFTtuning, DPU_RangeProcHWA_StaticConfig_t::resetDcRangeSigMeanBuffer, DPU_RangeProcHWA_Config_t::staticCfg, DPU_RangeProcHWA_StaticConfig_t::window, and DPU_RangeProcHWA_StaticConfig_t::windowSize.
Referenced by DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjDet_reconfigSubFrame (ObjDetObj * objDetObj, uint8_t subFrameIndx) static
Description
Sub-frame reconfiguration, used when switching sub-frames. Invokes the DPU configuration using the configuration that was stored during the pre-start configuration so reconstruction time is saved because this will happen in real-time.
Parameters
[in] objDetObj Pointer to DPC object
[in] subFrameIndx Sub-frame index.
Return values
Success - 0
Error - <0
Definition at line 1019 of file objectdetection.c.
References DpuConfigs_t::aoaCfg, DpuConfigs_t::cfarCfg, ObjDetObj_t::commonCfg, DPU_AoAProc_DynamicConfig_t::compRxChanCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DpuConfigs_t::dopplerCfg, DPC_ObjDet_GenDopplerWindow(), DPC_ObjDet_GenRangeWindow(), DPC_ObjDet_GetRxChPhaseComp(), DPU_AoAProcHWA_config(), DPU_CFARCAProcHWA_config(), DPU_DopplerProcHWA_config(), DPU_RangeProcHWA_config(), DPU_StaticClutterProc_config(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dpuStaticClutterObj, DPU_AoAProcHWA_Config_t::dynCfg, DpuConfigs_t::rangeCfg, SubFrameObj_t::staticCfg, DpuConfigs_t::staticClutterCfg, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_ioctl(), and DPC_ObjectDetection_start().
static int32_t DPC_ObjDet_staticClutterConfig (DPU_StaticClutterProc_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, MemPoolObj * CoreLocalRamObj, uint32_t * CoreLocalRamScratchUsage, DPU_StaticClutterProc_Config * cfgSave) static
Description
Configure Static Clutter DPU.
Parameters
[in] dpuHandle Handle to DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which will be the input and output of static clutter processing
[in] CoreLocalRamObj Pointer to core local RAM object to allocate local memory for the DPU, only for scratch purposes
[out] CoreLocalRamScratchUsage Core Local RAM's scratch usage in bytes
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1619 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPU_StaticClutterProc_ScratchBuf_t::buf, DPU_StaticClutterProc_ScratchBuf_t::bufSize, DPIF_ADCBufData_t::dataProperty, DPC_ObjDet_MemPoolAlloc(), DPC_OBJECTDETECTION_ENOMEM__CORE_LOCAL_RAM_STATIC_CLUTTER_SCRATCH, DPU_StaticClutterProc_config(), DPU_STATICCLUTTERPROC_SCRATCHBUFFER_BYTE_ALIGNMENT_DSP, DPU_STATICCLUTTERPROC_SCRATCHBUFFER_BYTE_ALIGNMENT_R4F, DPU_StaticClutterProc_HW_Resources_t::edmaHandle, DPU_StaticClutterProc_HW_Resources_t::edmaIn, DPU_StaticClutterProc_HW_Resources_t::edmaOut, DPU_StaticClutterProc_Config_t::hwRes, DPU_StaticClutterProc_StaticConfig_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPU_StaticClutterProc_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPU_StaticClutterProc_StaticConfig_t::numRxAntennas, DPU_StaticClutterProc_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_StaticClutterProc_StaticConfig_t::numVirtualAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_StaticClutterProc_EdmaCfg_t::ping, DPU_StaticClutterProc_EdmaCfg_t::pong, DPU_StaticClutterProc_HW_Resources_t::radarCube, DPU_StaticClutterProc_HW_Resources_t::scratchBuf, and DPU_StaticClutterProc_Config_t::staticCfg.
Referenced by DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) de-initialization function which is invoked by the application using DPM_deinit API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 2981 of file objectdetection.c.
References DPC_OBJECTDETECTION_EINVAL, DPU_AoAProcHWA_deinit(), DPU_CFARCAProcHWA_deinit(), DPU_DopplerProcHWA_deinit(), DPU_RangeProcHWA_deinit(), DPU_StaticClutterProc_deinit(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dpuStaticClutterObj, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjDet_MemPoolAlloc().
int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer * ptrResult) static
Description
DPC's (DPM registered) execute function which is invoked by the application in the DPM's execute context when the DPC issues DPM_notifyExecute API from its registered DPC_ObjectDetection_frameStart API that is invoked every frame interrupt.
Parameters
[in] handle DPM's DPC handle
[out] ptrResult Pointer to the result
Return values
Success - 0
Error - <0
Definition at line 836 of file objectdetection.c.
References DpuConfigs_t::aoaCfg, DPU_AoAProcHWA_Resources_t::azimuthStaticHeatMap, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMap, DPU_AoAProcHWA_Resources_t::azimuthStaticHeatMapSize, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMapSize, DpuConfigs_t::cfarCfg, ObjDetObj_t::commonCfg, DPC_ObjectDetection_ExecuteResult_t::compRxChanBiasMeasurement, DPU_AoAProc_DynamicConfig_t::compRxChanCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, ObjDetObj_t::compRxChanCfgMeasureOut, DPIF_DetMatrix_t::data, DPIF_RadarCube_t::data, DPU_DopplerProcHWA_HW_Resources_t::detMatrix, DPC_ObjectDetection_ExecuteResult_t::detMatrix, DPU_AoAProcHWA_Resources_t::detObjOut, DPU_AoAProcHWA_Resources_t::detObjOutSideInfo, DpuConfigs_t::dopplerCfg, DPC_ObjDet_GenDopplerWindow(), DPC_ObjDet_GetRxChPhaseComp(), DPC_ObjDet_rangeBiasRxChPhaseMeasure(), DPM_MAX_BUFFER, DPU_AoAProcHWA_config(), DPU_AoAProcHWA_process(), DPU_CFARCAProcHWA_config(), DPU_CFARCAProcHWA_process(), DPU_DopplerProcHWA_config(), DPU_DopplerProcHWA_process(), DPU_RangeProcHWA_process(), DPU_StaticClutterProc_process(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dpuStaticClutterObj, DPU_AoAProcHWA_Config_t::dynCfg, SubFrameObj_t::dynCfg, DPC_ObjectDetection_StaticClutterRemovalCfg_Base_t::enabled, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, DPU_RangeProcHWA_OutParams_t::endOfChirp, ObjDetObj_t::executeResult, DPU_RangeProcHWA_Config_t::hwRes, DPU_DopplerProcHWA_Config_t::hwRes, DPC_ObjectDetection_Stats_t::interChirpProcessingMargin, DPC_ObjectDetection_Stats_t::interFrameEndTimeStamp, DPC_ObjectDetection_Stats_t::interFrameStartTimeStamp, SubFrameObj_t::isAoAHWAparamSetOverlappedWithCFAR, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, DPU_AoAProcHWA_OutParams_t::numAoADetectedPoints, DPU_CFARCAProcHWA_OutParams_t::numCfarDetectedPoints, DPC_ObjectDetection_ExecuteResult_t::numObjOut, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, ObjDetObj_t::processCallBackCfg, DPC_ObjectDetection_ProcessCallBackCfg_t::processFrameBeginCallBackFxn, DPC_ObjectDetection_ProcessCallBackCfg_t::processInterFrameBeginCallBackFxn, DPM_Buffer_t::ptrBuffer, DPU_AoAProcHWA_Resources_t::radarCube, DPU_RangeProcHWA_HW_Resources_t::radarCube, DPC_ObjectDetection_ExecuteResult_t::radarCube, DpuConfigs_t::rangeCfg, DPU_AoAProcHWA_Config_t::res, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::searchWinSize, DPM_Buffer_t::size, SubFrameObj_t::staticCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, ObjDetObj_t::stats, DPC_ObjectDetection_ExecuteResult_t::stats, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, ObjDetObj_t::subFrameIndx, ObjDetObj_t::subFrameObj, and DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::targetDistance.
Referenced by DPC_ObjDet_GetAntGeometryDef(), and DPC_ObjDet_MemPoolAlloc().
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle) static
Description
DPC frame start function registered with DPM. This is invoked on reception of the frame start ISR from the RF front-end. This API is also invoked when application issues DPC_OBJDET_IOCTL__TRIGGER_FRAME to simulate a frame trigger (e.g for unit testing purpose).
Parameters
[in] handle DPM's DPC handle
Return values
Not applicable
Definition at line 418 of file objectdetection.c.
References DPC_Objdet_Assert, DPM_notifyExecute(), ObjDetObj_t::dpmHandle, DPC_ObjectDetection_Stats_t::frameStartIntCounter, DPC_ObjectDetection_Stats_t::frameStartTimeStamp, ObjDetObj_t::interSubFrameProcToken, ObjDetObj_t::stats, and ObjDetObj_t::subFrameIndx.
Referenced by DPC_ObjDet_MemPoolAlloc(), and DPC_ObjectDetection_ioctl().
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg * ptrInitCfg, int32_t * errCode) static
Description
DPC's (DPM registered) initialization function which is invoked by the application using DPM_init API. Among other things, this API allocates DPC instance and DPU instances (by calling DPU's init APIs) from the MemoryP osal heap. If this API returns an error of any type, the heap is not guaranteed to be in the same state as before calling the API (i.e any allocations from the heap while executing the API are not guaranteed to be deallocated in case of error), so any error from this API should be considered fatal and if the error is of _ENOMEM type, the application will have to be built again with a bigger heap size to address the problem.
Parameters
[in] dpmHandle DPM's DPC handle
[in] ptrInitCfg Handle to the framework semaphore
[out] errCode Error code populated on error
Return values
Success - 0
Error - <0
Definition at line 2828 of file objectdetection.c.
References DPM_InitCfg_t::arg, DPM_InitCfg_t::argSize, DPC_ObjectDetection_InitParams_t::CoreLocalRamCfg, DPC_OBJECTDETECTION_EINVAL, DPC_OBJECTDETECTION_EINVAL__INIT_CFG_ARGSIZE, DPC_OBJECTDETECTION_ENOMEM, DPU_AoAProcHWA_init(), DPU_CFARCAProcHWA_init(), DPU_DopplerProcHWA_init(), DPU_RangeProcHWA_init(), DPU_StaticClutterProc_init(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dpuStaticClutterObj, DPC_ObjectDetection_InitParams_t::edmaHandle, DPU_AoAProcHWA_InitParams_t::hwaHandle, DPU_DopplerProcHWA_InitCfg_t::hwaHandle, DPU_CFARCAProcHWA_InitParams_t::hwaHandle, DPU_RangeProcHWA_InitParams_t::hwaHandle, DPC_ObjectDetection_InitParams_t::hwaHandle, DPC_ObjectDetection_InitParams_t::L3ramCfg, DPC_ObjectDetection_InitParams_t::processCallBackCfg, and DPM_InitCfg_t::socHandle.
Referenced by DPC_ObjDet_MemPoolAlloc(), and DPC_ObjectDetection_ioctl().
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void * arg, uint32_t argLen) static
Description
DPC IOCTL commands configuration API which will be invoked by the application using DPM_ioctl API
Parameters
[in] handle DPM's DPC handle
[in] cmd Capture DPC specific commands
[in] arg Command specific arguments
[in] argLen Length of the arguments which is also command specific
Return values
Success - 0
Error - <0
Definition at line 2352 of file objectdetection.c.
References DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPC_ObjectDetection_CalibDcRangeSigCfg_t::cfg, DPC_ObjectDetection_CfarCfg_t::cfg, DPC_ObjectDetection_fovRangeCfg_t::cfg, DPC_ObjectDetection_fovDopplerCfg_t::cfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::cfg, DPC_ObjectDetection_fovAoaCfg_t::cfg, DPC_ObjectDetection_extMaxVelCfg_t::cfg, DPC_ObjectDetection_StaticClutterRemovalCfg_t::cfg, MemPoolObj_t::cfg, ObjDetObj_t::commonCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, ObjDetObj_t::CoreLocalRamObj, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreLocalRamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreLocalRamUsage, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMean, DPU_RangeProcHWA_HW_Resources_t::dcRangeSigMeanSize, DPC_ObjDet_Config_MeasureRxChannelBiasCfg(), DPC_ObjDet_Config_StaticClutterRemovalCfg(), DPC_ObjDet_GenRangeWindow(), DPC_ObjDet_GetRxChPhaseComp(), DPC_OBJDET_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_DOPPLER_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_RANGE_CFG, DPC_OBJDET_IOCTL__DYNAMIC_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_EXECUTE_RESULT_EXPORTED, DPC_OBJDET_IOCTL__DYNAMIC_EXT_MAX_VELOCITY, DPC_OBJDET_IOCTL__DYNAMIC_FOV_AOA, DPC_OBJDET_IOCTL__DYNAMIC_FOV_DOPPLER, DPC_OBJDET_IOCTL__DYNAMIC_FOV_RANGE, DPC_OBJDET_IOCTL__DYNAMIC_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_MULTI_OBJ_BEAM_FORM_CFG, DPC_OBJDET_IOCTL__DYNAMIC_RANGE_AZIMUTH_HEAT_MAP, DPC_OBJDET_IOCTL__DYNAMIC_STATICCLUTTER_REMOVAL_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPC_OBJDET_IOCTL__TRIGGER_FRAME, DPC_ObjDet_preStartConfig(), DPC_ObjDet_reconfigSubFrame(), DPC_OBJECTDETECTION_EINVAL__COMMAND, DPC_ObjectDetection_frameStart(), DPC_ObjectDetection_init(), DPC_OBJECTDETECTION_PRE_START_CONFIG_BEFORE_PRE_START_COMMON_CONFIG, DPU_AoAProcHWA_Cmd_CompRxChannelBiasCfg, DPU_AoAProcHWA_Cmd_ExtMaxVelocityCfg, DPU_AoAProcHWA_Cmd_FovAoACfg, DPU_AoAProcHWA_Cmd_MultiObjBeamFormingCfg, DPU_AoAProcHWA_Cmd_PrepareRangeAzimuthHeatMap, DPU_AoAProcHWA_control(), DPU_AoAProcHWA_getNumHwaParamSets(), DPU_CFARCAProcHWA_Cmd_CfarDopplerCfg, DPU_CFARCAProcHWA_Cmd_CfarRangeCfg, DPU_CFARCAProcHWA_Cmd_FovDopplerCfg, DPU_CFARCAProcHWA_Cmd_FovRangeCfg, DPU_CFARCAProcHWA_control(), DPU_RangeProcHWA_Cmd_dcRangeCfg, DPU_RangeProcHWA_Cmd_triggerProc, DPU_RangeProcHWA_config(), DPU_RangeProcHWA_control(), DPU_RANGEPROCHWA_NUM_HWA_PARAM_SETS, SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dynCfg, DPC_ObjectDetection_PreStartCfg_t::dynCfg, ObjDetObj_t::edmaHandle, DPC_ObjectDetection_DynCfg_t::extMaxVelCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovRange, ObjDetObj_t::hwaMemBankAddr, ObjDetObj_t::hwaMemBankSize, DPU_RangeProcHWA_Config_t::hwRes, ObjDetObj_t::interSubFrameProcToken, ObjDetObj_t::isCommonCfgReceived, ObjDetObj_t::L3RamObj, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamUsage, DPU_CFARCAProc_FovCfg_t::max, DPC_ObjectDetection_PreStartCfg_t::memUsage, DPU_CFARCAProc_FovCfg_t::min, DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DpuConfigs_t::rangeCfg, DPC_ObjectDetection_MemCfg_t::size, SubFrameObj_t::staticCfg, DPC_ObjectDetection_PreStartCfg_t::staticCfg, ObjDetObj_t::stats, DPC_ObjectDetection_ExecuteResultExportedInfo_t::subFrameIdx, ObjDetObj_t::subFrameIndx, ObjDetObj_t::subFrameObj, DPC_ObjectDetection_Stats_t::subFramePreparationCycles, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapUsed.
Referenced by DPC_ObjDet_MemPoolAlloc(), and DPC_ObjDet_preStartConfig().
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) start function which is invoked by the application using DPM_start API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 1085 of file objectdetection.c.
References DPC_ObjDet_GenRangeWindow(), DPC_ObjDet_reconfigSubFrame(), DPU_AoAProcHWA_getNumHwaParamSets(), DPU_RangeProcHWA_Cmd_triggerProc, DPU_RangeProcHWA_config(), DPU_RangeProcHWA_control(), DPU_RANGEPROCHWA_NUM_HWA_PARAM_SETS, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuRangeObj, DPC_ObjectDetection_Stats_t::frameStartIntCounter, ObjDetObj_t::isCommonCfgReceived, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, DpuConfigs_t::rangeCfg, SubFrameObj_t::staticCfg, ObjDetObj_t::stats, ObjDetObj_t::subFrameIndx, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjDet_MemPoolAlloc().
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) stop function which is invoked by the application using DPM_stop API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 1151 of file objectdetection.c.
References ObjDetObj_t::interSubFrameProcToken, and ObjDetObj_t::subFrameIndx.
Referenced by DPC_ObjDet_MemPoolAlloc().
Copyright 2020, Texas Instruments Incorporated